export interface NodeMetadataF6 {
  id: string;
  campo: string;
  campoTag: string;
  materia: string;
  materiaFolder: string;
  grado: '1er_Grado' | '2do_Grado' | '3er_Grado';
  gradoDisplay: string;
  temaNum: number;
  temaTitulo: string;
  tituloProyecto: string;
  ejes: string[];
  pda: string;
  detonadoras: string[];
  inicioDetalle: string;
  desarrolloDetalle: string;
  cierreDetalle: string;
  evaluacionCriterios: string[];
  materiales: string;
  entregable: string;
}

// 50 planeaciones únicas para LENGUAJES en Secundaria (Fase 6)
export const lenguajesF6Data: NodeMetadataF6[] = [
  // --- ESPAÑOL 1º, 2º, 3º ---
  {
    id: 'f6-len-01',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 1,
    temaTitulo: 'La diversidad de lenguas y su uso en la comunicación familiar y comunitaria',
    tituloProyecto: 'Voces de Nuestra Tierra: Cartografía y Memoria de la Diversidad Lingüística',
    ejes: ['Interculturalidad Crítica', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce la riqueza lingüística de México y el mundo, a partir de obras literarias procedentes de distintas culturas, valorando la preservación de las lenguas originarias.',
    detonadoras: [
      '¿Por qué México cuenta con 68 lenguas indígenas nacionales y qué sabiduría ancestral encierran?',
      '¿Cómo el contacto entre el español y las lenguas originarias enriqueció nuestro vocabulario cotidiano?',
      '¿Qué factores provocan el desplazamiento y pérdida de una lengua materna?',
      '¿Cómo podemos promover el respeto hacia los hablantes de lenguas indígenas en nuestra escuela?'
    ],
    inicioDetalle: 'Audición de poemas en náhuatl y zapoteco con traducción simultánea. Análisis del concepto de plurilingüismo.',
    desarrolloDetalle: 'Mapeo Lingüístico: Elaborar en equipos un mapa sonoro y visual de las familias lingüísticas de México, investigando indigenismos de uso diario (chayote, tianguis, mecate).',
    cierreDetalle: 'Exposición de mapas sonoros en el aula y reflexión sobre el orgullo lingüístico nacional.',
    evaluacionCriterios: [
      'Reconocimiento y valoración de la diversidad lingüística de México',
      'Investigación etimológica de préstamos lingüísticos originarios',
      'Actitud de respeto y empatía hacia los hablantes de lenguas indígenas'
    ],
    materiales: 'Mapas de México del INPI, grabaciones de audio, cartulinas y plumones.',
    entregable: 'Mapa Mural Ilustrado "Las 68 Lenguas Vivas de México: Riqueza y Resistencia".'
  },
  {
    id: 'f6-len-02',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 2,
    temaTitulo: 'La diversidad étnica, cultural y lingüística de México a favor de una sociedad intercultural',
    tituloProyecto: 'El Manifiesto del Diálogo: Lectura Crítica y Ensayos de Interculturalidad',
    ejes: ['Interculturalidad Crítica', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Comprende las ideas centrales y secundarias de textos relacionados con la diversidad étnica, cultural y lingüística, que favorecen una sociedad intercultural, para comentarlas en forma oral y escrita.',
    detonadoras: [
      '¿Cuál es la diferencia entre una sociedad multicultural (que solo tolera) y una sociedad intercultural (que dialoga y aprende)?',
      '¿Cómo identificamos ideas principales y argumentos en un ensayo sobre derechos indígenas?',
      '¿Qué prejuicios culturales persisten en los medios masivos de comunicación?',
      '¿Cómo construimos puentes de entendimiento entre jóvenes urbanos y rurales?'
    ],
    inicioDetalle: 'Lectura comentada de un ensayo de Guillermo Bonfil Batalla sobre el México Profundo.',
    desarrolloDetalle: 'Taller de Comprensión Crítica: Extraer tesis central, argumentos y contraargumentos en textos sobre interculturalidad y redactar un comentario crítico fundamentado.',
    cierreDetalle: 'Mesa redonda sobre el respeto a la diversidad en la secundaria. Coevaluación de textos.',
    evaluacionCriterios: [
      'Identificación precisa de ideas principales y estructura argumentativa',
      'Redacción fluida de comentarios críticos con postura fundamentada',
      'Participación activa y asertiva en el diálogo intercultural'
    ],
    materiales: 'Ensayos seleccionados, esquemas de análisis textual, hojas membretadas.',
    entregable: 'Comentario Crítico Escrito "De la Coexistencia al Diálogo Intercultural Verdadero".'
  },
  {
    id: 'f6-len-03',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 3,
    temaTitulo: 'Las lenguas como manifestación de la identidad y del sentido de pertenencia',
    tituloProyecto: 'Narrativas de Identidad: Relatos Autobiográficos y Variantes Regionales del Español',
    ejes: ['Apropiación de las Culturas', 'Inclusión'],
    pda: 'Fase 6 (2º Secundaria) - Comprende y redacta textos narrativos sobre la construcción de la identidad y el sentido de pertenencia, a partir del análisis de variantes del español en México y el mundo.',
    detonadoras: [
      '¿Cómo nuestra forma de hablar (entonación, modismos, vocabulario regional) refleja quiénes somos y de dónde venimos?',
      '¿Por qué ninguna variante del español es "mejor" o "peor" que otra?',
      '¿Cómo estructuramos un relato autobiográfico con descripciones sensoriales y reflexiones profundas?',
      '¿Qué anécdota familiar ilustra mejor el sentido de pertenencia a tu comunidad?'
    ],
    inicioDetalle: 'Muestrario de audios de variantes dialectales del español (norteño, yucateco, costeño, rioplatense, andaluz).',
    desarrolloDetalle: 'Taller de Narrativa Autobiográfica: Redactar un capítulo de memorias personales incorporando expresiones lingüísticas regionales y analizando su valor identitario.',
    cierreDetalle: 'Lectura en atril de fragmentos autobiográficos en el Café Literario del salón.',
    evaluacionCriterios: [
      'Narración estructurada con voz propia y sentido de pertenencia',
      'Uso reflexivo de variantes dialectales y recursos expresivos',
      'Puntuación, coherencia y riqueza léxica en el relato'
    ],
    materiales: 'Muestras de audios dialectales, formatos de autobiografía, colores.',
    entregable: 'Crónica Autobiográfica Ilustrada "El Acento de Mis Recuerdos y Mis Raíces".'
  },
  {
    id: 'f6-len-04',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 4,
    temaTitulo: 'El dinamismo de las lenguas y su relevancia como patrimonio cultural',
    tituloProyecto: 'El Español en Evolución: Cambios Temporales, Neologismos y Redes Sociales',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Reconoce cambios temporales y geográficos del español en la comunidad, el país o el mundo hispano, analizando neologismos, préstamos lingüísticos y transformaciones en la era digital.',
    detonadoras: [
      '¿Cómo cambia una lengua viva a lo largo de los siglos (del español medieval del Cantar de Mio Cid al español actual)?',
      '¿Qué nuevos términos digitales (chatear, viralizar, escanear) se han incorporado al diccionario de la RAE?',
      '¿Por qué las jergas juveniles son una prueba del dinamismo del idioma?',
      '¿Cómo equilibrar la creatividad lingüística con la norma gramatical?'
    ],
    inicioDetalle: 'Comparación de un texto del siglo XVI con un mensaje de texto actual. Identificación de arcaísmos y neologismos.',
    desarrolloDetalle: 'Elaboración del Diccionario Dinámico de Neologismos y Extranjerismos: Investigar el origen etimológico de 10 palabras modernas, su adaptación al español y ejemplos de uso.',
    cierreDetalle: 'Debate sobre la evolución del idioma en redes sociales y entrega de fichas lexicográficas.',
    evaluacionCriterios: [
      'Comprensión del proceso histórico de evolución y dinamismo lingüístico',
      'Análisis morfológico y semántico de neologismos y préstamos',
      'Rigor en la redacción de definiciones lexicográficas'
    ],
    materiales: 'Diccionarios históricos, textos coloniales, acceso a internet.',
    entregable: 'Diccionario Ilustrado de Neologismos y Transformaciones del Español.'
  },
  {
    id: 'f6-len-05',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 5,
    temaTitulo: 'La función creativa del español en la expresión de necesidades e intereses comunitarios',
    tituloProyecto: 'Letras de Cambio: Cuentos y Ensayos de Propuesta para Problemas Comunitarios',
    ejes: ['Pensamiento Crítico', 'Inclusión', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (3º Secundaria) - Crea textos literarios de distintos géneros (cuentos, ensayos, dramaturgia) para ofrecer una propuesta de solución a problemas de la comunidad, ejerciendo el pensamiento crítico.',
    detonadoras: [
      '¿Cómo puede la literatura ser un vehículo de denuncia y transformación social?',
      '¿Qué problemática local (contaminación, falta de espacios juveniles, deserción) te conmueve?',
      '¿Cómo diseñamos personajes realistas que enfrenten y resuelvan estos retos en una ficción?',
      '¿Cómo redactamos un desenlace que inspire acción y esperanza ciudadana?'
    ],
    inicioDetalle: 'Lectura de cuentos de realismo social latinoamericano (Juan Rulfo, Elena Poniatowska).',
    desarrolloDetalle: 'Taller de Creación Literaria Comprometida: Escribir un cuento o ensayo narrativo donde la trama gire en torno a la solución comunitaria de un problema ambiental o social.',
    cierreDetalle: 'Presentación de lecturas dramatizadas y compilación en la Antología de Literatura Comunitaria.',
    evaluacionCriterios: [
      'Creatividad narrativa y pertinencia en el abordaje de problemáticas sociales',
      'Construcción verosímil de personajes, conflicto y resolución crítica',
      'Calidad estilística, riqueza léxica y ortografía avanzada'
    ],
    materiales: 'Textos modelo de literatura social, guías de escritura narrativa, hojas de impresión.',
    entregable: 'Cuento de Ficción Social Ilustrado para la Antología "Voces que Transforman".'
  },
  {
    id: 'f6-len-06',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 6,
    temaTitulo: 'Los elementos y los recursos estéticos de la lengua española en la literatura oral y escrita',
    tituloProyecto: 'Dramaturgia Viva: Recursos Estéticos y Puesta en Escena de Problemáticas del Entorno',
    ejes: ['Artes y Experiencias Estéticas', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Usa creativa e intencionalmente las características y los recursos estéticos de textos dramáticos, para escenificar situaciones vinculadas con la comunidad.',
    detonadoras: [
      '¿Cómo transmiten los diálogos teatrales el subtexto, la tensión y las emociones humanas?',
      '¿Qué recursos estéticos (metáforas, ironía, contrastes) enriquecen el guion dramático?',
      '¿Cómo orientan las acotaciones la utilería, iluminación y expresión corporal de los actores?',
      '¿Qué conflicto de convivencia en la escuela podemos llevar a las tablas?'
    ],
    inicioDetalle: 'Lectura dramatizada de una escena de teatro clásico y contemporáneo. Análisis del conflicto.',
    desarrolloDetalle: 'Laboratorio de Dramaturgia: En equipos de 4, escribir una obra en un acto con 3 escenas, listado de personajes, acotaciones técnicas y diálogos cargados de figuras retóricas.',
    cierreDetalle: 'Ensayo general y lectura en atril con utilería básica. Coevaluación del impacto escénico.',
    evaluacionCriterios: [
      'Estructura técnica de libreto teatral (escenas, diálogos, acotaciones)',
      'Uso intencional de recursos estéticos y figuras literarias',
      'Pertinencia y profundidad en el abordaje de dilemas comunitarios'
    ],
    materiales: 'Textos teatrales breves, libretos en blanco, elementos de utilería.',
    entregable: 'Libreto Teatral Original en Un Acto y Guía de Montaje Escénico.'
  },
  {
    id: 'f6-len-07',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 7,
    temaTitulo: 'Textos literarios escritos en español o traducidos (géneros y juicio estético)',
    tituloProyecto: 'Tertulias Literarias: Crítica, Géneros Literarios y Juicio Estético',
    ejes: ['Apropiación de las Culturas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce el valor estético de diversos géneros literarios en textos de su elección (lírica, narrativa, dramática), para elaborar comentarios y promover su lectura.',
    detonadoras: [
      '¿Qué distingue a la poesía lírica de una novela de misterio o una comedia teatral?',
      '¿Cómo emitimos un juicio estético fundamentado sin limitarnos a decir "me gustó" o "no me gustó"?',
      '¿Cómo influye la época histórica en la forma de escribir de un autor?',
      '¿Qué libro clásico o contemporáneo recomendarías a la comunidad escolar?'
    ],
    inicioDetalle: 'Exhibición de portadas y fragmentos de grandes obras de la literatura universal.',
    desarrolloDetalle: 'Taller de Reseña Crítica: Leer una obra breve, analizar sus recursos literarios, temática y emitir una reseña crítica con juicio estético para el periódico escolar.',
    cierreDetalle: 'Tertulia literaria con intercambio de reseñas y recomendaciones.',
    evaluacionCriterios: [
      'Identificación y análisis de características del género literario',
      'Argumentación sólida en la emisión del juicio estético',
      'Redacción atractiva y persuasiva en la reseña literaria'
    ],
    materiales: 'Antología de cuentos universales, fichas de reseña crítica, cartulinas.',
    entregable: 'Reseña Literaria Crítica Publicada para la Biblioteca Escolar.'
  },
  {
    id: 'f6-len-08',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 8,
    temaTitulo: 'Creaciones literarias tradicionales y contemporáneas (mitos, leyendas, corridos)',
    tituloProyecto: 'Del Mito al Podcast: Adaptación de la Tradición Oral a Medios Digitales',
    ejes: ['Apropiación de las Culturas', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (2º Secundaria) - Valora textos literarios tradicionales y contemporáneos (mitos, leyendas, corridos, décimas); los adapta a otros lenguajes (audiovisual, podcast, historieta) para sensibilizar a la comunidad.',
    detonadoras: [
      '¿Cómo se han transmitido los mitos y leyendas prehispánicas y coloniales a través de generaciones?',
      '¿Qué estructura poética y musical tiene el corrido tradicional mexicano como crónica popular?',
      '¿Cómo adaptamos un relato oral antiguo a un guion de radioteatro o podcast sonoro?',
      '¿Por qué rescatar la tradición oral fortalece nuestra memoria histórica?'
    ],
    inicioDetalle: 'Escucha de un corrido histórico de la Revolución Mexicana y una leyenda náhuatl.',
    desarrolloDetalle: 'Taller de Guion para Audio-Ficción: Investigar una leyenda local, redactar el guion sonoro con voces, música incidental y efectos sonoros Foley, y grabar el episodio piloto.',
    cierreDetalle: 'Audición grupal de podcasts de leyendas mexicanas y coevaluación.',
    evaluacionCriterios: [
      'Investigación y respeto por las fuentes de la tradición oral',
      'Calidad en la adaptación al formato de guion radiofónico o podcast',
      'Creatividad en la ambientación sonora y modulación vocal'
    ],
    materiales: 'Grabadoras de audio, celulares, textos de leyendas tradicionales, instrumentos caseros.',
    entregable: 'Episodio de Podcast / Audio-Cuento "Ecos de Leyenda: Tradición Oral en la Era Digital".'
  },
  {
    id: 'f6-len-09',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 9,
    temaTitulo: 'Los géneros periodísticos de interpretación para preservar la memoria colectiva',
    tituloProyecto: 'Crónicas del Siglo XXI: Reportajes de Fondo y Memoria Comunitaria',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Analiza los sucesos más significativos de la comunidad y los comunica empleando las características de los géneros periodísticos de interpretación (crónica y reportaje), para preservar la memoria colectiva.',
    detonadoras: [
      '¿Cuál es la diferencia entre una noticia inmediata, un artículo de opinión y un reportaje de investigación a fondo?',
      '¿Cómo se construye una crónica combinando datos rigurosos con recursos literarios descriptivos?',
      '¿Qué acontecimiento de nuestra colonia merece una investigación periodística exhaustiva?',
      '¿Por qué el periodismo de calidad es un pilar indispensable de la democracia?'
    ],
    inicioDetalle: 'Lectura de fragmentos de grandes crónicas periodísticas de Carlos Monsiváis y Elena Poniatowska.',
    desarrolloDetalle: 'Taller de Periodismo de Investigación: En equipos de 3, seleccionar un tema comunitario (mercados tradicionales, historias de superación, impacto ambiental), realizar entrevistas, contrastar fuentes y redactar un reportaje de fondo.',
    cierreDetalle: 'Edición y publicación de la Revista Periodística Digital de 3º de Secundaria.',
    evaluacionCriterios: [
      'Rigor en la investigación documental y testimonial de campo',
      'Estructura formal de la crónica o reportaje con entrada, cuerpo y remate',
      'Ética periodística, contrastación de datos y calidad de redacción'
    ],
    materiales: 'Periódicos y revistas de fondo, formatos de entrevista, computadoras o pliegos.',
    entregable: 'Reportaje de Fondo Ilustrado "Crónicas de Nuestra Comunidad: Historia, Retos y Futuro".'
  },
  {
    id: 'f6-len-10',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 10,
    temaTitulo: 'Comunicación asertiva y dialógica para erradicar expresiones de violencia de género',
    tituloProyecto: 'Voces por la Igualdad: Debate, Argumentación y Protocolos de Prevención de Violencia',
    ejes: ['Igualdad de Género', 'Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Participa en un debate acerca de algunas expresiones de violencia -como la de género y la sexual- para argumentar una postura de rechazo, elaborando oficios e invitaciones formales.',
    detonadoras: [
      '¿Cómo se manifiestan los micromachismos y la violencia verbal en el noviazgo y en la escuela?',
      '¿Cómo argumentamos con firmeza y respeto en un debate formal sin caer en agresiones?',
      '¿Qué documentos formales (oficios, cartas de invitación) se requieren para convocar a especialistas a un foro escolar?',
      '¿Qué compromisos de cero tolerancia a la violencia asumimos en nuestro salón?'
    ],
    inicioDetalle: 'Proyección del violentómetro del IPN. Análisis de las escalas de agresión en la convivencia juvenil.',
    desarrolloDetalle: 'Taller de Debate y Gestión Institucional: Redactar oficios formales para invitar a psicólogos o personal de derechos humanos y estructurar argumentos lógicos con evidencia empírica para el debate.',
    cierreDetalle: 'Realización del Debate Formal en el auditorio y firma del Manifiesto Escolar de Igualdad y No Violencia.',
    evaluacionCriterios: [
      'Argumentación lógica basada en derechos humanos y perspectiva de género',
      'Redacción de documentos formales de gestión con estructura protocolaria',
      'Uso de comunicación asertiva y escucha respetuosa durante el debate'
    ],
    materiales: 'Formatos de oficios de gestión, copias del Violentómetro, tarjetas de debate.',
    entregable: 'Oficio de Gestión Formal y Memoria del Debate "Cero Violencia en la Escuela y el Noviazgo".'
  },

  // --- INGLÉS 1º, 2º, 3º ---
  {
    id: 'f6-len-11',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 11,
    temaTitulo: 'La diversidad lingüística y sus formas de expresión en México y el mundo (Inglés)',
    tituloProyecto: 'World Languages Passport: Countries, Nationalities and Basic Data in English',
    ejes: ['Interculturalidad Crítica', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Hace uso del alfabeto, números y expresiones básicas en inglés para nombrar y recuperar datos factuales y características básicas de lenguas reconocidas en México y el mundo.',
    detonadoras: [
      'How does English connect people from different cultures around the world?',
      'How do we ask and give personal information (nationality, language spoken, age) in English?',
      'What indigenous languages from Mexico can we introduce to foreign students in English?',
      'Why is learning a second language an open door to global citizenship?'
    ],
    inicioDetalle: 'Icebreaker: World Greetings Song and phonetic drill with the English alphabet and numbers.',
    desarrolloDetalle: 'Language Passport Workshop: In pairs, design an International Cultural Passport describing countries, official languages, indigenous languages of Mexico, and personal profiles using "Verb to be" and basic wh-questions.',
    cierreDetalle: 'Speed-dating interview in English: Asking partners for their name, origin, and languages spoken.',
    evaluacionCriterios: [
      'Correct usage of verb to be, subject pronouns, and nationality adjectives',
      'Accurate spelling and pronunciation of numbers and basic vocabulary',
      'Cultural appreciation and enthusiastic communication in English'
    ],
    materiales: 'Passport templates, world map, color markers, flag stickers.',
    entregable: 'International Cultural Passport and Spoken Dialogue in English.'
  },
  {
    id: 'f6-len-12',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 12,
    temaTitulo: 'La identidad y cultura de pueblos de habla inglesa',
    tituloProyecto: 'Cultural Mosaic: Traditions, Food and Identity of English-Speaking Nations',
    ejes: ['Interculturalidad Crítica', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Elabora fichas informativas e infografías en inglés sobre rasgos identitarios de pueblos de habla inglesa (Reino Unido, EUA, Canadá, Australia, Sudáfrica: tradiciones, comida, acentos).',
    detonadoras: [
      'What are the key cultural differences between British, American, Australian, and South African English?',
      'How do traditional celebrations (Thanksgiving, Saint Patrick’s, Diwali in English communities) express cultural identity?',
      'How can we compare Mexican traditions with celebrations in English-speaking nations using comparative adjectives?',
      'How do we structure an informative brochure in English with clear headings and visual appeal?'
    ],
    inicioDetalle: 'Listening activity comparing accents from London, New York, and Sydney. Identification of key vocabulary.',
    desarrolloDetalle: 'Infographic Design Workshop: Research one English-speaking country and create an infographic covering geography, typical dishes, traditional celebrations, and famous historical figures with comparative sentences.',
    cierreDetalle: 'Gallery Walk presentation in English with peer evaluation rubric.',
    evaluacionCriterios: [
      'Accurate use of comparative and superlative adjectives in English',
      'Depth and cultural accuracy in the presentation of traditions and identity',
      'Visual organization, graphic design, and grammatical correctness'
    ],
    materiales: 'Cardstock, printouts of English-speaking cultures, dictionaries, tablets.',
    entregable: 'Illustrated Cultural Infographic "Exploring English-Speaking Cultures Around the World".'
  },
  {
    id: 'f6-len-13',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 13,
    temaTitulo: 'El uso del inglés para expresar necesidades y problemas de la comunidad',
    tituloProyecto: 'Eco-Heroes: Community Campaigns and Problem-Solving Proposals in English',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Organiza una campaña en inglés sobre soluciones a problemas de la comunidad (ahorro de agua, reciclaje, reforestación), diseñando carteles, discursos persuasivos y folletos informativos.',
    detonadoras: [
      'How can we express urgency and call for environmental action using modals in English (must, should, have to)?',
      'What local problems can we address in an international social media campaign in English?',
      'How do we write a persuasive slogan and an action plan with sequence connectors (First, Next, Finally)?',
      'Why is global environmental awareness a responsibility of our generation?'
    ],
    inicioDetalle: 'Analysis of famous international youth environmental speeches (e.g. youth climate summits).',
    desarrolloDetalle: 'Campaign Production Workshop: In teams of 4, design an environmental campaign with a digital poster, a 30-second persuasive speech in English, and a leaflet with 5 concrete action steps using modal verbs.',
    cierreDetalle: 'Pitch Presentation: Each team presents their campaign in English to the class.',
    evaluacionCriterios: [
      'Effective use of modal verbs (should, must, can) and imperative sentences',
      'Persuasive rhetoric, fluency, and pronunciation in the spoken presentation',
      'Relevance, creativity, and visual impact of campaign materials'
    ],
    materiales: 'Poster boards, markers, audio recording device for oral pitch.',
    entregable: 'Campaign Kit "Save Our Community: Green Actions for Global Impact" (Poster & Speech Script).'
  },
  {
    id: 'f6-len-14',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 14,
    temaTitulo: 'Manifestaciones culturales, lingüísticas y artísticas en inglés a favor de la interculturalidad',
    tituloProyecto: 'Comic Strips for Empathy: Graphic Stories and Conflict Resolution in English',
    ejes: ['Inclusión', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (2º Secundaria) - Interpreta y elabora historietas, cómics o mangas en inglés sobre situaciones donde se rescata la importancia de la comunicación asertiva y la interculturalidad para resolver conflictos.',
    detonadoras: [
      'How do comic strips combine visual panels, speech bubbles, and onomatopoeias to tell powerful stories?',
      'How do we write realistic dialogues in English using past continuous and simple past ("While they were arguing, she said...")?',
      'How can a story teach us to solve misunderstandings with empathy rather than anger?',
      'What visual metaphors best represent peace and intercultural friendship?'
    ],
    inicioDetalle: 'Reading and analyzing panels from popular graphic novels and comics in English.',
    desarrolloDetalle: 'Comic Strip Creation Workshop: In pairs, write a 6-panel comic strip in English featuring characters from different backgrounds who overcome a cultural misunderstanding through assertive dialogue.',
    cierreDetalle: 'Class Comic Book Exhibition: Reading and peer feedback using a rubric.',
    evaluacionCriterios: [
      'Coherent narrative sequence with correct punctuation in English dialogues',
      'Use of narrative tenses (Past Simple & Past Continuous) and speech conventions',
      'Creative visual design and positive intercultural message'
    ],
    materiales: 'Comic strip templates, fine-liner pens, colored pencils, English dictionaries.',
    entregable: 'Illustrated 6-Panel Comic Strip "Building Bridges: An Intercultural Story".'
  },
  {
    id: 'f6-len-15',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 15,
    temaTitulo: 'Creaciones literarias tradicionales y contemporáneas en inglés (Poesía y Cuentos Cortos)',
    tituloProyecto: 'Young Poets & Storytellers: Literary Devices, Metaphors and Short Stories in English',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (3º Secundaria) - Crea poemas cortos y textos narrativos breves en inglés a partir del uso de recursos estéticos (metáforas, rimas, aliteraciones, personificación) para expresar vivencias y emociones.',
    detonadoras: [
      'How do metaphors and similes transform simple sentences into evocative English poetry?',
      'What are the characteristics of haikus, limericks, and free verse in the English poetic tradition?',
      'How do we build sensory imagery (sight, sound, touch, smell) in an English short story?',
      'What personal feeling or memory would you like to capture in a poem?'
    ],
    inicioDetalle: 'Reading classic and modern English poems (Robert Frost, Maya Angelou). Highlighting literary devices.',
    desarrolloDetalle: 'Creative Writing Workshop: Draft a 2-stanza poem and a 150-word flash fiction in English using at least 3 literary devices (simile, metaphor, alliteration) and rich adjectives.',
    cierreDetalle: 'Poetry Slam Session: Voluntary recitation with expressive rhythm and intonation.',
    evaluacionCriterios: [
      'Application of figurative language (similes, metaphors, imagery) in English',
      'Grammatical accuracy, rich vocabulary, and poetic rhythm',
      'Expressive reading and pronunciation during the poetry performance'
    ],
    materiales: 'Poetry anthology samples, decorative writing paper, highlighters.',
    entregable: 'Illustrated Poem and Flash Fiction Sheet for the "Classroom Literary Journal in English".'
  },

  // --- ARTES 1º, 2º, 3º ---
  {
    id: 'f6-len-16',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 16,
    temaTitulo: 'Diversidad de lenguajes artísticos en la riqueza pluricultural de México',
    tituloProyecto: 'Murales Comunitarios: Espacio, Tiempo, Ritmo y Simbolismo del Arte Popular',
    ejes: ['Artes y Experiencias Estéticas', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce en manifestaciones artísticas de México y el mundo el uso del cuerpo, espacio y tiempo, para valorarlas como parte de la riqueza pluricultural, experimentando con técnicas visuales y escénicas.',
    detonadoras: [
      '¿Cómo el muralismo mexicano de Rivera, Siqueiros y Orozco transformó los muros públicos en libros de historia visual?',
      '¿De qué manera los colores, texturas y líneas en una pintura expresan el ritmo del tiempo y las emociones colectivas?',
      '¿Cómo representamos la identidad de nuestra comunidad en un boceto de mural colectivo?',
      '¿Por qué el arte es un derecho humano y un espacio de encuentro para todos?'
    ],
    inicioDetalle: 'Proyección de detalles de murales históricos mexicanos. Análisis de la composición espacial.',
    desarrolloDetalle: 'Taller de Bocetaje de Mural en Equipos: Diseñar la composición a escala de un mural escolar sobre la historia y biodiversidad local, aplicando teoría del color y equilibrio visual.',
    cierreDetalle: 'Presentación de bocetos y selección comunitaria para el mural efímero del pasillo escolar.',
    evaluacionCriterios: [
      'Manejo de elementos de las artes visuales (línea, color, forma, espacio y textura)',
      'Pertinencia y profundidad en la representación de la identidad comunitaria',
      'Colaboración armónica y trabajo en equipo'
    ],
    materiales: 'Papel kraft largo, acrílicos, pinceles, paletas de mezclas, cinta de pintor.',
    entregable: 'Boceto a Escala y Pintura Colectiva del Mural Escolar "Nuestra Tierra en Colores".'
  },
  {
    id: 'f6-len-17',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 17,
    temaTitulo: 'Los lenguajes artísticos en la expresión de problemas de la comunidad',
    tituloProyecto: 'Instalaciones Efímeras: Escultura, Urbanismo Táctico y Arte Crítico',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Investiga propuestas artísticas colectivas de entornos rurales y urbanos a favor de la inclusión y la sustentabilidad, para presentar una postura crítica sobre un problema de la comunidad mediante una instalación artística.',
    detonadoras: [
      '¿Qué es una INSTALACIÓN ARTÍSTICA que transforma un espacio cotidiano para provocar una reflexión profunda?',
      '¿Cómo convertimos desechos plásticos, cartón y metales en esculturas con mensaje ecológico?',
      '¿Qué impacto emocional genera el arte contemporáneo en los transeúntes de la escuela?',
      '¿Cómo evaluamos la fuerza crítica y estética de una obra tridimensional?'
    ],
    inicioDetalle: 'Recorrido virtual por obras de arte conceptual y land-art de artistas contemporáneos.',
    desarrolloDetalle: 'Taller de Escultura e Instalación Efímera: En equipos de 5, recolectar botellas y tapas de plástico para montar una instalación escultórica en el patio escolar que visibilice el consumo de plásticos de un solo uso.',
    cierreDetalle: 'Inauguración de la Instalación con cédula curatorial y debate con la comunidad escolar.',
    evaluacionCriterios: [
      'Conceptualización crítica y pertinencia social de la instalación artística',
      'Uso innovador y estético de materiales reciclados en la composición 3D',
      'Redacción rigurosa de la cédula curatorial explicativa'
    ],
    materiales: 'Plásticos reciclados limpios, alambres, cartón, pintura, cédulas en cartón.',
    entregable: 'Instalación Artística Tridimensional en el Patio Escolar y Cédula Curatorial Crítica.'
  },
  {
    id: 'f6-len-18',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 18,
    temaTitulo: 'Valor estético de la naturaleza y categorías estéticas (lo sublime, lo grotesco, lo trágico, lo cómico)',
    tituloProyecto: 'La Mirada Filosófica del Arte: Categorías Estéticas y Fotografía Narrativa',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Identifica y argumenta categorías estéticas como lo bello, lo sublime, lo grotesco, lo trágico, lo cómico y lo siniestro, al apreciarlas en manifestaciones artísticas, la naturaleza y la vida cotidiana.',
    detonadoras: [
      '¿Qué diferencia a lo BELLO (armónico) de lo SUBLIME (la majestuosidad imponente de una tormenta o volcán que asombra y estremece)?',
      '¿Por qué el arte a veces utiliza lo GROTESCO o lo TRÁGICO para despertar la conciencia humana?',
      '¿Cómo capturamos con una cámara fotográfica o dibujo un instante cotidiano cargado de belleza o dramatismo?',
      '¿Cómo defendemos con argumentos filosóficos nuestro juicio estético sobre una obra?'
    ],
    inicioDetalle: 'Proyección de pinturas clásicas y fotografías de la naturaleza ilustrando las 6 categorías estéticas.',
    desarrolloDetalle: 'Taller de Fotografía y Juicio Estético: Tomar 4 fotografías en el entorno escolar/comunitario que ejemplifiquen categorías distintas (ej. Lo bello en una flor, lo sublime en un cielo nublado, lo cómico en un juego) y redactar el ensayo curatorial.',
    cierreDetalle: 'Exposición Fotográfica "Las Seis Miradas del Arte" y debate estético.',
    evaluacionCriterios: [
      'Comprensión rigurosa de las categorías estéticas filosóficas',
      'Calidad compositiva fotográfica (encuadre, iluminación, plano)',
      'Argumentación conceptual y justificación teórica en el ensayo'
    ],
    materiales: 'Cámaras de celular, papel fotográfico o impresiones, cartulina negra para montaje.',
    entregable: 'Serie Fotográfica Curada de 4 Obras con Ensayo Filosófico de Juicio Estético.'
  },
  {
    id: 'f6-len-19',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 19,
    temaTitulo: 'Sistemas alternativos y aumentativos de comunicación como herramientas creativas de inclusión',
    tituloProyecto: 'El Arte que Rompe el Silencio: Lengua de Señas Mexicana, Braille y Pintura Táctil',
    ejes: ['Inclusión', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (3º Secundaria) - Crea códigos y obras que favorecen la inclusión a través del uso artístico de texturas, formas, movimientos corporales, Lengua de Señas Mexicana (LSM) y sistema Braille, para sensibilizar sobre la diversidad.',
    detonadoras: [
      '¿Cómo percibe el arte una persona con discapacidad visual a través del tacto y las texturas en relieve?',
      '¿De qué manera la Lengua de Señas Mexicana (LSM) es una danza expresiva de manos, gestos y espacio tridimensional?',
      '¿Cómo incorporamos el alfabeto Braille en una pintura para que sea accesible a personas ciegas?',
      '¿Por qué una sociedad verdaderamente culta es aquella que garantiza accesibilidad universal en todos los museos y escuelas?'
    ],
    inicioDetalle: 'Experiencia sensorial con ojos vendados: Reconocimiento táctil de relieves y texturas. Aprendizaje del dactilológico LSM.',
    desarrolloDetalle: 'Taller de Arte Háptico y Táctil: Crear una pintura táctil utilizando arena, semillas, estambre y pasta de relieve, incorporando un poema en sistema Braille punteado a mano y señas de LSM.',
    cierreDetalle: 'Recorrido sensorial con antifaces en el "Museo Inclusivo de Arte Táctil". Metacognición.',
    evaluacionCriterios: [
      'Integración armónica de sistemas aumentativos (LSM y Braille) en la obra',
      'Calidad técnica en el diseño de texturas táctiles y relieve háptico',
      'Sensibilidad y compromiso ético con la accesibilidad y la inclusión social'
    ],
    materiales: 'Cartón grueso, arena fina, plastilina, semillas, punzones para Braille, antifaces.',
    entregable: 'Cuadro de Arte Táctil Accesible con Poema en Braille y Traducción a Lengua de Señas Mexicana.'
  },
  {
    id: 'f6-len-20',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes / Español',
    materiaFolder: 'Artes',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 20,
    temaTitulo: 'Memoria colectiva representada por medios artísticos (Música, Danza y Tradición)',
    tituloProyecto: 'El Son de la Memoria: Rescate de Cantos Tradicionales, Zapateado y Ritmos Regionales',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Reinterpreta, mediante características de géneros artísticos (danza folclórica, son tradicional, música de cuerdas), acontecimientos y memorias significativas de la comunidad para fortalecer el sentido de pertenencia.',
    detonadoras: [
      '¿Cómo cuentan los sones y danzas tradicionales las batallas, amores y faenas del pueblo?',
      '¿Qué relación matemática y corporal existe entre el compás musical de $6/8$ y el zapateado de tarima?',
      '¿Cómo construimos instrumentos de percusión caseros (quijadas, cajones, panderos) con materiales locales?',
      '¿Por qué la música tradicional mexicana es considerada Patrimonio Cultural de la Humanidad?'
    ],
    inicioDetalle: 'Audición guiada de sones jarochos, huastecos y calentanos. Identificación de la tarima como instrumento.',
    desarrolloDetalle: 'Taller de Ritmo y Zapateado: Aprender el paso básico de tres tiempos, coordinar palmadas polirrítmicas y componer coplas colectivas sobre la historia escolar.',
    cierreDetalle: 'Fandango Escolar en el patio con tarima central y versada colectiva improvisada.',
    evaluacionCriterios: [
      'Coordinación rítmica y corporal en el zapateado y percusiones',
      'Composición lírica de versos tradicionales con métrica y rima',
      'Aprecio por el patrimonio inmaterial y participación en el fandango'
    ],
    materiales: 'Tarima de madera, jaranas o guitarras, percusiones menores, hojas de versos.',
    entregable: 'Montaje Coreográfico y Cancionero de Décimas "El Fandango de Nuestra Escuela".'
  },
  // Planeaciones 21 a 50 de Lenguajes
  {
    id: 'f6-len-21',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 21,
    temaTitulo: 'Textos de divulgación científica y pensamiento crítico',
    tituloProyecto: 'Jóvenes Divulgadores: Artículos Científicos Escolares y Combate a las Pseudociencias',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Identifica las características del texto de divulgación científica y elabora uno sobre un tema de interés, empleando lenguaje riguroso pero accesible, gráficas y citas bibliográficas.',
    detonadoras: ['¿Cómo traducir conceptos científicos complejos a un lenguaje claro para todo el público?', '¿Cómo desenmascarar noticias falsas y pseudociencias en redes sociales?'],
    inicioDetalle: 'Análisis de artículos de la revista ¿Cómo ves? de la UNAM. Estructura de la divulgación.',
    desarrolloDetalle: 'Taller de Redacción: Investigar sobre energías limpias o vacunas y redactar un artículo con recuadros, gráficas y glosario.',
    cierreDetalle: 'Publicación de la Revista Científica Escolar y presentación en feria de ciencias.',
    evaluacionCriterios: ['Rigor conceptual y claridad divulgativa', 'Uso adecuado de fuentes y citas', 'Diseño editorial con recursos gráficos'],
    materiales: 'Revistas científicas, computadoras, cartulinas.',
    entregable: 'Artículo de Divulgación Científica Ilustrado.'
  },
  {
    id: 'f6-len-22',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 22,
    temaTitulo: 'Mensajes publicitarios y vida saludable en medios masivos',
    tituloProyecto: 'Desarmando el Comercial: Análisis Semiótico de Anuncios y Campañas de Salud',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Elabora un mensaje impreso y audiovisual empleando recursos retóricos para favorecer una vida saludable, analizando críticamente estereotipos en comerciales masivos.',
    detonadoras: ['¿Qué trucos psicológicos usan los anuncios para vender productos nocivos?', '¿Cómo diseñar un cartel publicitario persuasivo en favor de la salud?'],
    inicioDetalle: 'Proyección de anuncios comerciales de refrescos y comida rápida. Desglose de eslóganes.',
    desarrolloDetalle: 'Taller de Publicidad Social: Diseñar una campaña con cartel y guion de video para promover el deporte y el consumo de agua.',
    cierreDetalle: 'Exposición de carteles en los pasillos de la secundaria y autoevaluación.',
    evaluacionCriterios: ['Análisis crítico de estrategias persuasivas', 'Creatividad visual y eslogan contundente', 'Mensaje propositivo de salud integral'],
    materiales: 'Cartulinas, pinturas, software de diseño o marcadores.',
    entregable: 'Campaña Publicitaria Social en Cartel y Guion de Spot.'
  },
  {
    id: 'f6-len-23',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 23,
    temaTitulo: 'Manifestaciones culturales y artísticas a favor de la inclusión',
    tituloProyecto: 'Letras sin Barreras: Literatura Inclusiva y Diversidad de Capacidades',
    ejes: ['Inclusión', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (3º Secundaria) - Crea un texto literario que aborde un tema que promueva una sociedad incluyente, reconociendo aportes estéticos de personas con discapacidad.',
    detonadoras: ['¿Cómo visibiliza la literatura la resiliencia y dignidad de personas con discapacidad?', '¿Cómo creamos personajes entrañables que desafíen los estereotipos?'],
    inicioDetalle: 'Lectura de poemas y relatos de autores con discapacidad visual y auditiva.',
    desarrolloDetalle: 'Creación de Cuentos Inclusivos: Escribir una historia donde el protagonista supere barreras del entorno mediante la empatía y adaptaciones comunitarias.',
    cierreDetalle: 'Audición de cuentos grabados para audiolibro escolar.',
    evaluacionCriterios: ['Sensibilidad y profundidad en la temática de inclusión', 'Estructura narrativa y estilo literario', 'Grabación oral para audiolibro accesible'],
    materiales: 'Grabadoras de audio, hojas de texto, ilustraciones.',
    entregable: 'Cuento Inclusivo en Texto y Audiolibro Grabado.'
  },
  {
    id: 'f6-len-24',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 24,
    temaTitulo: 'Recursos literarios en cartas personales y biografías',
    tituloProyecto: 'Cartas a través del Tiempo: Epistolario Histórico y Recursos Retóricos',
    ejes: ['Apropiación de las Culturas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Identifica recursos literarios en lengua española y los emplea en la elaboración de cartas personales y biografías de personajes comunitarios.',
    detonadoras: ['¿Cómo una carta escrita en un momento crucial de la historia revela la intimidad y valor de un personaje?', '¿Cómo usamos figuras retóricas en textos biográficos?'],
    inicioDetalle: 'Lectura de cartas históricas de Benito Juárez y Frida Kahlo.',
    desarrolloDetalle: 'Taller Epistolar Histórico: Escribir una carta ficticia en primera persona asumiendo la voz de un personaje histórico o un abuelo de la comunidad.',
    cierreDetalle: 'Lectura con ambientación musical en el aula.',
    evaluacionCriterios: ['Uso de figuras literarias (metáforas, hipérboles)', 'Rigor histórico en el contexto de la carta', 'Estilo epistolar auténtico y emotivo'],
    materiales: 'Papel envejecido con café, tinta, plumas.',
    entregable: 'Epistolario Histórico Manuscrito e Ilustrado.'
  },
  {
    id: 'f6-len-25',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 25,
    temaTitulo: 'Textos narrativos y análisis de personajes en la novela latinoamericana',
    tituloProyecto: 'Cien Años de Historias: El Realismo Mágico y el Universo de la Novela',
    ejes: ['Apropiación de las Culturas', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (2º Secundaria) - Analiza las características y recursos estéticos de los textos narrativos, e interpreta y disfruta de cuentos y novelas del boom latinoamericano.',
    detonadoras: ['¿Qué hace al Realismo Mágico latinoamericano un género tan fascinante?', '¿Cómo se construyen personajes complejos con arquetipos y motivaciones psicológicas?'],
    inicioDetalle: 'Lectura de fragmentos de Gabriel García Márquez y Julio Cortázar.',
    desarrolloDetalle: 'Análisis de Novela en Equipos: Mapa de personajes, cronotopo (tiempo y espacio) y figuras retóricas en un capítulo seleccionado.',
    cierreDetalle: 'Creación de un micro-relato de realismo mágico ambientado en la escuela.',
    evaluacionCriterios: ['Interpretación crítica de recursos de la novela', 'Análisis profundo de la psicología de personajes', 'Creación de micro-ficción con elementos fantásticos'],
    materiales: 'Novelas latinoamericanas, esquemas de análisis literario.',
    entregable: 'Ensayo Literario y Micro-Relato de Realismo Mágico.'
  },
  {
    id: 'f6-len-26',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 26,
    temaTitulo: 'Elaboración de ensayos críticos sobre géneros literarios',
    tituloProyecto: 'La Pluma Crítica: El Ensayo Argumentativo sobre Obras Clásicas',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (3º Secundaria) - Elabora un ensayo acerca del tratamiento de un tema de su elección en obras literarias, argumentando un juicio estético y ético con citas textuales APA.',
    detonadoras: ['¿Cómo defender una postura sobre una obra literaria mediante argumentos de autoridad y citas?', '¿Qué temas universales (amor, justicia, libertad) siguen vigentes en los clásicos?'],
    inicioDetalle: 'Estructura del ensayo académico: Tesis, argumentos, contraargumentos y conclusión.',
    desarrolloDetalle: 'Taller de Redacción de Ensayo: Escribir un ensayo de 3 cuartillas sobre la justicia en Don Quijote o El Llano en Llamas usando citas textuales.',
    cierreDetalle: 'Defensa oral de tesis en el Coloquio Literario de 3º de Secundaria.',
    evaluacionCriterios: ['Solidez y originalidad de la tesis', 'Uso riguroso de citas bibliográficas y argumentos', 'Coherencia discursiva y elegancia estilística'],
    materiales: 'Obras literarias clásicas, manual de citas APA, hojas de ensayo.',
    entregable: 'Ensayo Académico Crítico "Ecos de la Literatura Universal".'
  },
  {
    id: 'f6-len-27',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 27,
    temaTitulo: 'Entrevistas y relatos de sucesos significativos en inglés',
    tituloProyecto: 'My Community Heroes: Biographies and Oral Interviews in Simple Past',
    ejes: ['Interculturalidad Crítica', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Entrevista y narra en inglés sucesos significativos familiares y comunitarios recuperados de la memoria colectiva, usando verbos regulares e irregulares en pasado simple.',
    detonadoras: ['How do we formulate past questions using "Did you...?" in English?', 'Who is a local hero in your family or neighbourhood?'],
    inicioDetalle: 'Práctica de verbos irregulares comunes (went, had, saw, made, helped) con dinámicas de memoria.',
    desarrolloDetalle: 'Taller de Entrevista Oral: Diseñar un cuestionario de 6 preguntas en inglés sobre un acontecimiento relevante y redactar la biografía corta del entrevistado.',
    cierreDetalle: 'Presentación en parejas de la historia oral grabada.',
    evaluacionCriterios: ['Uso correcto del pasado simple en afirmativo e interrogativo', 'Fluidez y pronunciación en la interacción oral', 'Valoración testimonial del personaje comunitario'],
    materiales: 'Fichas de verbos en pasado, grabadoras de audio.',
    entregable: 'Biografía en Inglés "A Local Hero: Story of Resilience and Hope".'
  },
  {
    id: 'f6-len-28',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 28,
    temaTitulo: 'Mensajes en inglés para promover una vida saludable y el deporte',
    tituloProyecto: 'Fit & Healthy Teens: Podcasting and Health Brochures in English',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Investiga en fuentes en inglés sobre nutrición y deporte para construir un folleto informativo y un guion de podcast difundido en medios escolares.',
    detonadoras: ['What are the best habits for physical and mental health in teenage years?', 'How do we give healthy advice using imperatives and conditionals in English?'],
    inicioDetalle: 'Análisis de infografías de salud de la OMS y CDC en inglés.',
    desarrolloDetalle: 'Producción de Folleto y Podcast: Redactar una guía de nutrición juvenil con recomendaciones usando "If you exercise daily, you will feel..." y grabar un audio de 1 minuto.',
    cierreDetalle: 'Escucha de podcasts de salud en el aula y autoevaluación.',
    evaluacionCriterios: ['Uso del primer condicional y vocabulario de salud', 'Diseño gráfico claro en el folleto', 'Claridad vocal en la grabación del podcast'],
    materiales: 'Cartulinas, micrófonos para celular, plantillas de folletos.',
    entregable: 'Folleto Tríptico y Episodio de Podcast "Healthy Living Guide for Teens".'
  },
  {
    id: 'f6-len-29',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 29,
    temaTitulo: 'Debates en inglés sobre cambios lingüísticos y tecnología',
    tituloProyecto: 'The Future of Communication: AI, Language Evolution and Debates in English',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Participa en un debate en inglés sobre los cambios lingüísticos y culturales derivados de la tecnología y la inteligencia artificial, argumentando posturas éticas.',
    detonadoras: ['Is artificial intelligence changing how we learn and write languages?', 'How do we express agreement and polite disagreement in a formal English debate?'],
    inicioDetalle: 'Video de debate internacional sobre tecnología y lenguaje. Fórmulas de cortesía en inglés.',
    desarrolloDetalle: 'Estructuración de Argumentos: En equipos, preparar argumentos a favor y en contra del uso de traductores automáticos y redactar ensayos de postura en inglés.',
    cierreDetalle: 'Debate parlamentario en inglés con moderador estudiantil.',
    evaluacionCriterios: ['Uso de conectores de contraste y adición (Furthermore, However, On the other hand)', 'Elocuencia y capacidad de refutación en inglés', 'Pensamiento crítico sobre el impacto tecnológico'],
    materiales: 'Tarjetas de debate, cronómetro, hojas de argumentos.',
    entregable: 'Ensayo de Postura y Récord del Debate "AI and the Evolution of Language".'
  },
  {
    id: 'f6-len-30',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 30,
    temaTitulo: 'Sistemas alternativos de comunicación en inglés para sociedades incluyentes',
    tituloProyecto: 'Universal Signs: Sign Language and Assistive Technology in English',
    ejes: ['Inclusión', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (3º Secundaria) - Crea en inglés alguna manifestación artística o proyecto digital que aborde cómo los sistemas alternativos de comunicación favorecen la inclusión social universal.',
    detonadoras: ['How do American Sign Language (ASL) and assistive tech empower people with disabilities?', 'How can we design an accessible English learning app interface?'],
    inicioDetalle: 'Demostración de señas básicas en ASL (American Sign Language) y subtítulos inclusivos.',
    desarrolloDetalle: 'Diseño de un Prototipo Digital Inclusivo: Diseñar en cartulina la interfaz de una app en inglés con botones accesibles, descripción de audio y pictogramas universales.',
    cierreDetalle: 'Presentación del prototipo en inglés ante el grupo.',
    evaluacionCriterios: ['Vocabulario técnico de inclusión y accesibilidad en inglés', 'Creatividad funcional en el diseño del prototipo', 'Empatía y compromiso con la accesibilidad universal'],
    materiales: 'Plantillas de diseño de interfaces móviles, colores, tarjetas de vocabulario.',
    entregable: 'Prototipo de Aplicación Inclusiva "Accessible English for Everyone".'
  },
  {
    id: 'f6-len-31',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 31,
    temaTitulo: 'Manifestaciones artísticas de pueblos afrodescendientes e indígenas',
    tituloProyecto: 'La Tercera Raíz en el Arte: Máscaras, Tambores y Tradición Afromexicana',
    ejes: ['Interculturalidad Crítica', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (1º Secundaria) - Identifica manifestaciones artísticas de pueblos afrodescendientes e indígenas de México (Danza de los Diablos de la Costa Chica), interpretando significados comunitarios.',
    detonadoras: ['¿Cómo se expresa la herencia africana en la música de artesa y las danzas tradicionales de México?', '¿Qué simbolizan las máscaras de madera y crines de caballo?'],
    inicioDetalle: 'Visualización de la Danza de los Diablos de Guerrero y Oaxaca. Ritmo de charrasca y bote.',
    desarrolloDetalle: 'Taller de Elaboración de Máscaras Tradicionales: Modelar con cartonería una máscara representativa de la cultura afromexicana explicando su simbolismo de libertad.',
    cierreDetalle: 'Danza colectiva con percusiones en el patio escolar.',
    evaluacionCriterios: ['Técnica de cartonería y modelado de máscara', 'Comprensión histórica de la herencia afromexicana', 'Expresión corporal al ritmo tradicional'],
    materiales: 'Papel periódico, engrudo, pinturas acrílicas, pinceles, estambre.',
    entregable: 'Máscara Tradicional en Cartonería y Ficha Etnográfica "La Tercera Raíz".'
  },
  {
    id: 'f6-len-32',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 32,
    temaTitulo: 'Creaciones artísticas que tienen su origen en textos literarios',
    tituloProyecto: 'De la Página al Lienzo: Ilustración Editorial y Grabado de Cuentos Clásicos',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Adapta textos literarios experimentando con grabado, linóleo o esténcil, aplicando ritmo, contraste y variación visual para sensibilizar a la comunidad.',
    detonadoras: ['¿Cómo el grabador José Guadalupe Posada inmortalizó la literatura de cordel y las calaveras?', '¿Cómo se traslada una escena literaria a un grabado en alto relieve?'],
    inicioDetalle: 'Muestra de grabados de Posada y Leopoldo Méndez en el Taller de Gráfica Popular.',
    desarrolloDetalle: 'Taller de Grabado en Foami/Linóleo: Tallar una ilustración basada en un cuento tradicional y estampar una serie numerada con tinta china sobre papel fabriano.',
    cierreDetalle: 'Montaje de la Galería de Estampa y Grabado Literario en el aula.',
    evaluacionCriterios: ['Destreza en el tallado y entintado de la matriz', 'Composición visual y fidelidad expresiva con el texto literario', 'Cuidado y limpieza en la estampación de la serie'],
    materiales: 'Placas de foami grueso o linóleo, gubias escolares, rodillos, tinta china, papel.',
    entregable: 'Serie de 3 Grabados Estampados e Ilustración de Cuento Clásico.'
  },
  {
    id: 'f6-len-33',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 33,
    temaTitulo: 'Procesos creativos dialógicos para erradicar la violencia',
    tituloProyecto: 'Teatro Foro: Augusto Boal y la Transformación Escénica de Conflictos',
    ejes: ['Inclusión', 'Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Presenta al público una propuesta escénica de Teatro Foro que sensibilice sobre la erradicación de la violencia escolar, donde el público intervenga como "espect-actores".',
    detonadoras: ['¿Qué es el Teatro del Oprimido de Augusto Boal y cómo empodera a los espectadores para cambiar el final de una obra?', '¿Cómo detener una escena injusta para proponer una solución pacífica en vivo?'],
    inicioDetalle: 'Dinámica de estatuas corporales de opresión vs estatuas de liberación y solidaridad.',
    desarrolloDetalle: 'Montaje de Escena de Teatro Foro: Representar un dilema de acoso escolar que termina mal y abrir el foro para que los compañeros del público suban a actuar soluciones pacíficas alternativas.',
    cierreDetalle: 'Debate dialógico con el público sobre los aprendizajes vivenciales.',
    evaluacionCriterios: ['Estructura dramática abierta para la intervención del público', 'Capacidad de improvisación y facilitación dialógica', 'Impacto transformador y reflexivo en la comunidad escolar'],
    materiales: 'Espacio escénico despejado, sillas, letrero de "Stop", libreto guía.',
    entregable: 'Puesta en Escena de Teatro Foro y Bitácora de Soluciones Colectivas.'
  },
  {
    id: 'f6-len-34',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 34,
    temaTitulo: 'Reglamentos escolares y normas de convivencia democrática',
    tituloProyecto: 'Leyes del Salón: Verbos Modales, Derechos y Obligaciones Democráticas',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Participa en la redacción colectiva de un reglamento escolar, analizando la función de verbos en imperativo, futuro e infinitivo para garantizar derechos y obligaciones.',
    detonadoras: ['¿Por qué un reglamento debe redactarse en positivo y proteger los derechos de todos?', '¿Cómo cambia el sentido normativo entre "Se prohíbe" vs "Los alumnos tienen derecho a"?'],
    inicioDetalle: 'Análisis comparativo de reglamentos de tránsito, deportivos y escolares.',
    desarrolloDetalle: 'Taller Legislativo del Aula: En comisiones, redactar los 5 capítulos del reglamento (Derechos, Obligaciones, Uso de Espacios, Convivencia y Sanciones Formativas) usando numerales y modos verbales.',
    cierreDetalle: 'Promulgación formal del Reglamento del Salón con firmas de todos.',
    evaluacionCriterios: ['Uso correcto de modos verbales normativos (infinitivo, futuro de mandato)', 'Estructura organizada en capítulos, artículos e incisos', 'Enfoque de derechos humanos y justicia restaurativa'],
    materiales: 'Pliegos de papel bond, marcadores, formatos legales didácticos.',
    entregable: 'Reglamento Escolar Democrático y Guía de Convivencia Restaurativa.'
  },
  {
    id: 'f6-len-35',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 35,
    temaTitulo: 'Análisis de textos dramáticos y escenificación',
    tituloProyecto: 'El Escenario de los Sueños: Análisis de Tragedia y Comedia Clásica',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Analiza las características y recursos estéticos de textos dramáticos (tragedia, comedia, drama) e interpreta obras de teatro clásico y contemporáneo.',
    detonadoras: ['¿Qué distingue a la catarsis de una tragedia griega de la risa reflexiva de una comedia de Molière?', '¿Cómo interpretamos el tono y subtexto en un parlamento dramático?'],
    inicioDetalle: 'Lectura coral de una escena de Antígona o Romeo y Julieta.',
    desarrolloDetalle: 'Taller de Dirección Teatral: Diseñar la planta escénica, vestuario y partitura de movimientos de personajes para una escena clásica adaptada al contexto actual.',
    cierreDetalle: 'Puesta en escena de 3 minutos por equipo con retroalimentación entre pares.',
    evaluacionCriterios: ['Comprensión de los géneros dramáticos clásicos', 'Propuesta de dirección escénica y escenografía coherente', 'Expresión actoral, dicción y proyección de voz'],
    materiales: 'Textos teatrales clásicos, elementos de vestuario y utilería.',
    entregable: 'Carpeta de Dirección Escénica y Representación Teatral Adaptada.'
  },
  {
    id: 'f6-len-36',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 36,
    temaTitulo: 'Elaboración de informes de experimentos científicos en español',
    tituloProyecto: 'El Cuaderno del Científico: Informes de Laboratorio con Diagramas y Conclusiones',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Elabora informes de experimentos científicos con estructura rigurosa (objetivo, hipótesis, metodología, registro de resultados, análisis y conclusiones), empleando voz pasiva y lenguaje formal.',
    detonadoras: ['¿Por qué en los reportes científicos se utiliza la voz pasiva ("se colocó la muestra...") en lugar de la primera persona?', '¿Cómo se grafican e interpretan datos experimentales en un informe formal?'],
    inicioDetalle: 'Revisión de informes científicos de laboratorios universitarios.',
    desarrolloDetalle: 'Redacción del Informe Experimental: Realizar una práctica sencilla de física o química y documentar paso a paso el protocolo con diagramas, tablas de datos y conclusiones fundamentadas.',
    cierreDetalle: 'Coevaluación del informe con rúbrica de publicaciones académicas.',
    evaluacionCriterios: ['Estructura metodológica completa del informe de laboratorio', 'Uso normativo de lenguaje técnico y voz impersonal/pasiva', 'Precisión en el análisis de datos y comprobación de hipótesis'],
    materiales: 'Formatos de reporte científico, hojas cuadriculadas, reglas.',
    entregable: 'Informe Técnico de Laboratorio Científico con Gráficas y Conclusiones.'
  },
  {
    id: 'f6-len-37',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 37,
    temaTitulo: 'Instrucciones y recetas de cocina internacional en inglés',
    tituloProyecto: 'MasterChef Junior: International Recipes, Ingredients and Sequence Adverbs',
    ejes: ['Vida Saludable', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (1º Secundaria) - Redacta e interpreta instructivos y recetas culinarias tradicionales en inglés, empleando vocabulario de medidas, ingredientes, verbos de acción y adverbios de secuencia.',
    detonadoras: ['How do we write a clear cooking recipe using sequence words (First, Then, After that, Finally)?', 'What typical Mexican dish would you love to explain in English to a foreign tourist?'],
    inicioDetalle: 'Cooking vocabulary flashcard challenge (chop, mix, boil, bake, slice, fry).',
    desarrolloDetalle: 'Cookbook Design Workshop: In pairs, write the illustrated recipe of a healthy traditional dish in English specifying ingredients, quantities, and numbered step-by-step instructions.',
    cierreDetalle: 'Cooking Show Roleplay: Demonstrating the recipe steps orally in English.',
    evaluacionCriterios: ['Accurate use of imperative verbs and sequence connectors in English', 'Correct vocabulary for ingredients, kitchen tools, and quantities', 'Creativity and visual presentation of the international recipe card'],
    materiales: 'Recipe card templates, culinary pictures, colored markers.',
    entregable: 'Illustrated Recipe Card for the "International Healthy Cookbook in English".'
  },
  {
    id: 'f6-len-38',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 38,
    temaTitulo: 'Redacción de reseñas de películas y libros en inglés',
    tituloProyecto: 'Movie & Book Critics: Film Reviews, Plot Summaries and Ratings in English',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Elabora reseñas críticas en inglés sobre libros, películas o series, describiendo la trama (plot), actuaciones, cinematografía y recomendación fundamentada.',
    detonadoras: ['What makes a movie review helpful for viewers?', 'How do we use opinion adjectives (breathtaking, thrilling, dull, overrated) to review a film in English?'],
    inicioDetalle: 'Analyzing film reviews from Rotten Tomatoes and IMDb in English.',
    desarrolloDetalle: 'Film Critic Workshop: Write a 200-word review of an inspiring film or documentary with Star Rating, Plot summary (without spoilers), Pros & Cons, and personal verdict.',
    cierreDetalle: 'Movie Critics Podcast: Presenting your 1-minute oral review in English.',
    evaluacionCriterios: ['Structured review format with persuasive opinion vocabulary', 'Correct grammar and transition phrases (In my opinion, I strongly recommend)', 'Engaging delivery and clear pronunciation during the oral presentation'],
    materiales: 'Film posters, review layout templates, highlighter pens.',
    entregable: 'Published Film Review Sheet with Star Rating and Spoken Audio Pitch.'
  },
  {
    id: 'f6-len-39',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 39,
    temaTitulo: 'Entrevistas de trabajo simuladas y currículum vitae en inglés',
    tituloProyecto: 'Job Hunting for the Future: Professional Resume & Mock Interviews in English',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Diseña un currículum vitae profesional en inglés y participa en entrevistas de trabajo simuladas destacando habilidades, logros académicos y aspiraciones vocacionales.',
    detonadoras: ['How do we describe our strengths, soft skills, and experiences professionally in English?', 'How do we handle challenging job interview questions ("Tell me about yourself") with confidence?'],
    inicioDetalle: 'Analyzing professional resumes (CV) and elevator pitches in English.',
    desarrolloDetalle: 'Job Fair Simulation Workshop: Draft your student CV in English highlighting skills (teamwork, leadership, digital tools) and conduct a 3-minute mock job interview in pairs.',
    cierreDetalle: 'Recruiter feedback and self-reflection on career readiness in English.',
    evaluacionCriterios: ['Professional layout and vocabulary in the English Resume (CV)', 'Confident verbal communication and body language in the mock interview', 'Accurate usage of present perfect and modal verbs for skills'],
    materiales: 'CV templates, mock job position listings, interview rubric.',
    entregable: 'Professional English Resume (CV) and Mock Job Interview Performance Record.'
  },
  {
    id: 'f6-len-40',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 40,
    temaTitulo: 'Patrimonio arquitectónico e identidad comunitaria en artes visuales',
    tituloProyecto: 'Monumentos Vivos: Dibujo Arquitectónico, Perspectiva y Patrimonio Local',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (1º Secundaria) - Interpreta manifestaciones del patrimonio arquitectónico e histórico de su comunidad mediante el dibujo en perspectiva de 1 y 2 puntos de fuga, fomentando su conservación.',
    detonadoras: ['¿Cómo cuentan los edificios antiguos, templos y quioscos la historia de nuestra ciudad?', '¿Cómo aplicamos la perspectiva cónica para dar profundidad tridimensional a un dibujo?'],
    inicioDetalle: 'Demostración de trazo de horizonte y puntos de fuga en el pizarrón.',
    desarrolloDetalle: 'Taller de Dibujo Arquitectónico: Dibujar un edificio histórico local aplicando perspectiva a 2 puntos de fuga y técnica de claroscuro con grafito o tinta.',
    cierreDetalle: 'Exposición "Rutas del Patrimonio Arquitectónico" en la biblioteca escolar.',
    evaluacionCriterios: ['Aplicación técnica correcta de la perspectiva y proporción arquitectónica', 'Manejo del claroscuro, textura y valor tonal', 'Investigación histórica del valor patrimonial del inmueble'],
    materiales: 'Hojas marquilla, reglas T, escuadras, lápices de grafito (2B, 4B, 6B).',
    entregable: 'Lámina de Dibujo en Perspectiva del Patrimonio Arquitectónico Comunitario.'
  },
  {
    id: 'f6-len-41',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 41,
    temaTitulo: 'Diseño de escenografía y vestuario teatral',
    tituloProyecto: 'El Taller del Escenógrafo: Maquetas Teatrales, Iluminación y Vestuario',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Diseña maquetas escenográficas y figurines de vestuario para una obra dramática, integrando conceptos de composición espacial, psicología del color e iluminación.',
    detonadoras: ['¿Cómo la escenografía y la luz ambiental transforman el estado emocional de una obra?', '¿Cómo elegimos telas y colores en el vestuario para reflejar el carácter de un personaje?'],
    inicioDetalle: 'Proyección de maquetas escenográficas de óperas y teatro contemporáneo.',
    desarrolloDetalle: 'Taller de Maquetas Escenográficas: En equipos de 4, construir en una caja de zapatos la maqueta a escala de un escenario teatral con decorados, telones y figurines de vestuario.',
    cierreDetalle: 'Exhibición de maquetas con iluminación mediante lámparas LED miniatura.',
    evaluacionCriterios: ['Diseño a escala y coherencia temática con la obra elegida', 'Uso expresivo del color, texturas e iluminación escénica', 'Detalle y creatividad en los figurines de vestuario'],
    materiales: 'Cajas de cartón, cartulina batería, telas, pinturas acrílicas, luces LED.',
    entregable: 'Maqueta Escenográfica Teatral Tridimensional y Cuaderno de Figurines de Vestuario.'
  },
  {
    id: 'f6-len-42',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 42,
    temaTitulo: 'Fotografía documental y fotorreportaje social',
    tituloProyecto: 'El Lente Social: Fotoperiodismo, Encuadres y Fotorreportaje Comunitario',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Construye una narrativa visual mediante un fotorreportaje de 6 imágenes con pie de foto crítico sobre un oficio tradicional o problemática comunitaria.',
    detonadoras: ['¿Cómo una fotografía documental cuenta una historia sin palabras?', '¿Qué planos fotográficos (general, medio, primer plano, detalle) aportan mayor dramatismo?'],
    inicioDetalle: 'Análisis de fotografías de Manuel Álvarez Bravo, Nacho López y Graciela Iturbide.',
    desarrolloDetalle: 'Taller de Fotoperiodismo: Capturar una serie de 6 fotografías que documenten la jornada de un artesano o comerciante local, cuidando la regla de los tercios y la luz natural.',
    cierreDetalle: 'Montaje de la exposición fotográfica con pies de foto periodísticos.',
    evaluacionCriterios: ['Calidad estética, encuadre y dominio técnico fotográfico', 'Secuencia narrativa coherente en la serie documental', 'Sensibilidad ética y respeto a la dignidad del sujeto fotografiado'],
    materiales: 'Cámaras o celulares, impresiones fotográficas, paspartú negro.',
    entregable: 'Fotorreportaje Impreso de 6 Fotografías con Memoria Narrativa.'
  },
  {
    id: 'f6-len-43',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 43,
    temaTitulo: 'Comprensión y producción de textos discontinuos (mapas conceptuales e infografías)',
    tituloProyecto: 'El Mapa de las Ideas: Organizadores Gráficos y Síntesis Visual del Saber',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (1º Secundaria) - Diseña mapas conceptuales, cuadros sinópticos e infografías para organizar y sintetizar información compleja de temas científicos e históricos.',
    detonadoras: ['¿Cómo jerarquizamos ideas con conceptos clave y palabras de enlace en un mapa de Novak?', '¿Por qué el cerebro humano procesa imágenes e iconos más rápido que textos planos?'],
    inicioDetalle: 'Comparación de un texto continuo de 3 páginas vs un mapa conceptual estructurado.',
    desarrolloDetalle: 'Taller de Mapeo Conceptual: Leer un texto de biología, extraer los conceptos principales y construir un mapa conceptual jerárquico con conectores precisos.',
    cierreDetalle: 'Exposición y coevaluación con lista de verificación lógica.',
    evaluacionCriterios: ['Jerarquía visual y pertinencia de los conceptos seleccionados', 'Uso correcto de conectores y proposiciones lógicas', 'Claridad, limpieza y diseño gráfico'],
    materiales: 'Hojas blancas, reglas, plumones, software de mapas conceptuales.',
    entregable: 'Mapa Conceptual Jerárquico Ilustrado de Alta Complejidad.'
  },
  {
    id: 'f6-len-44',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 44,
    temaTitulo: 'Entrevistas a especialistas para investigar temas de ciencias y sociedad',
    tituloProyecto: 'Encuentro con la Ciencia: Protocolo de Entrevista y Edición Testimonial',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (2º Secundaria) - Planifica y realiza entrevistas a especialistas sobre temas de salud, ciencia y sociedad, elaborando un reporte con citas directas e indirectas y signos de puntuación.',
    detonadoras: ['¿Cómo redactamos preguntas de profundidad científica sin ser redundantes?', '¿Cómo citamos fielmente las palabras de un experto usando comillas y paráfrasis?'],
    inicioDetalle: 'Análisis de una entrevista periodística televisiva con un científico.',
    desarrolloDetalle: 'Planificación y Ejecución de Entrevista: Invitar o contactar a un profesional de la salud o medio ambiente, realizar la entrevista y transcribir el reporte en formato pregunta-respuesta.',
    cierreDetalle: 'Publicación del reporte en la gaceta escolar.',
    evaluacionCriterios: ['Pertinencia y profundidad de las preguntas formuladas', 'Uso riguroso de citas textuales y discurso indirecto', 'Redacción formal y ortografía impecable'],
    materiales: 'Grabadoras de voz, formatos de guion, procesador de textos.',
    entregable: 'Reporte Formal de Entrevista con Especialista para la Gaceta Escolar.'
  },
  {
    id: 'f6-len-45',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Español',
    materiaFolder: 'Espanol',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 45,
    temaTitulo: 'Elaboración de antologías poéticas temáticas con prólogo crítico',
    tituloProyecto: 'El Canto de los Siglos: Antología Poética Temática y Prólogo de Autor',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (3º Secundaria) - Compila una antología poética sobre un tema específico (la paz, la naturaleza, el amor, la libertad), redactando un prólogo analítico y notas bio-bibliográficas.',
    detonadoras: ['¿Cuál es la función del prólogo en un libro recopilatorio?', '¿Qué criterios de selección y orden seguimos para estructurar una antología poética?'],
    inicioDetalle: 'Lectura de prólogos célebres de Jorge Luis Borges y Octavio Paz.',
    desarrolloDetalle: 'Taller Editorial de Antología: Seleccionar 10 poemas de autores hispanoamericanos, redactar el prólogo crítico que justifique la selección y diseñar la portada y maqueta del libro.',
    cierreDetalle: 'Presentación formal de antologías en el festival de lectura escolar.',
    evaluacionCriterios: ['Calidad crítica y argumentativa en la redacción del prólogo', 'Criterio selectivo coherente y notas biográficas de los autores', 'Cuidado editorial en el encuadernado y diseño de portada'],
    materiales: 'Hojas opalina, cartoncillo para encuadernación, cordel, pegamento.',
    entregable: 'Antología Poética Encuadernada a Mano con Prólogo Crítico.'
  },
  {
    id: 'f6-len-46',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 46,
    temaTitulo: 'Descripción de rutinas diarias y estilos de vida en inglés',
    tituloProyecto: 'Daily Life Around the Globe: Present Simple, Routines and Adverbs of Frequency',
    ejes: ['Vida Saludable', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (1º Secundaria) - Describe rutinas diarias, hábitos saludables y actividades escolares en inglés, usando presente simple, tercera persona (-s/-es) y adverbios de frecuencia (always, usually, never).',
    detonadoras: ['How do teenage daily routines differ between Mexico, Japan, and Canada?', 'How do we ask "What time do you usually wake up?" in English?'],
    inicioDetalle: 'Daily routines mime game and phonetic review of third-person singular verbs.',
    desarrolloDetalle: 'Daily Routine Vlog Script: Write and record a 1-minute video script in English describing a balanced healthy day in the life of a secondary student using adverbs of frequency.',
    cierreDetalle: 'Peer evaluation of the daily routine vlogs.',
    evaluacionCriterios: ['Correct conjugation of verbs in Present Simple (3rd person singular)', 'Appropriate placement of adverbs of frequency in sentences', 'Fluency and pronunciation in the video presentation'],
    materiales: 'Video recording device, routine flashcards, daily schedule planners.',
    entregable: 'Video Script and Daily Routine Planner in English.'
  },
  {
    id: 'f6-len-47',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Inglés',
    materiaFolder: 'Ingles',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 47,
    temaTitulo: 'Narración de planes futuros y proyectos sustentables en inglés',
    tituloProyecto: 'Future Cities 2050: Future Tenses (Will, Going to) and Green Innovations',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Expresa planes, predicciones y proyectos ecológicos futuros en inglés utilizando "will" para predicciones y "be going to" para planes estructurados.',
    detonadoras: ['How will cities look in 2050 regarding clean energy and transport?', 'What are you going to do this year to help the environment?'],
    inicioDetalle: 'Future predictions brainstorming using "In 2050, robots will..." and "I am going to...".',
    desarrolloDetalle: 'Green City Blueprint Workshop: In teams of 3, design a blueprint of a sustainable future city and write a 150-word proposal in English explaining upcoming green technologies.',
    cierreDetalle: 'Poster session with oral pitches in English.',
    evaluacionCriterios: ['Accurate distinction between "will" (predictions) and "going to" (plans)', 'Rich environmental vocabulary in English', 'Persuasive presentation and visual blueprint design'],
    materiales: 'Blueprint paper, green markers, future vocabulary charts.',
    entregable: 'Illustrated Green City Blueprint and Future Proposal in English.'
  },
  {
    id: 'f6-len-48',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 48,
    temaTitulo: 'Paisaje sonoro y creación de instrumentos musicales con materiales reciclados',
    tituloProyecto: 'La Orquesta del Reciclaje: Paisajes Sonoros, Cotidiáfonos y Polirritmia',
    ejes: ['Artes y Experiencias Estéticas', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Registra y analiza el paisaje sonoro de su entorno escolar y construye cotidiáfonos (instrumentos musicales con material reciclado) para interpretar ensambles rítmicos.',
    detonadoras: ['¿Qué sonidos identifican a nuestra escuela y comunidad (pájaros, campanas, tráfico)?', '¿Cómo convertimos tubos de PVC, botellas y latas en instrumentos afinados?'],
    inicioDetalle: 'Paseo de Escucha Atenta: Grabar y mapear los sonidos del patio escolar (paisaje sonoro).',
    desarrolloDetalle: 'Taller de Lutería Casera: Fabricar maracas con latas, flautas de PVC y tambores con cubetas. Ensayar un ensamble polirrítmico colectivo.',
    cierreDetalle: 'Concierto de la Orquesta del Reciclaje en el patio escolar.',
    evaluacionCriterios: ['Construcción funcional y afinación de los cotidiáfonos', 'Coordinación rítmica y seguimiento de partituras no convencionales', 'Sensibilidad y aprecio del paisaje sonoro ambiental'],
    materiales: 'Botellas, latas, tubos de PVC, semillas, ligas, globos.',
    entregable: 'Cotidiáfono Musical Construido y Partitura Gráfica de Ensamble Rítmico.'
  },
  {
    id: 'f6-len-49',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 49,
    temaTitulo: 'El performance y el arte de acción como intervención social',
    tituloProyecto: 'Cuerpos en Resistencia: El Performance Artístico como Mensaje Social',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Diseña y ejecuta un performance artístico o acción colectiva que utilice el cuerpo, el espacio y el silencio para sensibilizar sobre problemáticas de paz y ecología.',
    detonadoras: ['¿Cómo se diferencia un performance de una obra de teatro tradicional?', '¿Qué impacto genera una acción artística inesperada en el espacio público?'],
    inicioDetalle: 'Análisis de performances históricos de Marina Abramović y Yoko Ono.',
    desarrolloDetalle: 'Laboratorio de Arte de Acción: Diseñar el guion conceptual de un performance de 3 minutos sobre la deforestación o el consumismo, coordinando acciones simbólicas y vestuario.',
    cierreDetalle: 'Presentación del performance en el patio y círculo de diálogo con los espectadores.',
    evaluacionCriterios: ['Fuerza conceptual y mensaje crítico del performance', 'Uso intencional y expresivo del cuerpo, tiempo y espacio', 'Capacidad de conmover y dialogar con el público escolar'],
    materiales: 'Telas, letreros mudos, cronómetro, espacio abierto.',
    entregable: 'Guion Conceptual de Performance y Registro Fotográfico de la Intervención.'
  },
  {
    id: 'f6-len-50',
    campo: 'Lenguajes',
    campoTag: 'lenguajes',
    materia: 'Artes',
    materiaFolder: 'Artes',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 50,
    temaTitulo: 'Curaduría y montaje de exposiciones de artes visuales',
    tituloProyecto: 'El Ojo del Curador: Montaje, Museografía y Cédulas de una Exposición Escolar',
    ejes: ['Artes y Experiencias Estéticas', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Diseña y monta una exposición artística colectiva en la escuela, aplicando principios museográficos (recorrido, iluminación, alturas de montaje, cédulas y catálogo razonado).',
    detonadoras: ['¿Qué labor realiza un curador de arte para que una exposición cuente una historia coherente?', '¿Cómo se redacta una cédula de sala y de obra con datos técnicos y ficha analítica?'],
    inicioDetalle: 'Recorrido virtual por el Museo Nacional de Arte (MUNAL) observando la museografía.',
    desarrolloDetalle: 'Comité Curatorial: Seleccionar 20 obras de los alumnos, diseñar el plano de distribución en la galería escolar, redactar las cédulas de sala y montar las obras a la altura estándar (1.50 m).',
    cierreDetalle: 'Inauguración formal de la Exposición Anual de Artes con visita guiada para padres y alumnos.',
    evaluacionCriterios: ['Aplicación rigurosa de principios museográficos y de conservación', 'Redacción académica de textos de sala y cédulas de obra', 'Trabajo colaborativo en la gestión y difusión cultural'],
    materiales: 'Nivel de gota, cinta métrica, clavillos, paspartú, catálogo impreso.',
    entregable: 'Catálogo de Exposición Artística Escolar y Montaje Museográfico Concluido.'
  }
];

