import { NodeMetadataF6 } from './fase6_data_lenguajes';

// 50 planeaciones únicas para ÉTICA, NATURALEZA Y SOCIEDADES en Secundaria (Fase 6)
export const eticaF6Data: NodeMetadataF6[] = [
  // --- GEOGRAFÍA 1º (15 planeaciones) ---
  {
    id: 'f6-eti-01',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 101,
    temaTitulo: 'El espacio geográfico como una construcción social y patrimonio biocultural',
    tituloProyecto: 'Territorios Vivos: El Espacio Geográfico y el Patrimonio Biocultural de México',
    ejes: ['Interculturalidad Crítica', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Comprende que el espacio geográfico se conforma de interrelaciones sociedad-naturaleza y reconoce que el patrimonio biocultural es resultado de la cosmovisión, economía y biodiversidad en el tiempo.',
    detonadoras: [
      '¿Por qué el espacio geográfico no es solo un mapa físico inanimado sino el resultado vivo de las relaciones humanas y la naturaleza?',
      '¿Qué es el patrimonio biocultural y cómo lo custodian los pueblos indígenas y campesinos?',
      '¿Cómo ha transformado la urbanización acelerada el paisaje natural de nuestra región?'
    ],
    inicioDetalle: 'Comparación de fotografías aéreas históricas de la localidad con imágenes satelitales actuales de Google Earth.',
    desarrolloDetalle: 'Taller de Cartografía Biocultural: Mapear en capas transparentes componentes físicos (ríos, montañas), biológicos (flora, fauna) y sociales (comunidades, cultivos, sitios sagrados).',
    cierreDetalle: 'Exposición de mapas bioculturales y redacción de compromisos de custodia territorial.',
    evaluacionCriterios: [
      'Identificación de los 5 componentes del espacio geográfico (natural, social, cultural, económico y político)',
      'Valoración del patrimonio biocultural y saberes locales',
      'Elaboración cartográfica con simbología y coordenadas'
    ],
    materiales: 'Imágenes satelitales impresas, acetatos, plumones indelebles, mapas base.',
    entregable: 'Mapa Multicapa del Patrimonio Biocultural Local con Memoria Geográfica.'
  },
  {
    id: 'f6-eti-02',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 102,
    temaTitulo: 'Las categorías de análisis espacial: lugar, medio, paisaje, región y territorio',
    tituloProyecto: 'Las Cinco Escalas del Saber Geográfico: Lugar, Medio, Paisaje, Región y Territorio',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Comprende las categorías de análisis espacial (lugar, medio, paisaje, región y territorio) para explicar las dinámicas socioambientales de su entorno.',
    detonadoras: [
      '¿Qué distingue al "Lugar" (espacio con apego afectivo) del "Territorio" (espacio delimitado con poder y soberanía)?',
      '¿Cómo define el "Paisaje" lo que percibimos visual y sensorialmente de un ecosistema?',
      '¿Qué características definen a una "Región" geográfica homogénea?'
    ],
    inicioDetalle: 'Recorrido por la colonia identificando vivencias en esquinas, parques y mercados (el sentido de lugar).',
    desarrolloDetalle: 'Matriz Comparativa de Análisis Espacial: Analizar un caso de estudio (la Cuenca del Valle de México o la Selva Lacandona) a través de las 5 categorías espaciales con evidencias fotográficas.',
    cierreDetalle: 'Debate grupal sobre la defensa del territorio frente a proyectos extractivos.',
    evaluacionCriterios: [
      'Diferenciación conceptual precisa de las 5 categorías de análisis espacial',
      'Aplicación de conceptos de localización, distribución y temporalidad',
      'Argumentación crítica sobre soberanía territorial y sentido de pertenencia'
    ],
    materiales: 'Fotografías del entorno, cartulinas, fichas de análisis conceptual.',
    entregable: 'Matriz Ilustrada y Álbum Fotográfico de las 5 Categorías de Análisis Espacial.'
  },
  {
    id: 'f6-eti-03',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 103,
    temaTitulo: 'La distribución y dinámica de las aguas continentales y oceánicas',
    tituloProyecto: 'El Latido Azul: Cuencas Hidrográficas, Ríos, Acuíferos y Conciencia Marítima',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Analiza la distribución de aguas continentales en México (principales ríos, lagos, acuíferos subterráneos) y valora la Zona Económica Exclusiva y litorales marítimos.',
    detonadoras: [
      '¿Por qué una cuenca hidrográfica es el sistema natural más importante para la vida y la economía?',
      '¿Qué retos enfrenta México con la sobreexplotación del 70% de sus acuíferos subterráneos?',
      '¿Por qué México es un país bioceánico y qué riquezas albergan sus 11,000 km de costas?'
    ],
    inicioDetalle: 'Construcción de una maqueta de relieve con plastilina rociando agua para observar el nacimiento de cuencas.',
    desarrolloDetalle: 'Taller de Cartografía Hidrológica: Mapear las vertientes del Pacífico, Golfo y Caribe en México, identificando presas hidroeléctricas, zonas de estrés hídrico y calcular el balance hídrico local.',
    cierreDetalle: 'Firma del Manifiesto Escolar por la Defensa del Agua y el Saneamiento de Ríos.',
    evaluacionCriterios: [
      'Identificación y trazo de las principales cuencas y acuíferos de México',
      'Comprensión del valor geopolítico del mar territorial y la ZEE',
      'Propuestas viables de gestión comunitaria sustentable del agua'
    ],
    materiales: 'Mapas hidrológicos del INEGI, plastilina, bandejas plásticas, agua con colorante.',
    entregable: 'Atlas Hidrológico Escolar de México y Diagnóstico Comunitario de Cuencas.'
  },
  {
    id: 'f6-eti-04',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 104,
    temaTitulo: 'Placas tectónicas, sismicidad y vulcanismo en el Cinturón de Fuego',
    tituloProyecto: 'Tierra en Movimiento: Tectónica de Placas, Vulcanismo y Cultura Sísmica en México',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Argumenta la relación entre la dinámica de las placas tectónicas (convergencia, divergencia y transformación) con el Cinturón de Fuego del Pacífico, fallas geológicas y sismicidad en México.',
    detonadoras: [
      '¿Por qué México es uno de los países con mayor actividad sísmica y volcánica del planeta (interacción de 5 placas)?',
      '¿Cómo se genera la subducción de la Placa de Cocos bajo la Placa Norteamericana?',
      '¿Cómo opera la red del Sistema de Alerta Sísmica Mexicano (SASMEX) y qué protocolos salvan vidas?'
    ],
    inicioDetalle: 'Simulación de fallas y bordes de placa con galletas de chocolate y crema.',
    desarrolloDetalle: 'Laboratorio de Geofísica Escolar: Construir un sismógrafo casero con péndulo y marcador, mapear el Eje Neovolcánico Transversal (Popocatépetl, Colima, Pico de Orizaba) y diseñar el plan de repliegue sísmico.',
    cierreDetalle: 'Simulacro de evacuación evaluado con cronómetro y lista de cotejo de protección civil.',
    evaluacionCriterios: [
      'Explicación geodinámica de los tipos de límites de placas tectónicas',
      'Mapeo de zonas de alta sismicidad y volcanes activos en México',
      'Diseño y ejecución rigurosa de protocolos de protección civil ante sismos'
    ],
    materiales: 'Cajas de zapatos, canicas, plumones, mapas geomorfológicos, cronómetro.',
    entregable: 'Sismógrafo Casero Construido y Plan Maestro de Evacuación Escolar y Familiar.'
  },
  {
    id: 'f6-eti-05',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 105,
    temaTitulo: 'Migración humana como derecho, flujos globales y remesas',
    tituloProyecto: 'Caminantes del Mundo: Migración como Derecho Humano, Rutas y Diversidad Cultural',
    ejes: ['Inclusión', 'Interculturalidad Crítica', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Distingue la movilidad humana como un derecho inalienable, analiza causas estructurales de la migración (económicas, violencia, cambio climático) y su impacto sociocultural.',
    detonadoras: [
      '¿Por qué migrar es un derecho humano fundamental protegido por el derecho internacional?',
      '¿Cuáles son los principales corredores migratorios del mundo (Centroamérica-México-EUA, África-Europa)?',
      '¿Cómo enriquecen las familias migrantes la cultura y la economía de los países de acogida y origen?'
    ],
    inicioDetalle: 'Audición de testimonios orales de jóvenes migrantes en tránsito por México.',
    desarrolloDetalle: 'Taller de Cartografía Migratoria: Trazar las rutas de tren ("La Bestia"), albergues de acogida y analizar el impacto de las remesas familiares en la economía regional de México.',
    cierreDetalle: 'Mural de Solidaridad con los Hermanos Migrantes y combate a la xenofobia.',
    evaluacionCriterios: [
      'Análisis multicausal de los flujos migratorios contemporáneos',
      'Reconocimiento de la dignidad y derechos humanos de las personas en movilidad',
      'Empatía y propuestas contra la discriminación y el racismo'
    ],
    materiales: 'Mapas de rutas migratorias, testimonios en video/audio, cartulinas.',
    entregable: 'Atlas Testimonial de la Migración Humana y Decálogo de Acogida e Interculturalidad.'
  },

  // --- HISTORIA 1º, 2º, 3º (20 planeaciones) ---
  {
    id: 'f6-eti-06',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 106,
    temaTitulo: 'Los albores de la humanidad: poblamiento de América y restos fósiles en México',
    tituloProyecto: 'Cazadores y Recolectores: El Hombre de Tepexpan, la Mujer del Peñón y la Prehistoria Inclusiva',
    ejes: ['Pensamiento Crítico', 'Igualdad de Género'],
    pda: 'Fase 6 (1º Secundaria) - Reflexiona y toma postura en torno a las teorías del poblamiento de América (Estrecho de Bering, rutas costeras) y analiza el caso de los fósiles humanos en la Cuenca de México.',
    detonadoras: [
      '¿Cómo cruzaron los primeros grupos humanos durante la última glaciación hace más de 15,000 años?',
      '¿Por qué los análisis forenses modernos demostraron que el "Hombre de Tepexpan" era en realidad una mujer cazadora?',
      '¿Cómo transforma este descubrimiento la visión del papel de las mujeres en la prehistoria?'
    ],
    inicioDetalle: 'Observación de pinturas rupestres de la Sierra de San Francisco en Baja California Sur.',
    desarrolloDetalle: 'Taller de Arqueología Experimental: Modelar puntas de proyectil Clovis y Folsom en plastilina/barro y reconstruir la vida cotidiana de las bandas recolectoras en el Pleistoceno tardío.',
    cierreDetalle: 'Línea del tiempo ilustrada de la prehistoria mexicana con perspectiva de género.',
    evaluacionCriterios: [
      'Contrastación crítica de teorías del poblamiento americano',
      'Reconocimiento del papel activo de las mujeres en la prehistoria',
      'Uso riguroso de fuentes arqueológicas y datación histórica'
    ],
    materiales: 'Barro, plastilina, réplicas de puntas líticas, mapas de glaciaciones.',
    entregable: 'Diario Ilustrado de una Cazadora-Recolectora del Valle de México y Friso Cronológico.'
  },
  {
    id: 'f6-eti-07',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 107,
    temaTitulo: 'La agricultura mesoamericana y la domesticación del maíz',
    tituloProyecto: 'Los Hijos del Maíz: Teocintle, Milpa Mesoamericana y Revolución Urbana',
    ejes: ['Apropiación de las Culturas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Desarrolla teóricamente el entramado de causas que dieron lugar a la agricultura mesoamericana y el impacto civilizatorio de la domesticación del maíz a partir del teocintle.',
    detonadoras: [
      '¿Cómo lograron los antiguos pueblos de Tehuacán transformar el modesto teocintle en la mazorca de maíz moderna mediante selección artificial milenaria?',
      '¿Por qué la milpa (maíz, frijol, calabaza y chile) es un policultivo ecológicamente perfecto?',
      '¿Cómo permitió la agricultura el florecimiento de grandes metrópolis como Teotihuacán y Monte Albán?'
    ],
    inicioDetalle: 'Comparación de mazorcas de maíces criollos nativos (azul, rojo, palomero, cacahuazintle).',
    desarrolloDetalle: 'Laboratorio de Historia y Botánica: Dibujar la evolución genética del teocintle al maíz, modelar una chinampa lacustre y analizar el calendario agrícola solar mesoamericano.',
    cierreDetalle: 'Degustación de tortillas de maíz nixtamalizado y diálogo sobre la soberanía alimentaria.',
    evaluacionCriterios: [
      'Explicación científica e histórica del proceso de domesticación del maíz',
      'Comprensión del policultivo de la milpa como patrimonio agronómico',
      'Relación entre el excedente agrícola y la complejización social mesoamericana'
    ],
    materiales: 'Muestras de mazorcas de colores, semillas, barro para maqueta de chinampa.',
    entregable: 'Maqueta de Chinampa Mesoamericana y Ensayo Histórico "La Civilización del Maíz".'
  },
  {
    id: 'f6-eti-08',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 108,
    temaTitulo: 'La conquista de México-Tenochtitlan: alianzas indígenas y campañas militares',
    tituloProyecto: '1521, El Encuentro y la Ruptura: Señoríos Mesoamericanos, Tlaxcaltecas y la Caída de Tenochtitlan',
    ejes: ['Interculturalidad Crítica', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Problematiza los factores políticos, militares, tecnológicos y epidémicos (viruela) que determinaron la caída de Tenochtitlan en 1521, analizando las alianzas indígenas con Hernán Cortés.',
    detonadoras: [
      '¿Por qué la conquista no fue una hazaña de 500 españoles sino el levantamiento de decenas de miles de guerreros tlaxcaltecas, totonacas y texcocanos contra el tributo mexica?',
      '¿Qué papel desempeñó Malintzin (la Malinche) como diplomática e intérprete trilingüe?',
      '¿Cómo devastó la epidemia de viruela a la población antes del asalto final a la ciudad lacustre?'
    ],
    inicioDetalle: 'Lectura comentada de la Visión de los Vencidos de Miguel León-Portilla.',
    desarrolloDetalle: 'Taller de Análisis Historiográfico Multiperspectiva: Contrastar crónicas españolas (Bernal Díaz del Castillo) con códices indígenas (Lienzo de Tlaxcala, Códice Florentino) y elaborar un mapa del sitio de Tenochtitlan.',
    cierreDetalle: 'Debate histórico: ¿Fue 1521 una derrota, una victoria o el doloroso nacimiento del México mestizo?',
    evaluacionCriterios: [
      'Análisis multicausal de la caída de Tenochtitlan (alianzas, tecnología, epidemias, cosmovisión)',
      'Valoración crítica del papel de Malintzin y de los pueblos aliados',
      'Manejo riguroso de fuentes primarias y códices mesoamericanos'
    ],
    materiales: 'Fragmentos de crónicas coloniales, reproducciones de códices, mapas antiguos de Tenochtitlan.',
    entregable: 'Dossier Historiográfico Comparativo "Las Voces de 1521: Crónicas, Códices y Alianzas".'
  },
  {
    id: 'f6-eti-09',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 109,
    temaTitulo: 'El Virreinato de la Nueva España: minería, castas y resistencia esclava',
    tituloProyecto: 'La Plata y las Cadenas: Minería Novohispana, Sistema de Castas y Yanga',
    ejes: ['Interculturalidad Crítica', 'Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Distingue las formas de gobierno virreinal, la economía extractiva minera (Zacatecas, Guanajuato) y reflexiona sobre el sistema de castas y la gesta libertaria de Gaspar Yanga en Veracruz.',
    detonadoras: [
      '¿Cómo financió la plata extraída de la Nueva España el comercio global del Galeón de Manila y el Imperio Español?',
      '¿Cómo operaba la pirámide racista del sistema de castas en la sociedad colonial?',
      '¿Quién fue Gaspar Yanga y por qué fundó en 1609 el primer pueblo libre de América (San Lorenzo de los Negros)?'
    ],
    inicioDetalle: 'Observación de cuadros de castas novohispanos del siglo XVIII identificando etiquetas raciales.',
    desarrolloDetalle: 'Taller de Historia Social: Reconstruir las condiciones laborales en las minas de plata (el peonaje por deudas), el papel de las haciendas y redactar la proclama de libertad de los cimarrones de Yanga.',
    cierreDetalle: 'Juicio simulado al Tribunal del Santo Oficio de la Inquisición en el salón.',
    evaluacionCriterios: [
      'Comprensión del modelo económico extractivo novohispano y rutas comerciales',
      'Crítica fundamentada al sistema colonial de castas y discriminación',
      'Reconocimiento de las rebeliones indígenas y afrodescendientes cimarronas'
    ],
    materiales: 'Imágenes de cuadros de castas, mapas de la Ruta de la Plata, biografías de Yanga.',
    entregable: 'Periódico Histórico Colonial "El Pregonero Novohispano: Economía, Castas y Libertad".'
  },
  {
    id: 'f6-eti-10',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 110,
    temaTitulo: 'La Guerra de Independencia de 1810: de Hidalgo y Morelos a la Consumación',
    tituloProyecto: 'Sentimientos de la Nación: Las Cuatro Etapas de la Independencia de México',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Aplica conceptos organizadores para dar cuenta de las 4 etapas de la Independencia (Iniciación, Organización, Resistencia y Consumación), analizando los "Sentimientos de la Nación" de Morelos.',
    detonadoras: [
      '¿Qué ideales de justicia social plasmó José María Morelos al exigir "que se modere la opulencia y la indigencia"?',
      '¿Cómo cambió la lucha desde el levantamiento popular de Hidalgo en 1810 hasta el pacto militar del Plan de Iguala en 1821?',
      '¿Quiénes fueron las heroínas insurgentes (Leona Vicario, Josefa Ortiz, Gertrudis Bocanegra)?'
    ],
    inicioDetalle: 'Lectura en atril de los artículos clave de los "Sentimientos de la Nación" (1813).',
    desarrolloDetalle: 'Construcción del Friso Cronológico de la Independencia: Mapear en 4 paneles las campañas de Hidalgo, el Congreso de Anáhuac, la resistencia guerrillera de Vicente Guerrero y el Abrazo de Acatempan.',
    cierreDetalle: 'Análisis de la Constitución de Apatzingán de 1814 como raíz de los derechos humanos en México.',
    evaluacionCriterios: [
      'Secuenciación y caracterización rigurosa de las 4 etapas de la Independencia',
      'Análisis del pensamiento político y social de Morelos y los insurgentes',
      'Visibilización de la participación de mujeres y sectores populares'
    ],
    materiales: 'Documentos facsimilares de 1810-1821, cartulinas, líneas del tiempo.',
    entregable: 'Friso Histórico Insurgente y Ensayo "Vigencia de los Sentimientos de la Nación".'
  },

  // --- FORMACIÓN CÍVICA Y ÉTICA 1º, 2º, 3º (15 planeaciones) ---
  {
    id: 'f6-eti-11',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 111,
    temaTitulo: 'Los derechos humanos en México y en el mundo como valores universales',
    tituloProyecto: 'Dignidad sin Fronteras: La Declaración Universal de los Derechos Humanos y la CNDH',
    ejes: ['Inclusión', 'Pensamiento Crítico', 'Igualdad de Género'],
    pda: 'Fase 6 (1º Secundaria) - Asume una postura crítica sobre la vigencia de los derechos humanos como valores compartidos universales (libertad, igualdad, justicia, no discriminación), analizando mecanismos de defensa legal.',
    detonadoras: [
      '¿Por qué la DIGNIDAD HUMANA es la base inquebrantable de todos los derechos humanos?',
      '¿Cómo surgió la Declaración Universal de los Derechos Humanos en 1948 tras los horrores de la Segunda Guerra Mundial?',
      '¿Qué instituciones públicas (CNDH, CONAPRED) protegen a los ciudadanos frente a abusos de autoridad en México?'
    ],
    inicioDetalle: 'Lectura del Preámbulo de la Declaración Universal de 1948. Análisis del concepto de inalienabilidad.',
    desarrolloDetalle: 'Taller Jurídico Escolar: Analizar 3 casos de vulneración de derechos en México y redactar una queja formal ante la CNDH fundamentada en artículos constitucionales (1º, 3º, 4º).',
    cierreDetalle: 'Creación del "Mural de los Derechos Humanos Inviolables" en la escuela.',
    evaluacionCriterios: [
      'Comprensión de las características de los derechos humanos (universales, inalienables, indivisibles)',
      'Manejo de artículos de la Constitución Mexicana y tratados internacionales',
      'Redacción fundamentada de una queja formal ciudadana'
    ],
    materiales: 'Copias de la DUDH de 1948, Constitución Política de México, formatos de queja de CNDH.',
    entregable: 'Expediente Jurídico Simulado de Queja Ciudadana y Decálogo de Derechos Inalienables.'
  },
  {
    id: 'f6-eti-12',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 112,
    temaTitulo: 'Cultura de paz, mediación escolar y resolución no violenta de conflictos',
    tituloProyecto: 'Embajadores de Paz: El Círculo de Mediación Escolar y la Comunicación Asertiva',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Propone y aplica técnicas de mediación escolar y negociación pacífica para resolver conflictos cotidianos, comprendiendo la estructura del conflicto (personas, proceso y problema).',
    detonadoras: [
      '¿Por qué el conflicto no es negativo en sí mismo, sino una oportunidad de crecimiento si se gestiona sin violencia?',
      '¿Cómo actúa un mediador escolar neutral aplicando la escucha activa sin tomar partido ni juzgar?',
      '¿Cómo transformamos una disputa de agresión en un acuerdo donde ambas partes ganen (Ganar-Ganar)?'
    ],
    inicioDetalle: 'Dinámica de roleplay: Dos alumnos disputan un recurso escaso; el grupo analiza las emociones en juego.',
    desarrolloDetalle: 'Entrenamiento de Mediadores Escolares: Aprender el protocolo de mediación en 5 pasos (1. Apertura, 2. Cuéntame, 3. Aclarar el problema, 4. Lluvia de soluciones, 5. Acuerdo firmado) y simular 3 casos reales.',
    cierreDetalle: 'Instalación de la Mesa Permanente de Mediación de Conflictos de 2º Grado.',
    evaluacionCriterios: [
      'Desglose analítico de la estructura del conflicto (personas, proceso, problema)',
      'Aplicación rigurosa de los 5 pasos del protocolo de mediación pacífica',
      'Demostración de escucha activa, neutralidad y confidencialidad'
    ],
    materiales: 'Manual de mediación escolar, formatos de actas de acuerdo pacífico, sillas en círculo.',
    entregable: 'Manual de Mediación Escolar del Aula y Actas de Compromiso de Cultura de Paz.'
  },
  {
    id: 'f6-eti-13',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 113,
    temaTitulo: 'Principios de la democracia: Estado de derecho, división de poderes y legalidad',
    tituloProyecto: 'El Equilibrio del Poder: Estado de Derecho, División de Poderes y Ciudadanía Activa',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Participa de manera activa en la defensa de los principios de la democracia constitucional, analizando la función de la división de poderes (Ejecutivo, Legislativo, Judicial) y los contrapesos democráticos.',
    detonadoras: [
      '¿Por qué Montesquieu propuso la división de poderes para evitar que una sola persona o grupo ejerza la tiranía?',
      '¿Cómo defiende la Suprema Corte de Justicia de la Nación (SCJN) los derechos constitucionales frente a leyes injustas?',
      '¿Cómo ejercemos una ciudadanía crítica más allá del voto electoral?'
    ],
    inicioDetalle: 'Análisis de un dilema constitucional sobre la aprobación de una ley controvertida.',
    desarrolloDetalle: 'Simulación del Congreso Constituyente Escolar: Organizar comisiones legislativas para redactar una iniciativa de ley estudiantil, debatir en tribuna con argumentos constitucionales y votar por mayoría calificada.',
    cierreDetalle: 'Promulgación simbólica de la Ley de Participación Estudiantil.',
    evaluacionCriterios: [
      'Comprensión del sistema de pesos y contrapesos en el Estado democrático',
      'Argumentación fundada en principios constitucionales y de derechos humanos',
      'Participación activa y deliberación democrática en la asamblea legislativa'
    ],
    materiales: 'Constitución Política Mexicana, diario de debates simulado, mazo de presidencia.',
    entregable: 'Iniciativa de Ley Estudiantil Redactada y Acta de Sesión Constituyente del Aula.'
  },
  {
    id: 'f6-eti-14',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 114,
    temaTitulo: 'Transparencia, rendición de cuentas y acceso a la información pública (INAI)',
    tituloProyecto: 'Cuentas Claras: El Derecho de Acceso a la Información Pública y la Lucha Anticorrupción',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Analiza y ejerce el derecho al acceso a la información pública, la protección de datos personales y la rendición de cuentas de servidores públicos a través de la Plataforma Nacional de Transparencia.',
    detonadoras: [
      '¿Por qué el dinero público proviene de los impuestos de todos y los gobernantes tienen la obligación legal de rendir cuentas peso por peso?',
      '¿Cómo protege el INAI nuestros datos personales (huellas, fotos, historiales clínicos) frente al espionaje y la delincuencia digital?',
      '¿Cómo realizamos una solicitud ciudadana de acceso a la información pública?'
    ],
    inicioDetalle: 'Inspección de la Plataforma Nacional de Transparencia de México (PNT).',
    desarrolloDetalle: 'Taller de Solicitud de Información Pública Simulada: En equipos, redactar una solicitud formal de presupuesto sobre el mantenimiento de parques públicos o escuelas locales, evaluando tiempos de respuesta legal y recursos de revisión.',
    cierreDetalle: 'Decálogo para la protección de la privacidad digital y contraseñas seguras.',
    evaluacionCriterios: [
      'Comprensión del marco legal del Artículo 6º Constitucional y la Ley de Transparencia',
      'Elaboración técnica de una solicitud formal de información pública',
      'Conciencia crítica sobre la protección de la identidad y datos personales'
    ],
    materiales: 'Formatos de solicitud de la PNT, guías del INAI sobre privacidad de datos.',
    entregable: 'Expediente de Solicitud de Transparencia Simulada y Guía de Protección de Datos Personales.'
  },
  {
    id: 'f6-eti-15',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 115,
    temaTitulo: 'Igualdad sustantiva y perspectiva de género para erradicar el machismo',
    tituloProyecto: 'Cero Brechas: Igualdad Sustantiva, No Discriminación y Derechos Plenos de las Mujeres',
    ejes: ['Igualdad de Género', 'Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Participa en acciones dirigidas a reducir brechas de desigualdad de género en la escuela y comunidad, analizando leyes de paridad, brecha salarial y rechazando todo tipo de discriminación sexista.',
    detonadoras: [
      '¿Por qué la IGUALDAD SUSTANTIVA exige no solo leyes en papel sino cambios reales en la vida diaria?',
      '¿Qué factores perpetúan la brecha salarial y la sobrecarga no remunerada de trabajo doméstico en las mujeres?',
      '¿Cómo construimos masculinidades positivas basadas en el cuidado, la empatía y la no violencia?'
    ],
    inicioDetalle: 'Análisis de estadísticas del INEGI sobre el uso del tiempo libre y salarios por género.',
    desarrolloDetalle: 'Taller de Auditoría de Género Escolar: Revisar el uso de espacios deportivos en el recreo, liderazgos en comisiones escolares y libros de texto, redactando un Plan de Acción de Paridad e Inclusión.',
    cierreDetalle: 'Presentación del Plan de Igualdad Sustantiva a la Dirección de la Secundaria.',
    evaluacionCriterios: [
      'Manejo de conceptos de género, paridad, roles estereotipados e igualdad sustantiva',
      'Diagnóstico riguroso con datos estadísticos de la realidad escolar',
      'Diseño de propuestas concretas y transformadoras para erradicar el sexismo'
    ],
    materiales: 'Estadísticas del INEGI/INMUJERES, cartulinas, formatos de auditoría escolar.',
    entregable: 'Diagnóstico Escolar de Equidad de Género y Plan de Acción de Igualdad Sustantiva.'
  },
  // Planeaciones 116 a 150 de Ética, Naturaleza y Sociedades
  {
    id: 'f6-eti-16',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 116,
    temaTitulo: 'Los riesgos de desastre y la vulnerabilidad social',
    tituloProyecto: 'Atlas Comunitario de Riesgos: Amenazas Naturales, Antrópicas y Resiliencia Local',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Identifica que los desastres no son naturales sino construcciones sociales derivadas de la vulnerabilidad y la falta de prevención ante fenómenos naturales y tecnológicos.',
    detonadoras: ['¿Por qué un sismo o huracán es un fenómeno natural pero la pérdida de vidas es un desastre social evitable?', '¿Cómo influye la pobreza y la autoconstrucción precaria en la vulnerabilidad?'],
    inicioDetalle: 'Análisis de imágenes de inundaciones y deslaves en zonas de ladera urbana.',
    desarrolloDetalle: 'Mapeo Participativo de Riesgos: Identificar en el plano de la colonia zonas de riesgo por inundación, gasolineras, cables caídos y diseñar rutas de repliegue seguro.',
    cierreDetalle: 'Presentación del Atlas de Riesgos a los comités de vecinos de la escuela.',
    evaluacionCriterios: ['Diferenciación entre amenaza, peligro, vulnerabilidad y riesgo', 'Elaboración cartográfica del atlas escolar de riesgos', 'Propuesta de medidas no estructurales de prevención'],
    materiales: 'Planos de la colonia, marcadores de colores, guías del CENAPRED.',
    entregable: 'Atlas Comunitario de Riesgos y Plan Familiar de Protección Civil.'
  },
  {
    id: 'f6-eti-17',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 117,
    temaTitulo: 'El suelo como recurso estratégico para la seguridad alimentaria',
    tituloProyecto: 'Tierra Viva: Erosión, Agroecología y Conservación del Suelo Fértil',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Indaga sobre el origen, los horizontes del suelo (O, A, B, C) y los problemas de degradación por sobrepastoreo y monocultivo, proponiendo técnicas de agroecología y composta.',
    detonadoras: ['¿Por qué se requieren hasta 500 años para formar apenas $2.5\\text{ cm}$ de suelo fértil?', '¿Cómo destruye el uso excesivo de pesticidas y fertilizantes químicos la microbiota del suelo?'],
    inicioDetalle: 'Toma de muestras de suelo del jardín escolar analizando textura y presencia de materia orgánica.',
    desarrolloDetalle: 'Taller de Suelos y Lombricomposta: Construir una vermicompostera escolar con lombrices rojas californianas y analizar técnicas de terrazas y rotación de cultivos para evitar la erosión.',
    cierreDetalle: 'Aplicación de humus de lombriz en el huerto escolar y registro de crecimiento.',
    evaluacionCriterios: ['Comprensión de la pedogénesis y capas del perfil del suelo', 'Evaluación de causas y consecuencias de la erosión y desertificación', 'Construcción y manejo adecuado de la composta escolar'],
    materiales: 'Muestras de tierra, lupas, lombrices rojas, cajas de plástico, residuos orgánicos.',
    entregable: 'Vermicompostera Escolar en Funcionamiento y Manual de Conservación de Suelos.'
  },
  {
    id: 'f6-eti-18',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 118,
    temaTitulo: 'Desigualdades socioeconómicas y el Índice de Desarrollo Humano (IDH)',
    tituloProyecto: 'El Mapa de la Equidad: IDH, Coeficiente de Gini y Calidad de Vida en el Mundo',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Argumenta las desigualdades socioeconómicas en México y el mundo mediante la interpretación del Índice de Desarrollo Humano (salud, educación e ingreso) del PNUD.',
    detonadoras: ['¿Por qué un país con alto Producto Interno Bruto (PIB) puede tener altos niveles de pobreza si la riqueza está concentrada?', '¿Qué mide el IDH (esperanza de vida, escolaridad e ingreso per cápita)?'],
    inicioDetalle: 'Análisis de la pirámide de distribución del ingreso en México y América Latina.',
    desarrolloDetalle: 'Taller de Geografía Económica: Comparar en mapas temáticos los municipios con mayor IDH (Benito Juárez, CDMX) vs menor IDH (Cochoapa el Grande, Guerrero), proponiendo políticas de justicia redistributiva.',
    cierreDetalle: 'Debate sobre los Objetivos de Desarrollo Sostenible (ODS 1: Fin de la Pobreza, ODS 10: Reducción de Desigualdades).',
    evaluacionCriterios: ['Interpretación estadística y cartográfica del IDH y Coeficiente de Gini', 'Identificación de causas estructurales de la desigualdad regional', 'Propuestas fundadas en derechos humanos y justicia social'],
    materiales: 'Informes del PNUD e INEGI, mapas temáticos de México y el mundo.',
    entregable: 'Informe Geoeconómico "Radiografía del Desarrollo Humano en México y el Mundo".'
  },
  {
    id: 'f6-eti-19',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 119,
    temaTitulo: 'Grandes civilizaciones fluviales de la antigüedad (Mesopotamia, Egipto, Indo y China)',
    tituloProyecto: 'Los Ríos de la Historia: El Tigris, Éufrates, Nilo, Indo y Amarillo en el Origen Civilizatorio',
    ejes: ['Apropiación de las Culturas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Aplica el eje organizador uso y gestión del agua para analizar el desarrollo de las antiguas civilizaciones fluviales (Mesopotamia, Egipto, Indo y China) y la invención de la escritura.',
    detonadoras: ['¿Cómo el control de las inundaciones de los grandes ríos impulsó la invención de diques, canales y el cálculo geométrico?', '¿Por qué la escritura cuneiforme y los jeroglíficos nacieron para llevar registros de cosechas y leyes (Código de Hammurabi)?'],
    inicioDetalle: 'Imágenes del Creciente Fértil y el Nilo desde el espacio.',
    desarrolloDetalle: 'Taller de Escritura Antigua y Maqueta Hidráulica: Escribir nombres en tablillas de arcilla con caracteres cuneiformes y diseñar el plano de regadío del Antiguo Egipto.',
    cierreDetalle: 'Debate comparativo entre los sistemas jurídicos antiguos y los derechos actuales.',
    evaluacionCriterios: ['Análisis del agua como motor de la complejización urbana antigua', 'Comprensión de los sistemas de estratificación social y teocracia', 'Elaboración precisa de la tablilla cuneiforme'],
    materiales: 'Barro, estiletes de madera, mapas del Creciente Fértil.',
    entregable: 'Tablilla de Barro con Escritura Cuneiforme y Ensayo de Civilizaciones Fluviales.'
  },
  {
    id: 'f6-eti-20',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 120,
    temaTitulo: 'Grecia clásica, Roma y el espacio ecúmene mediterráneo',
    tituloProyecto: 'La Cuna de la Polis y la República: Democracia Ateniense, Derecho Romano y Esclavitud',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (1º Secundaria) - Indaga a partir de la noción de espacio ecúmene aplicada a los pueblos del Mediterráneo (fenicios, griegos, romanos), contrastando la democracia ateniense con la república romana y el trabajo esclavo.',
    detonadoras: ['¿Quiénes participaban en la asamblea democrática de Atenas y quiénes estaban totalmente excluidos (mujeres, esclavos, extranjeros)?', '¿Cómo estructuró el Derecho Romano las bases del sistema legal moderno?'],
    inicioDetalle: 'Recreación de un debate en el Ágora de Atenas sobre la justicia y el ostracismo.',
    desarrolloDetalle: 'Laboratorio de Historia Comparada: Construir un cuadro sinóptico contrastando la democracia directa de Atenas vs la República romana y redactar un juicio crítico sobre el sistema esclavista imperial.',
    cierreDetalle: 'Discusión sobre los límites de la democracia antigua frente a la ciudadanía universal moderna.',
    evaluacionCriterios: ['Diferenciación conceptual entre sistemas políticos del Mediterráneo', 'Análisis del rol del comercio marítimo fenicio y griego', 'Crítica ética al modelo económico sustentado en la esclavitud'],
    materiales: 'Mapas de la Cuenca del Mediterráneo, textos de Tucídides y Cicerón.',
    entregable: 'Cuadro Comparativo de Sistemas Políticos Clásicos y Ensayo sobre el Derecho Romano.'
  },
  {
    id: 'f6-eti-21',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 121,
    temaTitulo: 'Las Leyes de Reforma y la Guerra de Tres Años en México (1858-1861)',
    tituloProyecto: 'La Gran Transformación Laica: Benito Juárez, Melchor Ocampo y las Leyes de Reforma',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Analiza las Leyes de Reforma expedidas entre 1859 y 1861 (separación Iglesia-Estado, Registro Civil, nacionalización de bienes eclesiásticos) y estima su valor fundacional en el México contemporáneo.',
    detonadoras: ['¿Por qué la separación entre la Iglesia y el Estado fue indispensable para garantizar la libertad de culto y el Estado laico moderno?', '¿Cómo defendió el gobierno itinerante de Benito Juárez la legalidad constitucional durante la Guerra de Reforma?'],
    inicioDetalle: 'Lectura del Acta de Nacimiento número 1 del Registro Civil en Veracruz (Jerónima Francisca Juárez Maza).',
    desarrolloDetalle: 'Taller de Historia Política: Analizar los decretos de Juárez de 1859 en Veracruz, contrastar posturas liberales (Juárez, Ocampo, Ramírez) vs conservadoras (Miramón, Mejía) y redactar un alegato parlamentario.',
    cierreDetalle: 'Debate en atril: ¿Por qué el Estado Laico protege la libertad de creyentes y no creyentes por igual?',
    evaluacionCriterios: ['Comprensión de los principios rectores de las Leyes de Reforma', 'Contextualización histórica de la Guerra de Tres Años', 'Valoración del Estado Laico como pilar de la convivencia democrática'],
    materiales: 'Facsimilares de las Leyes de Reforma de 1859, biografías de liberales y conservadores.',
    entregable: 'Periódico Histórico "El Monitor Republicano: Las Leyes de Reforma y el Triunfo Laico".'
  },
  {
    id: 'f6-eti-22',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 122,
    temaTitulo: 'La Segunda Intervención Francesa, la Batalla de Puebla y el Imperio de Maximiliano',
    tituloProyecto: 'Soberanía Inquebrantable: El 5 de Mayo de 1862, la Resistencia Republicana y el Segundo Imperio',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Comprende la relevancia histórica de la Batalla del 5 de mayo de 1862 en Puebla, la resistencia militar popular frente al ejército francés y la restauración de la República en 1867.',
    detonadoras: ['¿Cómo venció el ejército mexicano al mando de Ignacio Zaragoza, apoyado por los indígenas zacapoaxtlas, al ejército más poderoso del mundo en los Fuertes de Loreto y Guadalupe?', '¿Por qué Maximiliano de Habsburgo no pudo sostener su imperio sin el apoyo de las bayonetas francesas?'],
    inicioDetalle: 'Telegrama de Zaragoza al presidente Juárez: "Las armas nacionales se han cubierto de gloria".',
    desarrolloDetalle: 'Laboratorio de Cartografía Militar: Diseñar la maqueta táctica de los Fuertes de Loreto y Guadalupe, analizar las cartas diplomáticas de la Alianza Tripartita de Londres y redactar el juicio de fusilamiento en el Cerro de las Campanas.',
    cierreDetalle: 'Exposición sobre el triunfo definitivo de la República en 1867.',
    evaluacionCriterios: ['Análisis táctico y político de la Batalla de Puebla del 5 de mayo', 'Comprensión de la resistencia diplomática y guerrillera del gobierno juarista', 'Reconocimiento del principio de no intervención y autodeterminación de los pueblos'],
    materiales: 'Partes de guerra del 5 de mayo de 1862, mapas de Puebla, maquetas.',
    entregable: 'Maqueta Táctica de la Batalla de Puebla y Crónica Militar Ilustrada.'
  },
  {
    id: 'f6-eti-23',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 123,
    temaTitulo: 'El Porfiriato: modernización económica vs desigualdad y represión social',
    tituloProyecto: 'Luces y Sombras del Porfiriato: Ferrocarriles, Oligarquía y las Huelgas de Cananea y Río Blanco',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Genera interpretaciones del Porfiriato comparando el crecimiento económico (ferrocarriles, telégrafo, minería, haciendas) con la represión a la oposición política, a la prensa y a los movimientos obreros y campesinos.',
    detonadoras: ['¿Cómo transformó el tendido de 20,000 km de vías férreas el mercado nacional durante el régimen de Porfirio Díaz?', '¿Por qué las huelgas de Cananea (1906) y Río Blanco (1907) encendieron la mecha de la Revolución Mexicana?', '¿Qué denunció John Kenneth Turner en su libro "México Bárbaro"?'],
    inicioDetalle: 'Visualización de fotografías de los festejos del Centenario de la Independencia en 1910 frente a imágenes de peones acasillados.',
    desarrolloDetalle: 'Taller de Historia Social: Contrastar la vida de la oligarquía de los "Científicos" en el Paseo de la Reforma vs las condiciones de esclavitud en Valle Nacional y las tiendas de raya.',
    cierreDetalle: 'Juicio histórico simulado a Porfirio Díaz en el aula con fiscalía y defensa.',
    evaluacionCriterios: ['Contraste fundamentado entre modernización tecnológica y opresión social', 'Análisis de fuentes históricas primarias (periódico El Hijo del Ahuizote)', 'Argumentación objetiva y fundamentada en el juicio histórico'],
    materiales: 'Fotografías del archivo Casasola, textos de México Bárbaro, caricaturas de Posada.',
    entregable: 'Gaceta Histórica Crítica "El México de 1910: Progreso para Pocos, Opresión para Muchos".'
  },
  {
    id: 'f6-eti-24',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 124,
    temaTitulo: 'La Revolución Mexicana de 1910 y la Constitución de 1917',
    tituloProyecto: 'Tierra y Libertad: Maderismo, Zapatismo, Villismo, Carrancismo y la Constitución de 1917',
    ejes: ['Pensamiento Crítico', 'Inclusión', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Analiza la causalidad de la Revolución Mexicana de 1910, la heterogeneidad de sus líderes y demandas (Plan de San Luis, Plan de Ayala, División del Norte) y la consagración de derechos sociales en la Constitución de 1917.',
    detonadoras: ['¿Por qué la Revolución Mexicana fue la primera gran revolución social del siglo XX en el mundo?', '¿Qué exigía el Plan de Ayala de Emiliano Zapata respecto a la restitución de tierras comunales?', '¿Cómo revolucionaron al mundo los Artículos 3º (Educación), 27 (Propiedad de la Tierra y Petróleo) y 123 (Derecho Laboral)?'],
    inicioDetalle: 'Audición de corridos revolucionarios ("La Adelita", "El Corrido de Emiliano Zapata").',
    desarrolloDetalle: 'Taller del Constituyente de Querétaro: Mapear las 4 corrientes revolucionarias y simular el debate de los diputados jacobinos (Múgica, Jara) en el Teatro de la República en 1917.',
    cierreDetalle: 'Presentación del mural de los derechos sociales consagrados en 1917.',
    evaluacionCriterios: ['Diferenciación de las demandas sociales de las corrientes revolucionarias', 'Comprensión del carácter pionero mundial de los derechos sociales de 1917', 'Visibilización de las soldaderas y enfermeras en la lucha armada'],
    materiales: 'Texto de la Constitución de 1917, mapas de campañas villistas y zapatistas, corridos.',
    entregable: 'Constitución Ilustrada del Aula de los Artículos Sociales (3º, 27 y 123).'
  },
  {
    id: 'f6-eti-25',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 125,
    temaTitulo: 'El Cardenismo: Reforma Agraria, Expropiación Petrolera de 1938 y Educación Socialista',
    tituloProyecto: 'La Soberanía Recuperada: Lázaro Cárdenas, el Ejido Colectivo y el 18 de Marzo de 1938',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Reúne información acerca de las principales políticas del gobierno de Lázaro Cárdenas (reparto agrario de 18 millones de hectáreas, creación del IPN, nacionalización de ferrocarriles y la Expropiación Petrolera del 18 de marzo de 1938).',
    detonadoras: [
      '¿Por qué el 18 de marzo de 1938 todo el pueblo de México donó joyas, animales y monedas para pagar la indemnización a las compañías petroleras extranjeras?',
      '¿Cómo transformó el reparto agrario en La Laguna y Yucatán la vida de millones de campesinos?',
      '¿Qué significó la fundación del Instituto Politécnico Nacional (IPN) para los hijos de los trabajadores?'
    ],
    inicioDetalle: 'Audición del discurso radiofónico original de Lázaro Cárdenas decretando la Expropiación Petrolera.',
    desarrolloDetalle: 'Taller de Historia Oral e Institucional: Analizar testimonios de familias que cooperaron en Bellas Artes en 1938 y diseñar una portada de periódico de la época conmemorando la soberanía energética.',
    cierreDetalle: 'Debate sobre la soberanía energética de México en el siglo XXI.',
    evaluacionCriterios: [
      'Análisis integral de los pilares del proyecto cardenista (agrario, obrero, educativo y energético)',
      'Comprensión del contexto internacional previo a la Segunda Guerra Mundial',
      'Reflexión sobre el valor de los bienes estratégicos de la nación'
    ],
    materiales: 'Grabación de audio de 1938, fotografías históricas de la donación popular, cartulinas.',
    entregable: 'Edición Conmemorativa de Periódico Histórico "El Nacional: ¡El Petróleo es de México!".'
  },
  {
    id: 'f6-eti-26',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 126,
    temaTitulo: 'El Movimiento Estudiantil de 1968 y la lucha por las libertades democráticas',
    tituloProyecto: '2 de Octubre no se Olvida: El Movimiento Estudiantil Popular de 1968 y la Masacre de Tlatelolco',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (2º Secundaria) - Recupera información de crónicas y narrativas de participantes del movimiento estudiantil de 1968 (Pliego Petitorio de 6 Puntos), reflexiona desde su condición juvenil y emite juicios éticos sobre la represión de Estado.',
    detonadoras: [
      '¿Qué exigían los jóvenes estudiantes de la UNAM y del IPN en su Pliego Petitorio de 1968 (libertad a presos políticos, derogación del delito de disolución social, destitución de jefes policiacos)?',
      '¿Por qué el gobierno autoritario de Gustavo Díaz Ordaz temía tanto a las manifestaciones pacíficas frente a los Juegos Olímpicos de 1968?',
      '¿Cómo el 68 sembró la semilla de la transición democrática y la defensa de los derechos humanos en México?'
    ],
    inicioDetalle: 'Lectura de testimonios de La Noche de Tlatelolco de Elena Poniatowska.',
    desarrolloDetalle: 'Taller de Memoria Histórica y Gráfica del 68: Analizar los volantes y grabados que los estudiantes imprimían en mimeógrafos clandestinos y diseñar un cartel conmemorativo de exigencia democrática.',
    cierreDetalle: 'Minuto de silencio y marcha pacífica de antorchas simbólicas en el patio escolar.',
    evaluacionCriterios: [
      'Comprensión de las causas y demandas democráticas del movimiento de 1968',
      'Juicio crítico y ético sobre el autoritarismo y la represión estatal',
      'Empatía histórica y vinculación con las luchas juveniles contemporáneas'
    ],
    materiales: 'Fragmentos de La Noche de Tlatelolco, copias de grabados del 68, cartulinas.',
    entregable: 'Cartel Conmemorativo de Gráfica Popular del 68 y Ensayo Crítico de Memoria Democrática.'
  },
  {
    id: 'f6-eti-27',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 127,
    temaTitulo: 'La Primera Guerra Mundial y la Revolución Rusa de 1917',
    tituloProyecto: 'Fuego en las Trincheras: Imperialismo, la Gran Guerra (1914-1918) y el Nacimiento de la URSS',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Explica las causas imperialistas de la Primera Guerra Mundial, la guerra de trincheras, el Tratado de Versalles y analiza la Revolución Rusa de 1917 como punto de ruptura geopolítico.',
    detonadoras: ['¿Cómo el asesinato del Archiduque Francisco Fernando desató la red de alianzas secretas arrastrando al mundo a la guerra?', '¿Qué exigían los sóviets de obreros y soldados en la consigna "Paz, Pan y Tierra" de Lenin en 1917?'],
    inicioDetalle: 'Lectura de cartas reales de soldados desde las trincheras del frente occidental.',
    desarrolloDetalle: 'Laboratorio de Geopolítica de la Primera Guerra: Mapear el colapso de 4 grandes imperios (Austrohúngaro, Ruso, Otomano y Alemán), analizar las draconianas sanciones de Versalles y redactar el diario de un soldado de 1917.',
    cierreDetalle: 'Debate sobre cómo el Tratado de Versalles sembró el resentimiento para la Segunda Guerra Mundial.',
    evaluacionCriterios: ['Explicación de las tensiones imperialistas y armamentistas de la "Paz Armada"', 'Análisis de la Revolución Bolchevique y el surgimiento del Estado soviético', 'Mapeo de la reorganización territorial europea tras 1918'],
    materiales: 'Mapas de Europa antes y después de 1918, cartas de soldados, cartulinas.',
    entregable: 'Atlas Histórico de la Gran Guerra de 1914 y Diario de un Soldado de Trinchera.'
  },
  {
    id: 'f6-eti-28',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 128,
    temaTitulo: 'La Segunda Guerra Mundial, el Holocausto y la bomba atómica',
    tituloProyecto: 'Nunca Más: Fascismo, Resistencia, la Segunda Guerra Mundial (1939-1945) y el Holocausto',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Problematiza el surgimiento del fascismo y nazismo, elabora un organizador cronológico de la Segunda Guerra Mundial, reflexiona sobre el Holocausto y debate el lanzamiento de las bombas atómicas en Hiroshima y Nagasaki.',
    detonadoras: [
      '¿Cómo el totalitarismo y la propaganda de odio nazi condujeron al genocidio sistemático de 6 millones de judíos y minorías?',
      '¿Qué papel jugó la Batalla de Stalingrado y el Día D en la derrota del Eje?',
      '¿Por qué el uso de armas nucleares en 1945 cambió para siempre la historia militar y ética de la humanidad?'
    ],
    inicioDetalle: 'Lectura de fragmentos del Diario de Ana Frank y testimonios de supervivientes de Auschwitz.',
    desarrolloDetalle: 'Taller de Memoria y Derechos Humanos: Elaborar un mapa cronológico interactivo de las etapas de la guerra y redactar un ensayo ético sobre la Declaración Universal de los Derechos Humanos nacida en 1948 para evitar que la barbarie se repita.',
    cierreDetalle: 'Encendido simbólico de velas por las víctimas de la guerra y la intolerancia.',
    evaluacionCriterios: [
      'Comprensión de las causas ideológicas, económicas y militares del conflicto',
      'Condena inequívoca del racismo, fascismo y crímenes de lesa humanidad',
      'Reflexión sobre el desarme nuclear y la cultura de paz internacional'
    ],
    materiales: 'Testimonios de supervivientes, mapas bélicos de 1939-1945, líneas de tiempo.',
    entregable: 'Memoria Histórica Ilustrada "El Imperativo del Nunca Más: Lecciones de 1939-1945".'
  },
  {
    id: 'f6-eti-29',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 129,
    temaTitulo: 'La Guerra Fría, la Carrera Espacial y la caída del Muro de Berlín',
    tituloProyecto: 'El Mundo Bipolar: Guerra Fría, Crisis de los Misiles, Carrera Espacial y 1989',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Genera hipótesis sobre el mundo bipolar (bloque capitalista liderado por EUA vs bloque socialista liderado por la URSS), analiza la Guerra de Vietnam, la Carrera Espacial y el simbolismo de la caída del Muro de Berlín en 1989.',
    detonadoras: ['¿Por qué se le llamó "Guerra Fría" si nunca hubo un enfrentamiento militar directo entre EUA y la URSS debido a la Destrucción Mutua Asegurada (MAD)?', '¿Cómo simbolizó el Muro de Berlín la división ideológica de Europa durante 28 años?'],
    inicioDetalle: 'Proyección del alunizaje del Apolo 11 en 1969 y la transmisión de la caída del Muro de Berlín en 1989.',
    desarrolloDetalle: 'Taller de Geopolítica Contemporánea: Mapear conflictos periféricos (Corea, Vietnam, Crisis de los Misiles en Cuba) y analizar la perestroika y glásnost que culminaron con la disolución de la Unión Soviética.',
    cierreDetalle: 'Debate sobre los desafíos del mundo multipolar actual.',
    evaluacionCriterios: ['Caracterización precisa de los modelos capitalista y socialista', 'Análisis de las tensiones nucleares y carrera tecnológica/espacial', 'Comprensión de las causas del colapso del bloque soviético'],
    materiales: 'Mapas del mundo bipolar de la Guerra Fría, hemerografía de 1989.',
    entregable: 'Línea del Tiempo Mural "La Guerra Fría: Del Telón de Acero a la Caída del Muro".'
  },
  {
    id: 'f6-eti-30',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 130,
    temaTitulo: 'Tribus urbanas, identidades juveniles y libertad de expresión',
    tituloProyecto: 'Mosaico Joven: Identidades Juveniles, Culturas Urbanas y Respeto a la Diversidad',
    ejes: ['Inclusión', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (1º Secundaria) - Valora la diversidad de grupos e identidades juveniles (skaters, gamers, otakus, colectivos artísticos) en la escuela y fortalece el respeto a formas de ser, vestir y pensar.',
    detonadoras: ['¿Por qué los jóvenes buscan pertenecer a colectivos con gustos compartidos?', '¿Cómo combatimos los prejuicios y la discriminación hacia la estética juvenil?'],
    inicioDetalle: 'Exhibición de fotografías y música de distintas culturas urbanas juveniles.',
    desarrolloDetalle: 'Taller de Identidades Juveniles: Realizar entrevistas a compañeros de distintos grados sobre sus pasiones, gustos musicales y artísticos, armando un collage de la diversidad del plantel.',
    cierreDetalle: 'Firma del Pacto Escolar de Cero Discriminación por Apariencia o Gustos.',
    evaluacionCriterios: ['Reconocimiento del derecho a la libre expresión de la personalidad', 'Desmontaje de estereotipos y estigmas hacia grupos juveniles', 'Actitud de empatía, inclusión y escucha activa'],
    materiales: 'Revistas, fotografías, cartulinas, música variada, marcadores.',
    entregable: 'Collage Mural "Nuestras Voces, Nuestras Identidades: Juventudes sin Etiquetas".'
  },
  {
    id: 'f6-eti-31',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 131,
    temaTitulo: 'Prevención de la trata de personas y ciberacoso (grooming y sexting no consentido)',
    tituloProyecto: 'Escudo Digital: Prevención de la Trata, Ciberseguridad y Ley Olimpia',
    ejes: ['Pensamiento Crítico', 'Igualdad de Género', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Compara los tipos de violencia digital (grooming, ciberacoso, difusión no consentida de imágenes íntimas) e identifica medidas legales de denuncia como la Ley Olimpia y líneas de ayuda.',
    detonadoras: ['¿Cómo operan los delincuentes y redes de trata a través de perfiles falsos en redes sociales y videojuegos en línea?', '¿Qué castiga la Ley Olimpia en México con penas de cárcel de hasta 6 años?'],
    inicioDetalle: 'Análisis de un caso simulado de estafa y manipulación en redes sociales.',
    desarrolloDetalle: 'Taller de Ciberseguridad Ciudadana: Configurar privacidad en redes, identificar "focos rojos" de manipulación psicológica y redactar el protocolo de denuncia ante la Policía Cibernética.',
    cierreDetalle: 'Difusión de la campaña escolar "Navega Seguro, Protege tu Intimidad".',
    evaluacionCriterios: ['Identificación de conductas de riesgo y señales de alerta digital', 'Conocimiento de los alcances punitivos y protectores de la Ley Olimpia', 'Diseño de materiales de prevención y autocuidado tecnológico'],
    materiales: 'Guías de ciberseguridad, infografías de la Ley Olimpia, cartulinas.',
    entregable: 'Guía Rápida de Ciberseguridad y Protocolo de Denuncia Digital Escolar.'
  },
  {
    id: 'f6-eti-32',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 132,
    temaTitulo: 'El derecho a la salud y prevención crítica del consumo de drogas sintéticas',
    tituloProyecto: 'Consciencia y Futuro: La Verdad sobre el Fentanilo, Drogas Sintéticas y Salud Integral',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Toma decisiones autónomas y responsables para prevenir el consumo de drogas sintéticas (fentanilo, metanfetaminas) y denuncia situaciones de riesgo en su entorno.',
    detonadoras: ['¿Por qué sustancias como el fentanilo son letales incluso en dosis microscópicas de apenas $2\\text{ miligramos}$?', '¿Cómo destruyen las metanfetaminas los centros de recompensa y juicio en el cerebro adolescente?'],
    inicioDetalle: 'Revisión de la campaña nacional "Si te drogas, te dañas" de la SEP y Secretaría de Salud.',
    desarrolloDetalle: 'Taller de Asertividad y Factores Protectores: Analizar técnicas de rechazo firme ante la presión de grupo ("No me interesa, cuido mi futuro") y elaborar un directorio de centros de atención a adicciones (CONASAMA).',
    cierreDetalle: 'Mesa de diálogo con testimonios de profesionales de la salud mental.',
    evaluacionCriterios: ['Comprensión científica de los daños neurológicos y orgánicos de drogas sintéticas', 'Desarrollo de habilidades de comunicación asertiva para resistir la presión social', 'Identificación de redes de apoyo médico y psicológico'],
    materiales: 'Guías docentes de prevención de adicciones, rotafolios, formatos de directorio.',
    entregable: 'Tríptico Informativo Escolar y Directorio de Apoyo Emocional y Salud Mental.'
  },
  {
    id: 'f6-eti-33',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 133,
    temaTitulo: 'El fin del Apartheid en Sudáfrica y el liderazgo ético de Nelson Mandela',
    tituloProyecto: 'El Largo Camino hacia la Libertad: Nelson Mandela, el Fin del Apartheid y la Reconciliación',
    ejes: ['Inclusión', 'Interculturalidad Crítica', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Analiza la elección de Nelson Mandela como presidente de Sudáfrica en 1994, la lucha contra el régimen racista del Apartheid y la Comisión de la Verdad y la Reconciliación.',
    detonadoras: ['¿Cómo pudo Nelson Mandela perdonar a sus carceleros tras 27 años de prisión injusta para evitar una guerra civil sangrienta?', '¿Cómo operaba el sistema racista del Apartheid que despojaba de la ciudadanía a la mayoría negra en su propia patria?'],
    inicioDetalle: 'Fragmento del discurso de toma de posesión de Nelson Mandela en Pretoria (1994).',
    desarrolloDetalle: 'Taller de Historia y Derechos Humanos: Analizar el papel de la resistencia no violenta de Desmond Tutu, las sanciones internacionales y la función de la Comisión de la Verdad para sanar heridas históricas.',
    cierreDetalle: 'Debate sobre la erradicación del racismo estructural en México y el mundo.',
    evaluacionCriterios: ['Comprensión del régimen del Apartheid y su desmantelamiento pacífico', 'Valoración del liderazgo ético basado en el perdón y la justicia restaurativa', 'Reflexión crítica sobre el racismo contemporáneo'],
    materiales: 'Biografía de Nelson Mandela, discursos históricos, mapas de Sudáfrica.',
    entregable: 'Ensayo Ético e Infografía Histórica "Nelson Mandela: Dignidad, Resiliencia y Perdón".'
  },
  {
    id: 'f6-eti-34',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía / Historia',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 134,
    temaTitulo: 'Cambio climático global, acuerdos internacionales y justicia ambiental',
    tituloProyecto: 'Planeta al Límite: El Acuerdo de París, COP y la Lucha por la Justicia Climática',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Asume una postura crítica ante el cambio climático global, evalúa los compromisos del Acuerdo de París (mantener el calentamiento bajo $1.5^{\\circ}\\text{C}$) y propone acciones comunitarias.',
    detonadoras: ['¿Por qué los países del Sur Global sufren las peores sequías e inundaciones a pesar de ser los que menos gases de efecto invernadero han emitido históricamente?', '¿Qué es la JUSTICIA CLIMÁTICA?'],
    inicioDetalle: 'Visualización interactiva del reloj climático global y mapas de aumento del nivel del mar.',
    desarrolloDetalle: 'Cumbre Climática Escolar Simulada (COP Juvenil): Representar a delegaciones de países insulares, potencias industriales y comunidades indígenas para negociar fondos de pérdidas y daños.',
    cierreDetalle: 'Firma del Tratado Escolar por la Reducción de la Huella Ecológica.',
    evaluacionCriterios: ['Comprensión de los fundamentos científicos del cambio climático', 'Análisis geopolítico de las negociaciones de las cumbres climáticas (COP)', 'Compromiso activo con la sustentabilidad y el consumo ético'],
    materiales: 'Informes del IPCC, banderas de delegaciones, banderas de debate.',
    entregable: 'Resolución de la Cumbre Climática Escolar y Plan de Acción Verde.'
  },
  {
    id: 'f6-eti-35',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 135,
    temaTitulo: 'El levantamiento zapatista del EZLN en 1994 y los Acuerdos de San Andrés',
    tituloProyecto: '¡Ya Basta!: El 1 de Enero de 1994, el EZLN, Autonomía Indígena y Derechos Colectivos',
    ejes: ['Interculturalidad Crítica', 'Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Analiza las causas del levantamiento armado del EZLN en Chiapas el 1 de enero de 1994, las demandas de los Acuerdos de San Andrés Larráinzar y la reforma constitucional del Artículo 2º.',
    detonadoras: ['¿Por qué el 1 de enero de 1994, el mismo día que entraba en vigor el Tratado de Libre Comercio (TLCAN), los pueblos mayas de Chiapas dijeron "¡Ya Basta!"?', '¿Qué son los Caracoles y Juntas de Buen Gobierno zapatistas?'],
    inicioDetalle: 'Lectura de la Primera Declaración de la Selva Lacandona (1994).',
    desarrolloDetalle: 'Taller de Historia Reciente: Analizar los 11 puntos del pliego del EZLN (techo, tierra, trabajo, pan, salud, educación, independencia, libertad, democracia, justicia y paz) y la lucha por el reconocimiento constitucional de los pueblos originarios.',
    cierreDetalle: 'Mesa redonda sobre el respeto a la libre determinación y autonomía indígena.',
    evaluacionCriterios: ['Comprensión del contexto histórico del neoliberalismo y marginación indígena', 'Análisis de los Acuerdos de San Andrés sobre derechos y cultura indígena', 'Valoración del diálogo como vía para la paz y la justicia social'],
    materiales: 'Textos de comunicados del EZLN, mapas de Chiapas, Constitución Mexicana.',
    entregable: 'Dossier Histórico "El Grito de Chiapas: 1994 y la Lucha por la Dignidad Indígena".'
  },
  {
    id: 'f6-eti-36',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 136,
    temaTitulo: 'La empatía, el diálogo interreligioso y la libertad de culto',
    tituloProyecto: 'Caminos de Fe y Consciencia: Libertad de Creencia, Tolerancia y Diálogo Interreligioso',
    ejes: ['Inclusión', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce y valora la libertad de culto y pensamiento como un derecho humano consagrado en el Artículo 24 Constitucional, promoviendo el diálogo ecuménico y la no discriminación.',
    detonadoras: ['¿Por qué cada persona es libre de profesar la fe de su elección o decidir no profesar ninguna religión?', '¿Cómo evitamos la intolerancia y el fanatismo religioso en la escuela laica?'],
    inicioDetalle: 'Presentación de símbolos de las grandes tradiciones espirituales y filosóficas del mundo.',
    desarrolloDetalle: 'Taller de Valores Compartidos: Analizar cómo el amor al prójimo, la compasión y la justicia están presentes en todas las religiones y filosofías humanistas.',
    cierreDetalle: 'Decálogo de Respeto a la Libertad de Conciencia en el aula.',
    evaluacionCriterios: ['Comprensión del marco constitucional de la libertad de culto', 'Aprecio por la diversidad religiosa y filosófica', 'Fomento de actitudes de tolerancia y diálogo pacífico'],
    materiales: 'Infografías de tradiciones religiosas, cartulinas, Constitución Mexicana.',
    entregable: 'Decálogo Ilustrado de Tolerancia Religiosa y Libertad de Pensamiento.'
  },
  {
    id: 'f6-eti-37',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 137,
    temaTitulo: 'Procesos productivos, cadenas globales de valor y comercio justo',
    tituloProyecto: 'De la Fábrica a tus Manos: Cadenas Globales de Suministro y Consumo Ético',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Compara procesos productivos y espacios económicos en México y el mundo, evaluando las contradicciones de las cadenas de suministro y promoviendo el Comercio Justo (Fair Trade).',
    detonadoras: ['¿Cuántos países y trabajadores intervienen en la fabricación de un solo teléfono celular o playera?', '¿Por qué en el comercio tradicional el campesino recibe una mínima fracción del precio final de su producto?'],
    inicioDetalle: 'Desglose del origen de las piezas de un smartphone (coltán de África, chips de Asia, ensamble global).',
    desarrolloDetalle: 'Laboratorio de Geografía Económica: Rastrear la ruta de un producto desde la extracción de materia prima hasta el desecho, analizando las condiciones laborales y promoviendo sellos de Comercio Justo.',
    cierreDetalle: 'Mercadito Escolar de Trueque y Comercio Local Justo.',
    evaluacionCriterios: ['Mapeo de las etapas de una cadena global de valor', 'Análisis crítico de la precarización laboral y la huella ecológica', 'Propuestas de consumo responsable y apoyo a cooperativas locales'],
    materiales: 'Mapas mundiales mudos, etiquetas de ropa y aparatos electrónicos.',
    entregable: 'Mapa de Flujos Comerciales Globales y Guía Escolar de Consumo Justo.'
  },
  {
    id: 'f6-eti-38',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 138,
    temaTitulo: 'La descolonización de Asia y África y el movimiento de países no alineados',
    tituloProyecto: 'Vientos de Libertad: Descolonización Africana, Gandhi y la Conferencia de Bandung',
    ejes: ['Interculturalidad Crítica', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Indaga acerca de los procesos de descolonización en Asia (la resistencia no violenta de Mahatma Gandhi en la India) y África (Argelia, Ghana, Congo), y el Movimiento de Países No Alineados.',
    detonadoras: ['¿Cómo la filosofía de la "Ahimsa" (no violencia activa) y la Marcha de la Sal de Gandhi derrotaron al Imperio Británico?', '¿Qué heridas territoriales y guerras civiles dejó el reparto colonial artificial de África?'],
    inicioDetalle: 'Lectura de fragmentos de los escritos de Frantz Fanon (Los Condenados de la Tierra) y Gandhi.',
    desarrolloDetalle: 'Taller de Historia Global: Comparar las vías de independencia pacífica (India) vs lucha armada (Argelia) y mapear los 10 principios de Bandung de autodeterminación y soberanía.',
    cierreDetalle: 'Reflexión sobre el neocolonialismo económico en el siglo XXI.',
    evaluacionCriterios: ['Comprensión de las causas del fin de los imperios coloniales europeos', 'Análisis de la resistencia no violenta como estrategia política', 'Mapeo del surgimiento de nuevas naciones en Asia y África'],
    materiales: 'Mapas históricos de África y Asia (1945-1970), discursos de Gandhi y Lumumba.',
    entregable: 'Atlas Histórico de la Descolonización y Ensayo "Gandhi y el Poder de la No Violencia".'
  },
  {
    id: 'f6-eti-39',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 139,
    temaTitulo: 'El derecho al agua potable, justicia hídrica y medio ambiente sano',
    tituloProyecto: 'Agua para Todos: El Artículo 4º Constitucional y la Defensa de los Bienes Comunes',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Analiza el derecho humano al agua potable y saneamiento garantizado por el Artículo 4º Constitucional, evaluando dilemas éticos entre el uso industrial y el consumo humano prioritario.',
    detonadoras: ['¿Por qué el agua es un bien común esencial para la vida y no una simple mercancía con fines de lucro?', '¿Cómo afecta la crisis hídrica a las colonias más marginadas en México?'],
    inicioDetalle: 'Revisión de notas periodísticas sobre sequías y protestas por desabasto de agua.',
    desarrolloDetalle: 'Taller Jurídico-Ambiental: Diseñar un proyecto de ley ciudadana para regular las concesiones de agua a embotelladoras e industrias, priorizando el abastecimiento doméstico y de hospitales.',
    cierreDetalle: 'Pacto Comunitario de Ahorro y Reutilización de Aguas Grises en el plantel.',
    evaluacionCriterios: ['Manejo del marco legal internacional y nacional sobre el derecho al agua', 'Argumentación ética sobre justicia distributiva y bienes comunes', 'Propuestas prácticas de captación pluvial y ahorro'],
    materiales: 'Formatos legislativos, datos de CONAGUA sobre acuíferos, rotafolios.',
    entregable: 'Iniciativa Ciudadana de Justicia Hídrica y Plan de Ahorro Escolar de Agua.'
  },
  {
    id: 'f6-eti-40',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 140,
    temaTitulo: 'Mito y cosmovisión en las culturas prehispánicas de México',
    tituloProyecto: 'El Quinto Sol: Mitos Fundacionales, Dioses del Maíz y la Filosofía Náhuatl',
    ejes: ['Apropiación de las Culturas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Compara y encuentra lo común y lo diverso entre mitos fundacionales de pueblos mesoamericanos (La Leyenda de los Soles, el Popol Vuh maya) y su concepción sagrada del cosmos.',
    detonadoras: ['¿Cómo explicaban los antiguos mayas en el Popol Vuh la creación del hombre a partir del maíz blanco y amarillo?', '¿Qué significaba para los mexicas vivir en la era del Quinto Sol (Nahui Ollin: Sol de Movimiento)?'],
    inicioDetalle: 'Lectura dramatizada de fragmentos del Popol Vuh.',
    desarrolloDetalle: 'Taller de Códices y Filosofía Náhuatl: Recrear en papel amate artesanal un códice con la Piedra del Sol y las 4 eras cósmicas previas, analizando conceptos de dualidad (Ometéotl) y respeto a la naturaleza.',
    cierreDetalle: 'Exhibición de códices en el aula con declamación de poemas de Nezahualcóyotl.',
    evaluacionCriterios: ['Interpretación profunda de la cosmovisión mesoamericana', 'Elaboración estética del códice con glifos y colores tradicionales', 'Aprecio por la literatura y filosofía indígena'],
    materiales: 'Papel amate o papel estraza envejecido con café, tintas, pinceles, reproducciones de códices.',
    entregable: 'Códice Mesoamericano en Papel Amate "La Leyenda de los Cinco Soles y la Creación".'
  },
  {
    id: 'f6-eti-41',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 141,
    temaTitulo: 'Organizaciones de la sociedad civil y voluntariado ciudadano',
    tituloProyecto: 'Sociedad en Marcha: Colectivos Ciudadanos, Voluntariado y Transformación Social',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Colabora con organizaciones de la sociedad civil (OSC) en proyectos de beneficio comunitario (rescate de áreas verdes, asilos, protección animal), ejerciendo una ciudadanía activa.',
    detonadoras: ['¿Por qué la sociedad civil organizada es indispensable para llegar donde el gobierno no alcanza?', '¿Qué habilidades de liderazgo democrático y empatía desarrollamos en el voluntariado?'],
    inicioDetalle: 'Mapeo de fundaciones, albergues y brigadas de rescate animal en la alcaldía/municipio.',
    desarrolloDetalle: 'Diseño de un Proyecto de Voluntariado Juvenil: Formular un plan de acción de 4 semanas con objetivos, cronograma, presupuesto cero y recolección de víveres/croquetas para un albergue local.',
    cierreDetalle: 'Jornada comunitaria de entrega de donativos y labores de voluntariado.',
    evaluacionCriterios: ['Estructuración técnica del proyecto de intervención social', 'Liderazgo participativo, trabajo colaborativo y transparencia', 'Impacto tangible en la comunidad vulnerada'],
    materiales: 'Formatos de gestión de proyectos sociales, cartas de vinculación institucional.',
    entregable: 'Carpeta Ejecutiva de Proyecto de Voluntariado Social con Evidencias de Campo.'
  },
  {
    id: 'f6-eti-42',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 142,
    temaTitulo: 'La invasión estadounidense de 1846-1848 y el Tratado de Guadalupe Hidalgo',
    tituloProyecto: 'La Herida del Río Bravo: El Despojo Territorial de 1848 y la Defensa Heroica de Chapultepec',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Explica la debilidad estructural de la joven república mexicana ante la invasión estadounidense de 1846-1848, la pérdida de más de la mitad del territorio nacional y el Tratado de Guadalupe Hidalgo.',
    detonadoras: ['¿Cómo justificó la doctrina imperialista del "Destino Manifiesto" la anexión forzada de Texas, California y Nuevo México?', '¿Por qué la división entre centralistas y federalistas debilitó la defensa de la patria?'],
    inicioDetalle: 'Comparación cartográfica del mapa de México de 1824 (4.4 millones de km²) vs el mapa tras 1848.',
    desarrolloDetalle: 'Taller de Historia Diplomática: Analizar los artículos del Tratado de Guadalupe Hidalgo de 1848, las batallas de La Angostura, Churubusco y Chapultepec, y el heroísmo del Batallón de San Patricio.',
    cierreDetalle: 'Ensayo reflexivo sobre la soberanía territorial y la memoria histórica.',
    evaluacionCriterios: ['Análisis geopolítico de las causas de la invasión de 1846-1848', 'Interpretación crítica del Tratado de Guadalupe Hidalgo', 'Valoración de la resistencia militar y popular'],
    materiales: 'Mapas históricos de 1824 y 1848, texto del Tratado de Guadalupe Hidalgo.',
    entregable: 'Atlas de las Pérdidas Territoriales de México y Ensayo Histórico de 1848.'
  },
  {
    id: 'f6-eti-43',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 143,
    temaTitulo: 'Climas de México y el mundo: clasificación climática de Köppen',
    tituloProyecto: 'El Mosaico Climático: Sistema de Köppen, Factores del Clima y Biodiversidad',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce las relaciones entre elementos (temperatura, presión, humedad) y factores del clima (latitud, altitud, relieve, corrientes marinas) aplicando la clasificación climática de Köppen.',
    detonadoras: ['¿Por qué en una misma latitud encontramos la selva tropical de Veracruz y la nieve perpetua del Pico de Orizaba (efecto de la altitud)?', '¿Qué significan las letras climáticas de Köppen ($Af, BWh, Cwb$)?'],
    inicioDetalle: 'Construcción de climogramas comparando Cancún (tropical) vs Toluca (templado de altura).',
    desarrolloDetalle: 'Taller de Climatología Escolar: Construir una estación meteorológica casera (termómetro, pluviómetro, veleta) y mapear los 5 grandes grupos climáticos de México (A, B, C, D, E).',
    cierreDetalle: 'Registro diario del tiempo atmosférico durante una semana.',
    evaluacionCriterios: ['Manejo de la clasificación climática de Köppen y su simbología', 'Interpretación y trazo de climogramas de temperatura y precipitación', 'Comprensión de la influencia del clima en las actividades humanas'],
    materiales: 'Pluviómetros de botella, termómetros, mapas climáticos del INEGI.',
    entregable: 'Estación Meteorológica Escolar Operativa y Climatograma Comparativo de México.'
  },
  {
    id: 'f6-eti-44',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 144,
    temaTitulo: 'La Revolución Industrial y el surgimiento del movimiento obrero',
    tituloProyecto: 'Máquinas y Carbón: De la Máquina de Vapor de Watt al Socialismo y los Sindicatos',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Ubica la confluencia de causas de la Primera y Segunda Revolución Industrial en Inglaterra y Europa, el surgimiento del proletariado fabril y las respuestas políticas (ludismo, cartismo, socialismo científico).',
    detonadoras: ['¿Cómo transformó la máquina de vapor la producción artesanal en industria en serie acelerando la urbanización masiva?', '¿Por qué los obreros trabajaban 16 horas diarias sin días de descanso hasta que nacieron los sindicatos?'],
    inicioDetalle: 'Proyección de escenas de la película "Tiempos Modernos" de Charles Chaplin.',
    desarrolloDetalle: 'Taller de Historia Económica y Social: Contrastar las condiciones laborales del siglo XIX con los derechos laborales actuales (jornada de 8 horas, seguridad social, salario mínimo) y redactar una proclama obrera.',
    cierreDetalle: 'Debate sobre la Cuarta Revolución Industrial y la automatización por Inteligencia Artificial.',
    evaluacionCriterios: ['Comprensión del impacto técnico, social y ambiental de la Revolución Industrial', 'Análisis de las ideologías obreras (socialismo utópico, marxismo, anarquismo)', 'Relación entre las luchas históricas del trabajo y las leyes laborales vigentes'],
    materiales: 'Grabados de fábricas del siglo XIX, Manifiesto Comunista (extractos), cartulinas.',
    entregable: 'Periódico Obrero del Siglo XIX "La Voz del Taller" y Ensayo sobre el Futuro del Trabajo.'
  },
  {
    id: 'f6-eti-45',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 145,
    temaTitulo: 'Cuidado del medio ambiente, bioética y derechos de la naturaleza',
    tituloProyecto: 'Derechos de la Madre Tierra: Bioética, Ecosistemas y Desarrollo Sustentable',
    ejes: ['Pensamiento Crítico', 'Vida Saludable', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (2º Secundaria) - Evalúa la contribución de la bioética y los derechos de la naturaleza en las prácticas de producción y consumo, proponiendo alternativas sustentables basadas en el "Buen Vivir" latinoamericano.',
    detonadoras: ['¿Por qué los ríos, bosques y arrecifes deben ser considerados sujetos de derechos legales protegidos por el Estado?', '¿Qué nos enseña la cosmovisión del "Buen Vivir" (Sumak Kawsay) sobre vivir en armonía sin explotar la Tierra?'],
    inicioDetalle: 'Lectura de leyes de países que otorgan personalidad jurídica a ríos sagrados.',
    desarrolloDetalle: 'Taller de Bioética Ambiental: Redactar la Carta de Derechos del Río o Bosque Local, estableciendo sanciones para empresas contaminantes y un plan comunitario de reforestación con flora nativa.',
    cierreDetalle: 'Jornada escolar de plantación de árboles nativos en la secundaria.',
    evaluacionCriterios: ['Aplicación de principios de bioética y sustentabilidad intergeneracional', 'Integración de saberes ancestrales sobre la Madre Tierra', 'Ejecución práctica de una acción de restauración ecológica'],
    materiales: 'Árboles nativos para reforestar, palas, tierra de hoja, cartulinas de la Carta de Derechos.',
    entregable: 'Carta Jurídica Simbólica de Derechos de los Ecosistemas Locales y Reporte de Reforestación.'
  },
  {
    id: 'f6-eti-46',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 146,
    temaTitulo: 'El voto de las mujeres en México (1953) y las luchas sufragistas',
    tituloProyecto: 'Voz y Voto: Hermila Galindo, Elvia Carrillo Puerto y la Conquista del Sufragio Femenino',
    ejes: ['Igualdad de Género', 'Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Dimensiona el tiempo histórico y las luchas de las mujeres mexicanas por sus derechos políticos, desde los Congresos Feministas de Yucatán (1916) hasta el decreto del voto federal en 1953.',
    detonadoras: ['¿Por qué a las mujeres mexicanas se les negó el derecho al voto hasta 1953 bajo el prejuicio machista de que "no tenían criterio político autónomo"?', '¿Quiénes fueron las "Monjas Rojas" de Yucatán lideradas por Elvia Carrillo Puerto?'],
    inicioDetalle: 'Revisión del decreto publicado en el Diario Oficial de la Federación el 17 de octubre de 1953.',
    desarrolloDetalle: 'Taller de Historia Sufragista: Reconstruir las biografías de Hermila Galindo, Laureana Wright y Amalia González Caballero, diseñando una pancarta y periódico de época exigiendo la ciudadanía plena.',
    cierreDetalle: 'Debate sobre la paridad de género obligatoria en el Congreso de la Unión actual.',
    evaluacionCriterios: ['Reconstrucción cronológica de las etapas del movimiento sufragista mexicano', 'Reconocimiento de liderazgos femeninos históricos fundamentales', 'Comprensión de la paridad de género como conquista democrática'],
    materiales: 'Diario Oficial de 1953, cartulinas, fotografías de sufragistas mexicanas.',
    entregable: 'Periódico Histórico Conmemorativo "La Mujer Mexicana: ¡Ciudadanas con Pleno Derecho!".'
  },
  {
    id: 'f6-eti-47',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Geografía',
    materiaFolder: 'Geografia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 147,
    temaTitulo: 'Conflictos territoriales y geopolítica de los recursos estratégicos',
    tituloProyecto: 'Mapas de Poder: Geopolítica de los Recursos Estratégicos, Litio, Petróleo y Tierras Raras',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Debate acerca de la multicausalidad de los conflictos territoriales en México y el mundo, analizando la disputa geopolítica por recursos estratégicos (litio, agua, petróleo, gas y minerales raros).',
    detonadoras: ['¿Por qué el "Triángulo del Litio" en Sudamérica y los yacimientos de Sonora son el centro de la disputa tecnológica global de autos eléctricos?', '¿Cómo provocan las disputas por fronteras marítimas y canales estratégicos (Suez, Panamá) tensiones internacionales?'],
    inicioDetalle: 'Mapeo de los principales estrechos marítimos y reservas mundiales de litio y gas.',
    desarrolloDetalle: 'Simulación de Consejo de Seguridad Geopolítico: Analizar un conflicto territorial real (disputas por agua en el Río Bravo o minerales en África), proponiendo acuerdos diplomáticos de soberanía compartida.',
    cierreDetalle: 'Conclusiones sobre la soberanía nacional y la nacionalización de recursos estratégicos.',
    evaluacionCriterios: ['Identificación cartográfica de recursos estratégicos globales', 'Análisis multicausal de tensiones territoriales contemporáneas', 'Argumentación diplomática basada en el derecho internacional y la paz'],
    materiales: 'Mapamundi temático de recursos energéticos, fichas de análisis geopolítico.',
    entregable: 'Dossier Geopolítico "La Batalla por los Recursos Estratégicos del Siglo XXI".'
  },
  {
    id: 'f6-eti-48',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Historia',
    materiaFolder: 'Historia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 148,
    temaTitulo: 'La Guerra Civil Española y el exilio republicano en México',
    tituloProyecto: 'Tierra de Asilo: Lázaro Cárdenas, el Barco Sinaia y el Aporte Cultural del Exilio Español',
    ejes: ['Inclusión', 'Interculturalidad Crítica', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (3º Secundaria) - Valora la actitud solidaria del gobierno mexicano al recibir a más de 25,000 refugiados del exilio republicano español (1939) y analiza su gigantesco aporte cultural, científico y educativo (Casa de México / El Colegio de México).',
    detonadoras: ['¿Cómo acogió México a los "Niños de Morelia" y a miles de intelectuales que huían de la dictadura fascista de Francisco Franco?', '¿Qué instituciones culturales y científicas fundaron los exiliados españoles en nuestro país?'],
    inicioDetalle: 'Fotografías históricas del arribo del barco Sinaia al puerto de Veracruz en junio de 1939.',
    desarrolloDetalle: 'Taller de Historia y Solidaridad Internacional: Investigar aportes de científicos, filósofos (José Gaos, Adolfo Sánchez Vázquez) y artistas exiliados, redactando cartas testimoniales de agradecimiento.',
    cierreDetalle: 'Reflexión sobre la tradición de asilo político y humanitario de México en el mundo.',
    evaluacionCriterios: ['Comprensión del contexto de la Guerra Civil Española y el fascismo', 'Valoración de la política exterior mexicana de asilo y solidaridad', 'Identificación del legado cultural e institucional del exilio'],
    materiales: 'Documentos del Ateneo Español de México, fotografías del barco Sinaia.',
    entregable: 'Álbum Testimonial "El Exilio Español en México: Memoria, Ciencia y Agradecimiento".'
  },
  {
    id: 'f6-eti-49',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Formación Cívica y Ética',
    materiaFolder: 'Formacion_Civica_y_Etica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 149,
    temaTitulo: 'El Tequio, la Faena y las formas comunitarias de trabajo solidario',
    tituloProyecto: 'Mano Vuelta: El Tequio Oaxaqueño, la Comunalidad y la Solidaridad Ciudadana',
    ejes: ['Interculturalidad Crítica', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Aprecia las prácticas comunitarias ancestrales de trabajo no remunerado en favor del bien común (el tequio, la faena, la gozona) y organiza una jornada solidaria en la escuela.',
    detonadoras: ['¿Cómo construyen los pueblos de Oaxaca sus caminos, escuelas y clínicas sin esperar presupuestos oficiales mediante el tequio?', '¿Qué es la "Mano Vuelta" (ayuda mutua recíproca)?'],
    inicioDetalle: 'Video documental sobre la organización comunal en la Sierra Juárez de Oaxaca.',
    desarrolloDetalle: 'Organización del Tequio Escolar: En asamblea general, acordar una jornada de limpieza profunda, pintura de bancas y remozamiento de áreas verdes del plantel donde todos participen.',
    cierreDetalle: 'Compartir alimentos comunitarios al estilo de una fiesta patronal tras la faena.',
    evaluacionCriterios: ['Comprensión filosófica y sociológica del concepto de comunalidad y tequio', 'Participación activa y solidaria en la faena escolar', 'Reflexión sobre la reciprocidad y el valor del trabajo colectivo'],
    materiales: 'Brochas, pintura, escobas, bolsas de basura, hojas de registro de asamblea.',
    entregable: 'Acta de Asamblea Comunal Escolar y Registro Fotográfico de la Jornada de Tequio.'
  },
  {
    id: 'f6-eti-50',
    campo: 'Ética, Naturaleza y Sociedades',
    campoTag: 'etica_naturaleza_y_sociedades',
    materia: 'Ética / Geografía / Historia',
    materiaFolder: 'Ciencias_Sociales_Integradas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 150,
    temaTitulo: 'Proyecto integrador de ciudadanía democrática y transformación socioambiental',
    tituloProyecto: 'Sembrando Ciudadanía: Diagnóstico Participativo y Presupuesto Ciudadano Escolar',
    ejes: ['Inclusión', 'Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Diseña e implementa un proyecto de ciudadanía democrática comunitaria que integre análisis espacial geográfico, perspectiva histórica y mecanismos de participación cívica directa.',
    detonadoras: ['¿Cómo podemos ejercer el Presupuesto Participativo para resolver una necesidad prioritaria de la escuela?', '¿Cómo aplicamos encuestas, cartografía social y asambleas deliberativas?'],
    inicioDetalle: 'Presentación de proyectos exitosos de presupuesto participativo municipal.',
    desarrolloDetalle: 'Taller de Presupuesto Participativo Escolar: Formular 3 proyectos viables (Comedor sustentable, techumbre con paneles solares, rampa accesible), elaborar cédulas de votación y realizar la jornada electoral estudiantil con urna transparente.',
    cierreDetalle: 'Conteo público de votos y entrega del proyecto ganador a las autoridades escolares.',
    evaluacionCriterios: ['Integración interdisciplinaria de Geografía, Historia y Formación Cívica', 'Ejecución transparente y democrática de la consulta estudiantil', 'Viabilidad técnica, ambiental y social de las propuestas'],
    materiales: 'Urnas electorales, boletas foliadas, formatos de plan de proyecto, rotafolios.',
    entregable: 'Expediente Completo del Proyecto de Presupuesto Participativo Escolar y Acta de Cómputo.'
  }
];

