import { NodeMetadataF6 } from './fase6_data_lenguajes';

// 50 planeaciones únicas para DE LO HUMANO Y LO COMUNITARIO en Secundaria (Fase 6)
export const humanoF6Data: NodeMetadataF6[] = [
  // --- TECNOLOGÍA 1º, 2º, 3º (17 planeaciones) ---
  {
    id: 'f6-hum-01',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 151,
    temaTitulo: 'Herramientas, máquinas e instrumentos como extensión de las capacidades humanas',
    tituloProyecto: 'La Prolongación del Cuerpo: De la Palanca Mecánica a la Robótica y la Ergonomía',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Explora las posibilidades corporales y la delegación de funciones en herramientas, máquinas e instrumentos, identificando procesos de cambio técnico en la satisfacción de necesidades humanas.',
    detonadoras: [
      '¿Cómo una simple pinza, un martillo o una lupa amplifican la fuerza, precisión y visión del cuerpo humano?',
      '¿Qué significa "delegar funciones" en un artefacto técnico (del cálculo mental al ábaco y a la computadora)?',
      '¿Cómo influye el diseño ergonómico de las herramientas en la prevención de lesiones laborales?'
    ],
    inicioDetalle: 'Desafío manual: Intentar extraer un clavo o cortar un alambre con las manos desnudas vs usando herramientas adecuadas.',
    desarrolloDetalle: 'Taller de Análisis Sistémico de Herramientas: Desarmar y analizar un taladro manual o tijeras, identificando partes motrices, de transmisión y de trabajo, y elaborar una ficha técnica ergonómica.',
    cierreDetalle: 'Galería de máquinas simples y compuestas en el laboratorio escolar.',
    evaluacionCriterios: [
      'Identificación del concepto de delegación de funciones técnicas',
      'Análisis de la estructura morfológica y ergonómica de herramientas',
      'Comprensión del cambio técnico a lo largo de la historia'
    ],
    materiales: 'Herramientas manuales (martillos, pinzas, destornilladores), láminas anatómicas, calibradores.',
    entregable: 'Informe Técnico y Ficha Ergonómica "La Evolución de las Herramientas como Extensión Corporal".'
  },
  {
    id: 'f6-hum-02',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 152,
    temaTitulo: 'Materiales, procesos técnicos y comunidad: sustentabilidad local',
    tituloProyecto: 'Alquimia Tecnológica: Ciclo de Vida de los Materiales y Ecotecnias Escolares',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Distingue el origen, transformación y propiedades tecnológicas de los materiales (madera, metales, polímeros, cerámicos), evaluando su ciclo de vida y proponiendo ecotecnias sustentables.',
    detonadoras: [
      '¿Qué diferencia a los materiales naturales de los sintéticos en cuanto a huella de carbono y biodegradabilidad?',
      '¿Cómo podemos construir una ecotecnia (calentador solar con botellas PET o deshidratador de frutas) con insumos locales?',
      '¿Cuál es el costo social y ambiental de la obsolescencia programada?'
    ],
    inicioDetalle: 'Pruebas de dureza, conductividad y flexibilidad con muestras de madera, cobre, aluminio y PVC.',
    desarrolloDetalle: 'Construcción de un Deshidratador Solar de Alimentos: Diseñar y armar una caja deshidratadora con madera reciclada, malla mosquitera y vidrio/plástico transparente para conservar fruta de temporada sin electricidad.',
    cierreDetalle: 'Prueba de deshidratación de manzanas y cálculo de ahorro energético.',
    evaluacionCriterios: [
      'Clasificación técnica y caracterización de propiedades de los materiales',
      'Diseño y manufactura funcional de la ecotecnia escolar',
      'Evaluación del impacto ambiental en el ciclo de vida del material'
    ],
    materiales: 'Madera de tarimas recicladas, malla mosquitera, bisagras, serruchos, lijas, clavos.',
    entregable: 'Prototipo Funcional de Deshidratador Solar y Manual de Construcción Sustentable.'
  },
  {
    id: 'f6-hum-03',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 153,
    temaTitulo: 'Sistemas técnicos: artesanales, industriales y automatizados',
    tituloProyecto: 'De la Rueda a la Fábrica Inteligente: Sistemas Artesanales, Industriales y Automatización',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Analiza los diferentes sistemas técnicos (artesanales con control humano directo, industriales con división del trabajo y automatizados con sensores y retroalimentación), reconociendo su impacto socioeconómico.',
    detonadoras: [
      '¿Qué distingue al trabajo único del alfarero o carpintero artesano de la producción masiva en cadena de montaje?',
      '¿Cómo operan los sistemas de control en lazo cerrado con sensores (termostato, servomotores)?',
      '¿Cómo impacta la robótica industrial en el empleo y en la calidad de los productos?'
    ],
    inicioDetalle: 'Comparación de un pan artesanal de leña vs un pan de molde ultraprocesado de fábrica.',
    desarrolloDetalle: 'Simulación de Línea de Producción Automatizada: Armar un prototipo con sensor de luz (LDR) y actuador con Arduino/relé que clasifique objetos por color o presencia, documentando el diagrama de flujo del sistema.',
    cierreDetalle: 'Mesa redonda sobre el futuro laboral de los jóvenes en la era de la automatización.',
    evaluacionCriterios: [
      'Diferenciación conceptual de los 3 tipos de sistemas técnicos',
      'Modelado de sistemas con entradas, procesos, salidas y retroalimentación',
      'Armado y programación básica del circuito de control automatizado'
    ],
    materiales: 'Placas Arduino/micro:bit, sensores LDR, servomotores, cables, cartón.',
    entregable: 'Prototipo Automatizado con Sensor y Diagrama de Bloques del Sistema Técnico.'
  },
  {
    id: 'f6-hum-04',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 154,
    temaTitulo: 'Comunicación y representación técnica: dibujo técnico y diagramas de flujo',
    tituloProyecto: 'El Lenguaje de la Ingeniería: Vistas Isométricas, Acotaciones y Diagramas de Flujo ANSI',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Elabora representaciones gráficas normalizadas de ideas y producciones técnicas (dibujo ortogonal: vista frontal, superior y lateral; dibujo isométrico a $30^{\\circ}$ y diagramas de flujo de procesos).',
    detonadoras: [
      '¿Por qué el dibujo técnico es un lenguaje universal que permite a ingenieros de cualquier país fabricar la misma pieza con precisión milimétrica?',
      '¿Cómo representamos un objeto tridimensional en sus tres vistas ortogonales principales?',
      '¿Qué significan los símbolos estándar de diagramas de flujo (óvalo de inicio, rectángulo de proceso, rombo de decisión)?'
    ],
    inicioDetalle: 'Lectura de un plano arquitectónico o manual de ensamble de muebles.',
    desarrolloDetalle: 'Taller de Dibujo Técnico y Flujos de Proceso: Trazar con escuadras a $30^{\\circ}$ la perspectiva isométrica de una pieza mecánica con acotaciones milimétricas y diseñar el diagrama de flujo algorítmico de un proceso productivo.',
    cierreDetalle: 'Revisión técnica de planos con escalímetro.',
    evaluacionCriterios: [
      'Trazado normativo de vistas ortogonales y perspectiva isométrica a $30^{\\circ}$',
      'Uso correcto de líneas de cota, flechas y escalas normalizadas',
      'Estructuración lógica de diagramas de flujo con simbología estándar'
    ],
    materiales: 'Escuadras de $30^{\\circ}-60^{\\circ}$ y $45^{\\circ}$, escalímetro, papel milimétrico, lápiz 2H.',
    entregable: 'Lámina de Dibujo Técnico Normalizado con Vistas Diédricas y Diagrama de Flujo.'
  },
  {
    id: 'f6-hum-05',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 155,
    temaTitulo: 'Evaluación interna y externa de sistemas tecnológicos sustentables',
    tituloProyecto: 'Auditoría Tecnológica: Eficiencia, Fiabilidad, Factibilidad e Impacto Ambiental',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Participa en la evaluación interna (eficiencia, eficacia, factibilidad, fiabilidad) y externa (impacto social, cultural y ambiental) de sistemas tecnológicos para proponer innovaciones sustentables.',
    detonadoras: [
      '¿Cómo auditamos si un sistema técnico escolar (ej. luminarias del salón o sistema de riego) es energéticamente eficiente?',
      '¿Qué diferencia a la "Eficacia" (lograr el objetivo) de la "Eficiencia" (lograrlo con el menor consumo de recursos)?',
      '¿Cómo evaluamos los impactos secundarios imprevistos de una nueva tecnología en la comunidad?'
    ],
    inicioDetalle: 'Auditoría energética rápida del salón de clases calculando el consumo en Watts de focos y aparatos.',
    desarrolloDetalle: 'Taller de Evaluación de Sistemas: Realizar la matriz de evaluación técnica y ambiental de 3 alternativas tecnológicas para la escuela (iluminación LED vs fluorescente, captación pluvial vs pipas), calculando costo-beneficio y retorno de inversión.',
    cierreDetalle: 'Presentación del Dictamen Técnico de Innovación a la administración escolar.',
    evaluacionCriterios: [
      'Aplicación de criterios de evaluación interna (eficacia, eficiencia, fiabilidad)',
      'Evaluación de impactos externos sociales, económicos y ambientales',
      'Formulación de propuestas de mejora continua y sustentabilidad'
    ],
    materiales: 'Medidores de consumo eléctrico (wattímetros), formatos de matriz de evaluación.',
    entregable: 'Dictamen de Auditoría Tecnológica Escolar y Propuesta de Optimización Sustentable.'
  },

  // --- TUTORÍA / SOCIOEMOCIONAL 1º, 2º, 3º (17 planeaciones) ---
  {
    id: 'f6-hum-06',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 156,
    temaTitulo: 'Formas de ser, pensar, actuar y autoconocimiento en la adolescencia',
    tituloProyecto: 'La Brújula Interior: Autoconocimiento, Fortalezas de Carácter y Autoestima',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce ideas, gustos, necesidades, posibilidades e intereses personales para favorecer el autoconocimiento, descubriendo nuevas potencialidades y enfrentando la transición a la secundaria con seguridad.',
    detonadoras: [
      '¿Qué cambios físicos, emocionales y sociales estás experimentando en esta nueva etapa de secundaria?',
      '¿Cuáles son tus 3 mayores fortalezas de carácter (creatividad, perseverancia, amabilidad, valentía)?',
      '¿Cómo construimos un autoconcepto positivo sin depender de la aprobación superficial en redes sociales?'
    ],
    inicioDetalle: 'Dinámica de la "Cápsula de Identidad": Escribir una carta a mi "yo" del futuro sobre quién soy hoy.',
    desarrolloDetalle: 'Taller de Autoconocimiento: Construir el "Mapa de Mis Fortalezas y Talentos" mediante la rueda de la vida (académico, familiar, amigos, salud, hobbies) identificando áreas de orgullo y metas de crecimiento.',
    cierreDetalle: 'Círculo de Aprecio Mutuo: Expresar cualidades positivas sinceras entre compañeros.',
    evaluacionCriterios: [
      'Identificación consciente de emociones, fortalezas y áreas de oportunidad',
      'Reflexión sobre el proceso de transición e identidad en la adolescencia',
      'Construcción de un autoconcepto positivo y realista'
    ],
    materiales: 'Plantillas de la Rueda de la Vida, formatos de carta personal, notas de aprecio.',
    entregable: 'Bitácora de Autoconocimiento "El Mapa de Mi Identidad y Mis Talentos".'
  },
  {
    id: 'f6-hum-07',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 157,
    temaTitulo: 'Diferencia entre emociones, estados de ánimo y sentimientos',
    tituloProyecto: 'El Océano Emocional: Emociones Primarias, Estados de Ánimo y Sentimientos Duraderos',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Distingue entre emociones (reacciones psicofisiológicas inmediatas), estados de ánimo (tonalidad afectiva prolongada) y sentimientos (construcciones conscientes duraderas) para la toma de decisiones asertivas.',
    detonadoras: [
      '¿Por qué una emoción como el susto o la ira dura apenas segundos, pero un sentimiento como el rencor o el amor puede durar años?',
      '¿Cómo influye nuestro estado de ánimo al despertar en la forma en que interpretamos lo que nos dicen los demás?',
      '¿Cómo pasamos de una emoción impulsiva a una respuesta reflexiva?'
    ],
    inicioDetalle: 'Proyección de escenas de la película "Intensamente" analizando el cuartel general de las emociones.',
    desarrolloDetalle: 'Laboratorio de Consciencia Afectiva: Clasificar 20 términos emocionales en el "Termómetro Afectivo" (Emoción vs Estado de Ánimo vs Sentimiento) y practicar técnicas de respiración diafragmática (4-7-8) para regular picos emocionales.',
    cierreDetalle: 'Creación del "Botiquín Emocional del Aula" con recursos de calma y escucha.',
    evaluacionCriterios: [
      'Diferenciación conceptual precisa de emoción, estado de ánimo y sentimiento',
      'Reconocimiento de las señales corporales asociadas a cada estado afectivo',
      'Aplicación de técnicas prácticas de autorregulación emocional'
    ],
    materiales: 'Cartas del vocabulario emocional de Plutchik, formatos del termómetro afectivo.',
    entregable: 'Cuadro Comparativo del Océano Emocional y Guía Personal de Autorregulación.'
  },
  {
    id: 'f6-hum-08',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 158,
    temaTitulo: 'Construcción del proyecto de vida y replanteamiento de metas',
    tituloProyecto: 'Trazando Mi Rumbo: Proyecto de Vida, Metas SMART y Resiliencia ante Fracasos',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (2º Secundaria) - Analiza intereses, necesidades y logros personales para diseñar un proyecto de vida con metas SMART (específicas, medibles, alcanzables, relevantes y con tiempo límite), replanteando estrategias ante dificultades.',
    detonadoras: [
      '¿Qué metas académicas, personales y vocacionales quieres haber alcanzado al terminar la secundaria?',
      '¿Cómo transformamos un deseo vago ("quiero que me vaya bien") en una meta SMART con pasos diarios?',
      '¿Cómo convertimos un error o tropiezo en una lección de aprendizaje sin caer en el desánimo?'
    ],
    inicioDetalle: 'Análisis de la historia de resiliencia de Thomas Edison o Stephen Hawking.',
    desarrolloDetalle: 'Taller de Planificación Estratégica Personal: Redactar 3 metas SMART a corto plazo (este bimestre), mediano plazo (fin de ciclo) y largo plazo (elección de preparatoria), con plan de contingencia ante obstáculos.',
    cierreDetalle: 'Firma de la Alianza de Compromiso Personal y entrega en sobre cerrado.',
    evaluacionCriterios: [
      'Formulación técnica de metas con metodología SMART',
      'Identificación de factores protectores y redes de apoyo familiar/escolar',
      'Desarrollo de actitudes de perseverancia y resiliencia'
    ],
    materiales: 'Formatos de metas SMART, cronogramas de hábitos, sobres membretados.',
    entregable: 'Plan Maestro del Proyecto de Vida con Metas SMART y Matriz de Resiliencia.'
  },
  {
    id: 'f6-hum-09',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 159,
    temaTitulo: 'Orientación vocacional y toma de decisiones para Educación Media Superior',
    tituloProyecto: 'Rumbo al Futuro: Orientación Vocacional, Oferta de Bachilleratos y Elección Consciente',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Visualiza su proyecto de vida y toma decisiones informadas para el ingreso a la Educación Media Superior (Bachillerato General, Tecnológico, Profesional Técnico), evaluando aptitudes e intereses vocacionales.',
    detonadoras: [
      '¿Cuáles son tus áreas de mayor afinidad: Físico-Matemáticas, Químico-Biológicas, Ciencias Sociales o Humanidades y Artes?',
      '¿Qué opciones de bachillerato existen en tu región (UNAM, IPN, CONALEP, DGETI, Bachilleres, Telebachillerato)?',
      '¿Cómo elegir una opción educativa con base en tus talentos auténticos y no por moda o presión social?'
    ],
    inicioDetalle: 'Aplicación del Test de Intereses y Aptitudes Vocacionales de Holland / Herrera y Montes.',
    desarrolloDetalle: 'Feria Vocacional Escolar: Investigar planes de estudio, perfiles de egreso y requisitos de ingreso de 3 instituciones de media superior, elaborando un cuadro comparativo vocacional.',
    cierreDetalle: 'Presentación de la Ruta de Elección Vocacional ante los padres de familia.',
    evaluacionCriterios: [
      'Interpretación de resultados del perfil de intereses y aptitudes vocacionales',
      'Investigación rigurosa de la oferta educativa de nivel medio superior',
      'Toma de decisiones vocacionales autónoma, informada y responsable'
    ],
    materiales: 'Cuestionarios vocacionales, guías de ingreso a media superior (COMIPEMS / estatales).',
    entregable: 'Expediente de Orientación Vocacional y Cuadro Comparativo de Opciones de Bachillerato.'
  },
  {
    id: 'f6-hum-10',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 160,
    temaTitulo: 'Prevención de conductas de riesgo, autolesiones y salud mental comunitaria',
    tituloProyecto: 'Redes de Vida: Salud Mental, Primeros Auxilios Psicológicos y Líneas de Ayuda',
    ejes: ['Vida Saludable', 'Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Reflexiona sobre las condiciones que representan riesgo para la salud mental (depresión, ansiedad, autolesiones) y promueve estrategias de autocuidado, redes de apoyo y primeros auxilios emocionales.',
    detonadoras: [
      '¿Por qué hablar de salud mental, tristeza profunda o ansiedad debe dejar de ser un tabú en la escuela y el hogar?',
      '¿Cómo identificamos señales de alerta en un amigo que está sufriendo en silencio?',
      '¿Cómo brindamos Primeros Auxilios Psicológicos (Escuchar sin juzgar, acompañar, conectar con un profesional)?'
    ],
    inicioDetalle: 'Dinámica de la Caja de Preguntas Anónimas sobre miedos y bienestar emocional.',
    desarrolloDetalle: 'Taller de Guardianes de la Vida: Aprender el protocolo de escucha empática, identificar factores de riesgo y crear el directorio de líneas gratuitas de apoyo emocional (Línea de la Vida 800 911 2000, Locatel, UNAM).',
    cierreDetalle: 'Campaña escolar de salud mental: "No estás solo, tu vida importa".',
    evaluacionCriterios: [
      'Comprensión de los factores que inciden en la salud mental adolescente',
      'Capacidad de escucha empática y aplicación de primeros auxilios psicológicos básicos',
      'Identificación y difusión de canales profesionales de ayuda inmediata'
    ],
    materiales: 'Guías de salud mental de UNICEF y Secretaría de Salud, cartulinas, tarjetas de apoyo.',
    entregable: 'Directorio Escolar de Salud Mental y Manual de Guardianes de Apoyo Emocional.'
  },

  // --- EDUCACIÓN FÍSICA 1º, 2º, 3º (16 planeaciones) ---
  {
    id: 'f6-hum-11',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 161,
    temaTitulo: 'Capacidades físico-motrices: resistencia, fuerza, velocidad y flexibilidad',
    tituloProyecto: 'Atletas en Acción: Evaluación de la Condición Física y Batería de Pruebas Eurofit',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Pone en práctica los elementos de la condición física (resistencia aeróbica, fuerza muscular, velocidad y flexibilidad) mediante pruebas diagnósticas, registrando su progreso en una bitácora deportiva.',
    detonadoras: [
      '¿Cómo medimos nuestra capacidad aeróbica y resistencia cardiovascular con la prueba de Cooper o Course-Navette?',
      '¿Por qué la flexibilidad es clave para evitar lesiones articulares y musculares en el deporte?',
      '¿Cómo diseñamos un plan de entrenamiento semanal equilibrado y adaptado a nuestro nivel inicial?'
    ],
    inicioDetalle: 'Calentamiento dinámico articular y toma de frecuencia cardíaca basal en la arteria radial/carótida.',
    desarrolloDetalle: 'Circuito de Evaluación de Condición Física (Batería Eurofit): Estación 1: Flexibilidad profunda de tronco (Sit and Reach); Estación 2: Abdominales en 1 minuto (fuerza); Estación 3: Salto de longitud sin impulso (potencia); Estación 4: Carrera de 50 metros (velocidad); Estación 5: Test de Course-Navette (resistencia).',
    cierreDetalle: 'Registro de datos en la Ficha Antropométrica y vuelta a la calma con estiramientos pasivos.',
    evaluacionCriterios: [
      'Ejecución técnica correcta y segura de las pruebas de condición física',
      'Registro honesto y sistemático de datos antropométricos y cardiovasculares',
      'Diseño de metas personales de mejora de condición física'
    ],
    materiales: 'Cintas métricas, cajón de flexibilidad, cronómetros, conos, fichas de registro.',
    entregable: 'Ficha Diagnóstica de Condición Física y Plan Semanal de Acondicionamiento Físico.'
  },
  {
    id: 'f6-hum-12',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 162,
    temaTitulo: 'Pensamiento estratégico y tácticas de juego en deportes de conjunto',
    tituloProyecto: 'Estrategia Total: Sistemas de Ataque, Defensa y Toma de Decisiones en la Cancha',
    ejes: ['Pensamiento Crítico', 'Inclusión', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Valora y reestructura las estrategias y tácticas de juego utilizadas en situaciones de iniciación deportiva (baloncesto, voleibol, fútbol, balonmano), incrementando la efectividad colectiva.',
    detonadoras: [
      '¿Cómo nos comunicamos con señas y códigos tácticos rápidos durante el dinamismo de una jugada?',
      '¿Qué diferencia a una defensa en zona de una defensa personal hombre a hombre?',
      '¿Cómo aprovechamos las fortalezas motrices de cada integrante del equipo para un ataque fluido?'
    ],
    inicioDetalle: 'Análisis de pizarras tácticas de baloncesto y voleibol con rotación de posiciones.',
    desarrolloDetalle: 'Torneo de Juegos Deportivos Modificados: Cada equipo diseña una jugada ensayada de saque y ataque rápido en baloncesto/balonmano, ejecuta 5 repeticiones en cancha y ajusta la táctica según la defensa rival.',
    cierreDetalle: 'Plenaria de análisis táctico: ¿Qué funcionó y cómo mejoró la sincronía de equipo?',
    evaluacionCriterios: [
      'Diseño y ejecución de esquemas tácticos ofensivos y defensivos',
      'Toma de decisiones motrices rápidas y asertivas en situaciones de juego real',
      'Inclusión activa y respeto hacia todos los compañeros de equipo'
    ],
    materiales: 'Balones de baloncesto/balonmano, petos de colores, pizarras tácticas borrables, conos.',
    entregable: 'Pizarra Táctica Diseñada en Equipo y Memoria de Estrategias Deportivas.'
  },
  {
    id: 'f6-hum-13',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 163,
    temaTitulo: 'Organización de torneos deportivos escolares, arbitraje y Juego Limpio (Fair Play)',
    tituloProyecto: 'Juego Limpio: Organización de la Liga Escolar Mixta, Arbitraje y Convivencia Pacífica',
    ejes: ['Inclusión', 'Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Diseña, organiza y evalúa torneos deportivos recreativos y de deporte educativo con equipos mixtos, aplicando reglamentos oficiales, arbitraje imparcial y códigos de Fair Play.',
    detonadoras: [
      '¿Cómo organizamos un torneo de liga escolar con sistema de todos contra todos (Round Robin) y eliminación directa?',
      '¿Por qué la figura del árbitro merece respeto absoluto y cómo se ejerce un arbitraje justo y sereno?',
      '¿Cómo erradicamos la violencia verbal y física en las porras y en el terreno de juego?'
    ],
    inicioDetalle: 'Firma del Juramento Deportivo del Atleta y Árbitro del Torneo de 3º Grado.',
    desarrolloDetalle: 'Comités de Organización Deportiva: Organizar 4 comisiones (1. Comité Técnico y Rol de Juegos, 2. Cuerpo de Árbitros y Jueces de Mesa, 3. Brigada de Primeros Auxilios e Hidratación, 4. Comité de Prensa y Fair Play) para operar la Liga Escolar Mixta.',
    cierreDetalle: 'Ceremonia de clausura y entrega de la Copa al Juego Limpio y Compañerismo.',
    evaluacionCriterios: [
      'Gestión y organización autónoma del torneo deportivo escolar',
      'Aplicación rigurosa del reglamento deportivo y arbitraje imparcial',
      'Promoción activa del Fair Play y resolución pacífica de controversias'
    ],
    materiales: 'Cédulas de arbitraje, cronómetros, silbatos, balones, botiquín deportivo, trofeo simbólico.',
    entregable: 'Convocatoria Oficial, Cédulas de Arbitraje y Memoria de la Liga Deportiva Mixta.'
  },
  {
    id: 'f6-hum-14',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 164,
    temaTitulo: 'Estilos de vida activos y combate al sedentarismo y uso excesivo de pantallas',
    tituloProyecto: 'Desconéctate y Muévete: Plan de 60 Minutos Diarios de Actividad Física y Salud Cardiovascular',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Implementa acciones para mantenerse físicamente activo en diferentes momentos del día (pausas activas, caminatas, deportes), combatiendo el sedentarismo tecnológico y la obesidad.',
    detonadoras: [
      '¿Cuántas horas al día pasamos sentados frente a pantallas de celular, televisión o videojuegos?',
      '¿Cómo deteriora el sedentarismo crónico la densidad ósea, la postura y la salud mental en adolescentes?',
      '¿Cómo integramos pausas activas de 5 minutos entre clases para reactivar el flujo sanguíneo cerebral?'
    ],
    inicioDetalle: 'Cálculo del gasto calórico diario y tiempo promedio de sedentarismo con una encuesta rápida.',
    desarrolloDetalle: 'Taller de Pausas Activas y Rutina HIIT Escolar: Diseñar una rutina de ejercicios de alta intensidad por intervalos (HIIT) de 15 minutos (saltos de tijera, sentadillas, escaladores, planchas) que se pueda realizar en casa sin aparatos.',
    cierreDetalle: 'Registro de frecuencia cardíaca post-ejercicio y entrega del Reto de 21 Días Activos.',
    evaluacionCriterios: [
      'Diseño y ejecución técnica de la rutina de ejercicios funcionales HIIT',
      'Monitoreo y comprensión de la respuesta cardíaca al esfuerzo físico',
      'Compromiso con la reducción del tiempo de pantalla sedentario'
    ],
    materiales: 'Cronómetros, música motivacional para entrenamiento, hojas de reto de 21 días.',
    entregable: 'Rutina Ilustrada de Ejercicios Funcionales y Bitácora del Reto de 21 Días Activos.'
  },
  {
    id: 'f6-hum-15',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología / Tutoría',
    materiaFolder: 'Proyectos_Comunitarios',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 165,
    temaTitulo: 'Proyecto integrador comunitario: Emprendimiento tecnológico sustentable',
    tituloProyecto: 'Emprendedores Sociales: Plan de Negocios Sustentable, Prototipo Tecnológico y Cooperativismo',
    ejes: ['Pensamiento Crítico', 'Inclusión', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Propone e implementa un emprendimiento sustentable o cooperativa escolar para atender una necesidad comunitaria, evaluando costos, impacto social y factibilidad técnica.',
    detonadoras: [
      '¿Cómo un emprendimiento social puede generar ingresos justos mientras resuelve un problema ecológico local?',
      '¿Cómo calculamos costos de producción, precio de venta justo y punto de equilibrio en una cooperativa?',
      '¿Qué modelo de economía social y solidaria empodera a los jóvenes de la secundaria?'
    ],
    inicioDetalle: 'Casos de éxito de cooperativas juveniles y empresas sociales en México.',
    desarrolloDetalle: 'Taller de Emprendimiento Social: Diseñar el Modelo Canvas de un producto ecológico (jabones biodegradables con aceite reciclado, libretas de papel reciclado, huertos verticales), fabricar el prototipo y elaborar el plan financiero.',
    cierreDetalle: 'Feria de Emprendimiento Social y presentación del pitch de ventas ante la comunidad.',
    evaluacionCriterios: [
      'Estructuración completa del modelo de negocio sustentable (Canvas)',
      'Calidad, funcionalidad e impacto ambiental positivo del prototipo fabricado',
      'Habilidades de trabajo en equipo cooperativo, liderazgo ético y comunicación'
    ],
    materiales: 'Plantillas de Modelo Canvas, insumos para prototipos, calculadoras.',
    entregable: 'Plan de Negocios del Emprendimiento Social y Prototipo Tecnológico Terminado.'
  },
  // Planeaciones 166 a 200 de De lo Humano y lo Comunitario
  {
    id: 'f6-hum-16',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 166,
    temaTitulo: 'Usos e implicaciones de la energía en los procesos técnicos',
    tituloProyecto: 'Fuerza Motriz: Fuentes de Energía en Procesos Técnicos y Eficiencia Energética',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Comprende la función de la energía en los sistemas técnicos y sus implicaciones en el desarrollo tecnológico para la toma de decisiones responsables en la disminución de riesgos.',
    detonadoras: ['¿Cómo se transforma la energía hidráulica, eólica y solar en trabajo mecánico útil?', '¿Cómo reducimos las pérdidas de calor y energía por fricción en mecanismos industriales?'],
    inicioDetalle: 'Análisis del funcionamiento de un molino de viento y una rueda hidráulica.',
    desarrolloDetalle: 'Taller de Conversión de Energía: Construir un generador manual con manivela y motor de DC para encender focos LED y medir el voltaje generado con multímetro.',
    cierreDetalle: 'Cálculo del ahorro de energía al sustituir motores ineficientes.',
    evaluacionCriterios: ['Comprensión de los tipos de energía en sistemas técnicos', 'Construcción y funcionamiento del generador electromecánico', 'Propuestas de eficiencia energética escolar'],
    materiales: 'Motores DC pequeños, engranes de plástico, manivelas, multímetros, LEDs.',
    entregable: 'Generador Manual Funcional e Informe de Conversión Energética.'
  },
  {
    id: 'f6-hum-17',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 167,
    temaTitulo: 'Factores que inciden en los procesos técnicos: equidad e inclusión',
    tituloProyecto: 'Tecnología para la Inclusión: Diseño Universal y Ayudas Técnicas para Discapacidad',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Analiza factores sociales y culturales en la definición de criterios para el desarrollo de soluciones técnicas que mejoran la calidad de vida, diseñando ayudas técnicas accesibles.',
    detonadoras: ['¿Cómo puede el diseño de un objeto facilitar la vida de una persona con movilidad reducida?', '¿Qué es el DISEÑO UNIVERSAL accesible para todos?'],
    inicioDetalle: 'Experimentar tareas manuales cotidianas con movilidad restringida simulada.',
    desarrolloDetalle: 'Taller de Diseño Inclusivo: Diseñar y fabricar un engrosador ergonómico de cubiertos/lápices y un pasapáginas accesible con materiales termoformables o impresión 3D.',
    cierreDetalle: 'Pruebas de usabilidad y entrega de las ayudas técnicas a la unidad de inclusión escolar.',
    evaluacionCriterios: ['Aplicación de principios de diseño universal y ergonomía', 'Funcionalidad y comodidad de la ayuda técnica fabricada', 'Compromiso ético con la accesibilidad y la no discriminación'],
    materiales: 'Foami moldeable, silicón, plásticos reciclados, cubiertos, lápices.',
    entregable: 'Set de Ayudas Técnicas Ergonómicas Fabricadas y Ficha de Usabilidad.'
  },
  {
    id: 'f6-hum-18',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 168,
    temaTitulo: 'Pensamiento estratégico y programación aplicada a la robótica',
    tituloProyecto: 'Mentes Algorítmicas: Programación por Bloques, Sensores y Robótica Móvil',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Implementa algoritmos y programas en microcontroladores para controlar robots móviles con sensores de obstáculos y seguidores de línea para resolver problemas de logística comunitaria.',
    detonadoras: ['¿Cómo toma decisiones un robot autónomo mediante estructuras condicionales (If-Then-Else)?', '¿Cómo leen los sensores infrarrojos el contraste entre blanco y negro en una pista?'],
    inicioDetalle: 'Desafío de programación desenchufada con laberintos en el piso.',
    desarrolloDetalle: 'Laboratorio de Robótica Educativa: Programar en Scratch/MakeCode un robot con sensor ultrasónico que evite colisiones en un circuito de rescate simulado.',
    cierreDetalle: 'Demostración en pista del robot móvil y optimización de código.',
    evaluacionCriterios: ['Lógica algorítmica estructurada y depuración de código', 'Integración correcta de sensores y actuadores en el robot', 'Resolución estratégica del reto de navegación autónoma'],
    materiales: 'Kits de robótica o microcontroladores Arduino/Microbit, sensores ultrasónicos, chasis con ruedas.',
    entregable: 'Robot Móvil Programado y Código Fuente Comentado del Algoritmo.'
  },
  {
    id: 'f6-hum-19',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 169,
    temaTitulo: 'Comunicación asertiva, escucha activa y resolución de desacuerdos entre pares',
    tituloProyecto: 'El Arte de Comunicarnos: Asertividad, Lenguaje "Yo" y Acuerdos sin Gritos',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Desarrolla habilidades de comunicación asertiva y escucha activa, distinguiendo estilos pasivo, agresivo y asertivo para expresar desacuerdos con dignidad y respeto.',
    detonadoras: ['¿Qué diferencia a quien calla por miedo (pasivo), quien ofende para imponerse (agresivo) y quien expresa lo que piensa con firmeza y calma (asertivo)?', '¿Cómo usamos mensajes en primera persona: "Yo me siento molesto cuando..."?'],
    inicioDetalle: 'Dramatización de 3 formas distintas de reaccionar ante un empujón accidental.',
    desarrolloDetalle: 'Taller de Mensajes Asertivos: Analizar 5 situaciones conflictivas típicas de secundaria y redactar respuestas asertivas aplicando la fórmula: Hecho + Emoción + Necesidad + Petición concreta.',
    cierreDetalle: 'Práctica de roleplay en parejas y entrega de carnets de asertividad.',
    evaluacionCriterios: ['Diferenciación conceptual de los 3 estilos de comunicación', 'Estructuración correcta de mensajes asertivos en primera persona', 'Demostración de escucha activa y empatía en las dinámicas'],
    materiales: 'Tarjetas de situaciones de conflicto, hojas de trabajo, carnets de asertividad.',
    entregable: 'Guía de Bolsillo de Comunicación Asertiva y Bitácora de Negociación Pacífica.'
  },
  {
    id: 'f6-hum-20',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 170,
    temaTitulo: 'Educación Integral en Sexualidad: afectividad, consentimiento y relaciones libres de violencia',
    tituloProyecto: 'Afectos Seguros: Consentimiento, Vínculos Libres de Violencia y Respeto Mutuo',
    ejes: ['Igualdad de Género', 'Vida Saludable', 'Inclusión'],
    pda: 'Fase 6 (2º Secundaria) - Valora la importancia del consentimiento libre, informado y continuo en las relaciones interpersonales, reconociendo señales de alerta de violencia en el noviazgo y promoviendo el respeto.',
    detonadoras: ['¿Por qué el consentimiento debe ser libre, entusiasta, específico y puede retirarse en cualquier momento?', '¿Qué mitos del "amor romántico" (los celos son prueba de amor, quien te quiere te aporrea) justifican el control y la violencia?'],
    inicioDetalle: 'Análisis de letras de canciones populares identificando mensajes de control o respeto.',
    desarrolloDetalle: 'Taller del Semáforo del Noviazgo: Clasificar conductas en Verde (confianza, libertad), Amarillo (control de celular, celos) y Rojo (gritos, amenazas, aislamiento), diseñando un violentómetro juvenil.',
    cierreDetalle: 'Firma colectiva del Decálogo de Relaciones Sanas e Igualitarias.',
    evaluacionCriterios: ['Comprensión rigurosa del concepto ético y legal de consentimiento', 'Identificación de indicadores tempranos de violencia de género y pareja', 'Propuesta de pautas de convivencia basadas en el cuidado mutuo y la equidad'],
    materiales: 'Semáforos de cartulina, canciones analizadas, formatos de decálogo.',
    entregable: 'Semáforo de Relaciones Saludables y Decálogo del Respeto Afectivo Escolar.'
  },
  {
    id: 'f6-hum-21',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 171,
    temaTitulo: 'Toma de decisiones éticas y dilemas morales en la juventud',
    tituloProyecto: 'La Encrucijada Moral: Dilemas Éticos, Valores y Toma de Decisiones Responsables',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Resuelve dilemas morales complejos evaluando principios éticos, consecuencias individuales y colectivas, y la congruencia entre lo que se piensa, se dice y se hace.',
    detonadoras: ['¿Qué harías si un amigo te pide encubrir una falta grave que afecta a otros compañeros?', '¿Cómo aplicamos el Principio del Imperativo Categórico de Kant (actúa de modo que tu acción pueda ser ley universal)?'],
    inicioDetalle: 'Planteamiento del clásico Dilema de Heinz (el medicamento robado para salvar una vida).',
    desarrolloDetalle: 'Taller de Juicio Moral de Kohlberg: Analizar en equipos 3 dilemas éticos juveniles reales, identificando valores en conflicto (lealtad vs justicia, beneficio propio vs bien común) y fundamentando la decisión.',
    cierreDetalle: 'Construcción del "Árbol de Decisiones Éticas" del salón.',
    evaluacionCriterios: ['Capacidad de argumentación en niveles superiores de juicio moral', 'Identificación de consecuencias a corto y largo plazo de las decisiones', 'Congruencia ética y responsabilidad ciudadana'],
    materiales: 'Fichas de dilemas morales, esquemas de árbol de decisiones.',
    entregable: 'Matriz de Resolución de Dilemas Éticos y Carta de Principios Morales Personales.'
  },
  {
    id: 'f6-hum-22',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 172,
    temaTitulo: 'Iniciación deportiva al atletismo: pruebas de pista y campo',
    tituloProyecto: 'Más Rápido, Más Alto, Más Fuerte: Atletismo Escolar, Relevos y Saltos Técnicos',
    ejes: ['Vida Saludable', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Integra habilidades motrices complejas en pruebas atléticas de pista (velocidad, relevos $4 \\times 50\\text{m}$, vallas adaptadas) y campo (salto de longitud, lanzamiento de pelota), perfeccionando la técnica corporal.',
    detonadoras: ['¿Cómo optimizamos la entrega del estafeta o testigo en la zona de transferencia de una carrera de relevos sin perder velocidad?', '¿Cómo influye el ángulo de batida ($45^{\\circ}$) en la distancia del salto de longitud?'],
    inicioDetalle: 'Calentamiento dinámico con técnica de carrera (skipping, talones a glúteos, zancada amplia).',
    desarrolloDetalle: 'Circuito de Pistas y Saltos: Estación 1: Salida baja de tacos con reacción al estímulo sonoro; Estación 2: Pase de estafeta a ciegas en zona de cambio; Estación 3: Salto de longitud en fosa de arena cuidando la fase aérea y caída amortiguada.',
    cierreDetalle: 'Minitorneo de relevos mixtos y vuelta a la calma con hidratación.',
    evaluacionCriterios: ['Ejecución técnica de la salida baja y pase del testigo', 'Coordinación y potencia en la carrera y batida de salto', 'Compañerismo y esfuerzo solidario en el equipo de relevos'],
    materiales: 'Testigos de relevos, fosa de salto o colchonetas, cronómetros, conos.',
    entregable: 'Registro Técnico de Marcas Atléticas y Ficha de Técnica de Carrera.'
  },
  {
    id: 'f6-hum-23',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 173,
    temaTitulo: 'Juegos tradicionales y autóctonos de México (Pelota mixteca, Pukiankuti, Ulama)',
    tituloProyecto: 'Juegos de los Abuelos: Juegos Autóctonos de México, Identidad y Rescate Cultural',
    ejes: ['Apropiación de las Culturas', 'Interculturalidad Crítica', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Reconoce y practica juegos tradicionales y autóctonos de México (Pelota Purépecha con pelota de fuego encendida de trapo, Pukiankuti tarahumara, Kimbomba yucateca), valorando la identidad comunitaria.',
    detonadoras: ['¿Cómo jugaban nuestros antepasados el juego de pelota con bastones (Uárukua Chanakua) simbolizando el paso del Sol?', '¿Por qué los juegos tradicionales fomentan la cooperación y el respeto más que el consumismo tecnológico?'],
    inicioDetalle: 'Construcción del bastón tradicional (Uárukua) y la pelota de trapo atada con mecate (Tatandukua).',
    desarrolloDetalle: 'Taller y Práctica de Pelota Purépecha: Delimitar la cancha con líneas de cal, acordar el reglamento tradicional de respeto sagrado al rival y disputar un encuentro deportivo ancestral.',
    cierreDetalle: 'Círculo de reflexión con los bastones alzados en señal de hermandad.',
    evaluacionCriterios: ['Destreza motriz en el manejo del bastón y control de la pelota', 'Aprecio y respeto por la cosmovisión de los pueblos originarios', 'Participación entusiasta y solidaria en los juegos tradicionales'],
    materiales: 'Bastones de madera curvos, mecate, tela de algodón, gises, silbato.',
    entregable: 'Bastón Tradicional Elaborado y Fichero Etnográfico de Juegos Autóctonos de México.'
  },
  {
    id: 'f6-hum-24',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 174,
    temaTitulo: 'Primeros auxilios básicos en actividades deportivas y escolares',
    tituloProyecto: 'Brigada de Rescate: Primeros Auxilios Deportivos, RICE, Vendajes y RCP Básica',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Aplica protocolos de primeros auxilios ante lesiones deportivas comunes (esguinces, calambres, desmayos, insolación) aplicando el protocolo RICE y la maniobra de Heimlich y RCP básica.',
    detonadoras: ['¿Cómo aplicamos el protocolo RICE (Reposo, Hielo, Compresión, Elevación) ante una torcedura de tobillo en la cancha?', '¿Cómo se realiza la Maniobra de Heimlich para salvar la vida de alguien que se está atragantando?'],
    inicioDetalle: 'Demostración de la cadena de supervivencia y llamada al 911 con datos precisos.',
    desarrolloDetalle: 'Taller Práctico de Vendajes y Maniobras de Emergencia: En parejas, realizar vendaje en espiga de muñeca y tobillo, practicar compresiones de RCP en maniquíes/cojines con ritmo de 100-120 lpm y simular la maniobra de Heimlich.',
    cierreDetalle: 'Certificación simbólica de la Brigada Juvenil de Primeros Auxilios Escolares.',
    evaluacionCriterios: ['Ejecución técnica correcta de vendajes funcionales y protocolo RICE', 'Demostración precisa de la Maniobra de Heimlich y RCP básica', 'Serenidad y liderazgo en la gestión de emergencias médicas simuladas'],
    materiales: 'Vendas elásticas de 5cm y 10cm, tela adhesiva, maniquíes o almohadas para RCP, hielo.',
    entregable: 'Manual Ilustrado de Primeros Auxilios Deportivos y Carnet de Brigadista Escolar.'
  },
  {
    id: 'f6-hum-25',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 175,
    temaTitulo: 'Seguridad e higiene en el taller escolar y manejo responsable de residuos tecnológicos',
    tituloProyecto: 'Taller Seguro: Señalética de Seguridad Industrial, Ergonomía y E-Waste',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Diseña e implementa normas y señalética de seguridad e higiene en el laboratorio de tecnología, gestionando el acopio y reciclaje seguro de residuos electrónicos (E-Waste).',
    detonadoras: ['¿Por qué las pilas alcalinas y tarjetas electrónicas no deben tirarse a la basura común debido a sus metales pesados (plomo, mercurio, cadmio)?', '¿Qué colores de seguridad industrial indican peligro (rojo), advertencia (amarillo) y primeros auxilios (verde) según las normas NOM-STPS?'],
    inicioDetalle: 'Inspección de riesgos y conexiones eléctricas en el taller de la escuela.',
    desarrolloDetalle: 'Taller de Señalética y Contenedor de Chatarra Electrónica: Fabricar señales normadas con pictogramas de seguridad y construir el depósito escolar de pilas y cables usados para llevarlos al Reciclatrón.',
    cierreDetalle: 'Auditoría de seguridad escolar y entrega del contenedor al comité ecológico.',
    evaluacionCriterios: ['Conocimiento y aplicación de la norma de señalética industrial', 'Comprensión de la toxicidad del e-waste y protocolos de manejo', 'Mantenimiento del orden y la higiene en el espacio técnico'],
    materiales: 'Cartulinas de colores normados, cajas de madera para contenedor de pilas, pinturas.',
    entregable: 'Señalética Normada del Laboratorio Técnico y Contenedor Escolar de E-Waste.'
  },
  {
    id: 'f6-hum-26',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 176,
    temaTitulo: 'Manejo del estrés académico, ansiedad y técnicas de mindfulness',
    tituloProyecto: 'Mente Serena: Técnicas de Estudio, Manejo del Estrés de Exámenes y Mindfulness',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Aplica estrategias de organización del tiempo (Técnica Pomodoro, Matriz de Eisenhower) y técnicas de atención plena (mindfulness) para regular el estrés y la ansiedad académica.',
    detonadoras: ['¿Cómo influye el cortisol y la falta de sueño en el rendimiento cerebral durante periodos de exámenes?', '¿Cómo dividimos el estudio en bloques de 25 minutos de enfoque y 5 de descanso con Pomodoro?'],
    inicioDetalle: 'Ejercicio de respiración guiada de atención plena y relajación muscular progresiva de Jacobson.',
    desarrolloDetalle: 'Taller de Gestión del Tiempo: Diseñar un planificador semanal clasificando pendientes en la Matriz de Eisenhower (Urgente vs Importante) y redactar un decálogo de hábitos para noches de estudio saludables.',
    cierreDetalle: 'Práctica de meditación de 3 minutos para iniciar la jornada escolar.',
    evaluacionCriterios: ['Aplicación práctica de herramientas de gestión del tiempo', 'Dominio de técnicas de respiración y autorregulación del estrés', 'Adopción de hábitos de sueño y descanso reparador'],
    materiales: 'Planificadores semanales impresos, música relajante instrumental.',
    entregable: 'Planificador Semanal Personalizado Pomodoro y Guía de Relajación Antiestrés.'
  },
  {
    id: 'f6-hum-27',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 177,
    temaTitulo: 'Gimnasia rítmica y acrosport: figuras acrobáticas y confianza mutua',
    tituloProyecto: 'Pirámides Humanas: Acrosport, Equilibrio Colectivo, Seguridad y Confianza',
    ejes: ['Inclusión', 'Artes y Experiencias Estéticas', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Construye composiciones gimnásticas y pirámides humanas colectivas (Acrosport) integrando roles de portor (base), ágil (cúspide) y ayudantes, cuidando la seguridad postural.',
    detonadoras: ['¿Por qué la confianza ciega y la comunicación son indispensables para que una pirámide humana se sostenga sin caer?', '¿Cómo distribuimos el peso sobre las zonas de apoyo óseas del portor (espalda y caderas) sin lastimar la columna?'],
    inicioDetalle: 'Ejercicios de estiramiento y calentamiento de muñecas, hombros y tronco en colchonetas.',
    desarrolloDetalle: 'Taller de Acrosport en Equipos de 4 y 6: Ensayar figuras estáticas de 2, 3 y 4 niveles con enlaces de danza y transiciones fluidas, respetando los apoyos seguros.',
    cierreDetalle: 'Presentación coreográfica de Acrosport con música rítmica.',
    evaluacionCriterios: ['Ejecución técnica y segura de las posiciones de portor y ágil', 'Equilibrio estático y coordinación coreográfica con música', 'Trabajo en equipo, confianza mutua y cuidado de la integridad del compañero'],
    materiales: 'Colchonetas de gimnasia, equipo de sonido, fichas de figuras de acrosport.',
    entregable: 'Partitura Coreográfica de Acrosport y Montaje Gimnástico Colectivo en Video/Fotos.'
  },
  {
    id: 'f6-hum-28',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 178,
    temaTitulo: 'Diseño y manufactura de objetos técnicos con impresión 3D y modelado CAD',
    tituloProyecto: 'Del Pixel al Átomo: Modelado Digital CAD (Tinkercad) y Manufactura Aditiva 3D',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Modela objetos técnicos tridimensionales en software de diseño asistido por computadora (CAD/Tinkercad), exportando archivos STL para manufactura aditiva con impresoras 3D.',
    detonadoras: ['¿Cómo convierte una impresora 3D un filamento termoplástico (PLA) fundido a $200^{\\circ}\\text{C}$ capa por capa en una pieza física real?', '¿Cómo aplicamos operaciones booleanas de unión y hueco para diseñar una pieza mecánica en CAD?'],
    inicioDetalle: 'Demostración de impresión 3D en vivo de un llavero geométrico.',
    desarrolloDetalle: 'Taller de Diseño CAD: En tabletas o computadoras, modelar en Tinkercad un repuesto mecánico para la escuela (perilla, soporte de cortina, soporte de celular) respetando tolerancias dimensionales.',
    cierreDetalle: 'Impresión y verificación dimensional de la pieza con vernier.',
    evaluacionCriterios: ['Manejo de herramientas de modelado 3D en software CAD', 'Precisión en cotas y ensambles mecánicos de la pieza', 'Optimización de parámetros de impresión (relleno, densidad, soportes)'],
    materiales: 'Computadoras con Tinkercad, impresora 3D, filamento PLA, calibrador vernier.',
    entregable: 'Archivo de Diseño 3D (.STL) y Prototipo Físico Impreso en 3D.'
  },
  {
    id: 'f6-hum-29',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 179,
    temaTitulo: 'Prevención del acoso escolar (bullying) y construcción de convivencia pacífica',
    tituloProyecto: 'Basta de Silencio: Protocolos Contra el Acoso Escolar, Ciberbullying y Redes de Apoyo',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Diseña e implementa una estrategia comunitaria de prevención e intervención temprana ante el acoso escolar (físico, verbal, relacional y digital), transformando el rol de los observadores pasivos en defensores activos.',
    detonadoras: ['¿Por qué el acoso escolar requiere de tres figuras: acosador, víctima y observadores pasivos que ríen o callan?', '¿Cómo empoderamos a los observadores para que digan "¡Detente, no da risa!" y apoyen a la víctima?'],
    inicioDetalle: 'Análisis de un cortometraje sobre acoso escolar y consecuencias psicológicas.',
    desarrolloDetalle: 'Taller de Defensores Activos: Elaborar el Protocolo Escolar de Denuncia Segura y Anónima (Buzón SOS), capacitando a brigadistas estudiantiles para acompañar a compañeros en situación de aislamiento.',
    cierreDetalle: 'Pacto de Aula: "Aquí nadie se queda solo".',
    evaluacionCriterios: ['Identificación de las dinámicas y roles del acoso escolar', 'Diseño de canales efectivos y confidenciales de reporte y apoyo', 'Actitud de solidaridad activa, valentía cívica y empatía'],
    materiales: 'Buzón escolar decorado, formatos de reporte anónimo, cartulinas.',
    entregable: 'Protocolo de Prevención e Intervención Anti-Bullying y Buzón SOS del Aula.'
  },
  {
    id: 'f6-hum-30',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 180,
    temaTitulo: 'Deportes alternativos y recreativos: Ultimate Frisbee, Korfbal y Kinball',
    tituloProyecto: 'Sin Contacto, Pura Estrategia: Ultimate Frisbee, Korfbal y Deportes Mixtos de Autoarbitraje',
    ejes: ['Inclusión', 'Vida Saludable', 'Igualdad de Género'],
    pda: 'Fase 6 (2º Secundaria) - Experimenta deportes alternativos mixtos (Ultimate Frisbee, Korfbal mixto, Kin-Ball) basados en el autoarbitraje (Espíritu de Juego), la equidad de género y la no violencia.',
    detonadoras: ['¿Cómo funciona el "Espíritu de Juego" en el Ultimate Frisbee donde no hay árbitros externos y los propios jugadores resuelven las faltas mediante el diálogo en la cancha?', '¿Por qué los deportes mixtos rompen la segregación tradicional entre hombres y mujeres?'],
    inicioDetalle: 'Práctica de lanzamientos técnicos de frisbee: Backhand, Forehand (Flick) y Hammer.',
    desarrolloDetalle: 'Torneo de Ultimate Frisbee Escolar: Delimitar las zonas de anotación (End Zones), jugar partidos de 10 minutos con equipos mixtos obligatorios y realizar el Círculo de Espíritu de Juego tras cada partido para felicitar al rival.',
    cierreDetalle: 'Evaluación formativa del Espíritu de Juego y premiación al juego más limpio.',
    evaluacionCriterios: ['Dominio técnico de lanzamientos y recepciones en carrera con el disco', 'Capacidad de resolución dialógica de jugadas dudosas (autoarbitraje)', 'Promoción activa de la equidad de género y compañerismo en la cancha'],
    materiales: 'Discos voladores (Frisbees) reglamentarios de 175g, conos, petos.',
    entregable: 'Reglamento Ilustrado de Ultimate Frisbee Escolar y Registro de Espíritu de Juego.'
  },
  {
    id: 'f6-hum-31',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 181,
    temaTitulo: 'Inteligencia artificial, ética de algoritmos y sesgos digitales',
    tituloProyecto: 'Algoritmos con Consciencia: Inteligencia Artificial, Aprendizaje Automático y Ética Digital',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Analiza los principios del aprendizaje automático (Machine Learning) y evalúa los sesgos algorítmicos, privacidad de datos y dilemas éticos en el uso cotidiano de la Inteligencia Artificial.',
    detonadoras: ['¿Cómo aprende un algoritmo de reconocimiento facial reconociendo patrones en millones de imágenes?', '¿Por qué una IA puede reproducir prejuicios racistas o sexistas si fue entrenada con datos sesgados?'],
    inicioDetalle: 'Prueba con la plataforma "Teachable Machine" entrenando una IA con la cámara web para clasificar objetos.',
    desarrolloDetalle: 'Laboratorio de IA y Ética: Entrenar un modelo de clasificación con Teachable Machine, identificar fallos en casos límite y redactar un Manifiesto Ético para el uso responsable de IA generativa en la escuela.',
    cierreDetalle: 'Debate: ¿Puede una IA sustituir la creatividad y empatía humana?',
    evaluacionCriterios: ['Comprensión de los principios básicos de Machine Learning (entrenamiento, prueba, sesgo)', 'Análisis crítico sobre privacidad y derechos digitales', 'Redacción de directrices éticas para el uso de herramientas de IA'],
    materiales: 'Computadoras con internet, cámara web, Teachable Machine de Google.',
    entregable: 'Modelo de IA Entrenado en Teachable Machine y Manifiesto Ético de Inteligencia Artificial.'
  },
  {
    id: 'f6-hum-32',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 182,
    temaTitulo: 'Hábitos de higiene digital, desintoxicación de pantallas y calidad del sueño',
    tituloProyecto: 'Desconexión Consciente: Higiene del Sueño, Luz Azul y Desintoxicación Digital',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Analiza el impacto de la luz azul y el uso nocturno de pantallas en la secreción de melatonina y la calidad del sueño, formulando un protocolo de desintoxicación digital.',
    detonadoras: ['¿Por qué revisar el celular antes de dormir engaña a la glándula pineal haciéndole creer que aún es de día?', '¿Cómo afecta dormir menos de 8 horas a la memoria, concentración y estado de ánimo en la escuela?'],
    inicioDetalle: 'Registro de tiempo de pantalla semanal en los teléfonos móviles de los estudiantes.',
    desarrolloDetalle: 'Taller de Higiene del Sueño: Diseñar el plan "Habitación Libre de Pantallas 1 hora antes de dormir", estableciendo rutinas de lectura nocturna y respiración relajante.',
    cierreDetalle: 'Monitoreo del diario de descanso y energía durante 7 días consecutivos.',
    evaluacionCriterios: ['Comprensión neurobiológica del ciclo circadiano y la melatonina', 'Adopción de medidas de reducción del uso nocturno de dispositivos', 'Mejora en los hábitos de descanso y bienestar general'],
    materiales: 'Diarios de sueño, gráficos del ciclo circadiano, cartulinas.',
    entregable: 'Diario de Higiene del Sueño y Plan Familiar de Desintoxicación Digital Nocturna.'
  },
  {
    id: 'f6-hum-33',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 183,
    temaTitulo: 'Senderismo, orientación en la naturaleza y campismo sustentable',
    tituloProyecto: 'Rumbo Verde: Senderismo, Manejo de Brújula, Mapas Topográficos y Principios "No Deje Rastro"',
    ejes: ['Vida Saludable', 'Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (3º Secundaria) - Diseña y realiza un recorrido de senderismo y orientación en espacios naturales o parques urbanos, utilizando brújula, mapas topográficos y aplicando los 7 Principios "No Deje Rastro".',
    detonadoras: ['¿Cómo orientamos un mapa topográfico con el Norte Magnético usando una brújula de limbo móvil?', '¿Cuáles son los 7 Principios de "No Deje Rastro" para disfrutar de la naturaleza sin alterarla?'],
    inicioDetalle: 'Identificación de rumbos y azimuts en el patio con brújulas de orientación.',
    desarrolloDetalle: 'Rally de Orientación en Equipos: Seguir un mapa topográfico escolar con 6 puntos de control ocultos (balizas), registrando coordenadas y armando un nudo de campismo en cada estación.',
    cierreDetalle: 'Círculo de campamento con armado de mochilas ergonómicas y cálculo de calorías.',
    evaluacionCriterios: ['Uso correcto de la brújula y lectura de curvas de nivel en mapas topográficos', 'Aplicación estricta de normas de seguridad y mínimo impacto ambiental', 'Trabajo en equipo y liderazgo en la navegación terrestre'],
    materiales: 'Brújulas de orientación tipo Silva, mapas topográficos impresos, cuerdas de campismo, balizas.',
    entregable: 'Hoja de Ruta del Rally de Orientación y Guía de Campismo Sustentable "No Deje Rastro".'
  },
  {
    id: 'f6-hum-34',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 184,
    temaTitulo: 'La técnica en la preparación y conservación tradicional de alimentos',
    tituloProyecto: 'Sabor y Ciencia: Técnicas Tradicionales de Conservación de Alimentos (Salazón, Ahumado y Deshidratado)',
    ejes: ['Apropiación de las Culturas', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce las técnicas tradicionales y artesanales de conservación de alimentos (fermentación, salazón, deshidratado y encurtido) como procesos técnicos que previenen la descomposición microbiana.',
    detonadoras: ['¿Cómo lograban los pueblos prehispánicos y coloniales conservar carnes y verduras sin refrigeradores?', '¿Cómo actúa la sal y el vinagre creando un medio inhóspito para bacterias y hongos (presión osmótica y pH ácido)?'],
    inicioDetalle: 'Cata sensorial de alimentos encurtidos y frutas deshidratadas.',
    desarrolloDetalle: 'Taller de Elaboración de Encurtidos Caseros: Esterilizar frascos de vidrio, preparar una salmuera aromatizada con hierbas de olor y envasar verduras (chiles, zanahorias, cebollas) sellando al vacío al baño maría.',
    cierreDetalle: 'Etiquetado con fecha de elaboración y tabla nutrimental.',
    evaluacionCriterios: ['Ejecución higiénica y técnica del protocolo de esterilización y sellado al vacío', 'Comprensión de los principios químicos y biológicos de conservación', 'Valoración del patrimonio gastronómico tradicional'],
    materiales: 'Frascos de vidrio herméticos, verduras, vinagre blanco, especias, ollas para esterilizar.',
    entregable: 'Frasco de Encurtidos Artesanales Elaborado y Ficha Técnica de Conservación.'
  },
  {
    id: 'f6-hum-35',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 185,
    temaTitulo: 'Manejo de la frustración, tolerancia al error y mentalidad de crecimiento',
    tituloProyecto: 'El Poder del "Todavía": Mentalidad de Crecimiento, Resiliencia y Superación del Error',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (2º Secundaria) - Desarrolla una mentalidad de crecimiento (Growth Mindset de Carol Dweck), reconociendo el error como oportunidad de aprendizaje y fortaleciendo la perseverancia ante desafíos académicos.',
    detonadoras: ['¿Qué diferencia a la "Mentalidad Fija" ("no soy bueno para las matemáticas") de la "Mentalidad de Crecimiento" ("aún no lo domino, pero con práctica lo lograré")?', '¿Cómo reacciona nuestro cerebro forjando nuevas conexiones sinápticas cuando nos esforzamos en una tarea difícil?'],
    inicioDetalle: 'Video de la investigadora Carol Dweck sobre el poder de la palabra "TODAVÍA".',
    desarrolloDetalle: 'Taller de Reencuadre Cognitivo: Transformar 10 frases derrotistas comunes en declaraciones de crecimiento activo y analizar un fracaso personal pasado identificando qué habilidades se ganaron.',
    cierreDetalle: 'Mural de los "Errores Brillantes": Compartir aprendizajes valiosos nacidos de equivocaciones.',
    evaluacionCriterios: ['Comprensión de la neuroplasticidad cerebral y mentalidad de crecimiento', 'Capacidad de reencuadre cognitivo y autorregulación de la frustración', 'Actitud de perseverancia y motivación intrínseca'],
    materiales: 'Tarjetas de reencuadre de mentalidad, cartulinas, plumones.',
    entregable: 'Guía Personal de Reencuadre Cognitivo "El Poder del Todavía: Mi Cerebro en Crecimiento".'
  },
  {
    id: 'f6-hum-36',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 186,
    temaTitulo: 'Danza folclórica, coordinación rítmica y expresión corporal en grupo',
    tituloProyecto: 'Raíces en Danza: Coordinación Espacial, Zapateado y Montaje de Danzas Tradicionales',
    ejes: ['Artes y Experiencias Estéticas', 'Apropiación de las Culturas', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Integra capacidades rítmicas, espaciales y de expresión corporal en la ejecución de coreografías de danza folclórica mexicana (El Jarabe Tapatío, La Bamba, Las Chiapanecas), valorando el patrimonio cultural.',
    detonadoras: ['¿Cómo sincronizamos el movimiento de faldeo y zapateado al compás de la música tradicional en formaciones geométricas grupales?', '¿Qué representa la indumentaria típica y los pasos de danza en la identidad regional?'],
    inicioDetalle: 'Calentamiento rítmico articular y práctica del paso básico de tres tiempos.',
    desarrolloDetalle: 'Taller Coreográfico de Danza Regional: Ensayar en parejas y bloques las figuras espaciales (cruces, círculos, diagonales) de un son jarocho o danza norteña, coordinando zapateado y expresión gestual.',
    cierreDetalle: 'Montaje general de la coreografía en el patio escolar.',
    evaluacionCriterios: ['Coordinación rítmica y precisión en el zapateado', 'Manejo del espacio escénico y sincronía grupal', 'Expresión corporal, entusiasmo y respeto por la tradición'],
    materiales: 'Música folclórica regional, faldas de ensayo, calzado adecuado, equipo de sonido.',
    entregable: 'Montaje Coreográfico de Danza Folclórica y Ficha Etnográfica del Baile Tradicional.'
  },
  {
    id: 'f6-hum-37',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 187,
    temaTitulo: 'Diseño web accesible, código HTML/CSS y alfabetización digital',
    tituloProyecto: 'La Red Inclusiva: Desarrollo Web con HTML5, Accesibilidad Digital y Hojas de Estilo CSS',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Diseña y programa una página web básica con HTML5 y CSS que cumpla con pautas de accesibilidad web (contraste adecuado, etiquetas alt para imágenes, tipografías legibles).',
    detonadoras: ['¿Cómo permite el código HTML5 estructurar la información para que un lector de pantalla para personas ciegas la interprete con claridad?', '¿Por qué la accesibilidad digital es un derecho humano en la era de la información?'],
    inicioDetalle: 'Inspección de código fuente de una página web en el navegador.',
    desarrolloDetalle: 'Taller de Programación Web Inclusiva: Escribir la estructura de una página informativa escolar con etiquetas semánticas (`<header>`, `<nav>`, `<article>`, `<footer>`) y aplicar estilos CSS responsivos y accesibles.',
    cierreDetalle: 'Validación de accesibilidad con herramientas en línea y publicación local.',
    evaluacionCriterios: ['Uso correcto de etiquetas semánticas de HTML5 y reglas de estilo CSS', 'Cumplimiento de estándares de accesibilidad digital básica', 'Diseño limpio, ordenado y funcional'],
    materiales: 'Computadoras con editor de código (VS Code o Bloc de Notas), navegadores web.',
    entregable: 'Página Web Accesible Programada en HTML5/CSS sobre una Causa Comunitaria.'
  },
  {
    id: 'f6-hum-38',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 188,
    temaTitulo: 'Educación financiera para adolescentes: ahorro, presupuesto y consumo inteligente',
    tituloProyecto: 'Finanzas para la Vida: Presupuesto Personal, Ahorro Inteligente y Metas Económicas',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Diseña un presupuesto personal y familiar mensual (ingresos, gastos fijos, variables y ahorro), analiza el funcionamiento del interés compuesto y promueve el consumo crítico frente a la publicidad.',
    detonadoras: ['¿Qué diferencia a un "Gasto Hormiga" (antojos diarios) de una inversión que genera valor a largo plazo?', '¿Cómo se aplica la regla de ahorro 50-30-20 (50% necesidades, 30% gustos, 20% ahorro)?', '¿Qué es el interés compuesto y cómo hace crecer los ahorros con el tiempo?'],
    inicioDetalle: 'Cálculo del costo acumulado anual de comprar un refresco y botana diarios ($15,000+ pesos).',
    desarrolloDetalle: 'Taller de Educación Financiera Juvenil: Elaborar un simulador de presupuesto mensual en hoja de cálculo, fijar una meta de ahorro a 6 meses y comparar opciones formales de cuentas de ahorro para jóvenes (CetesDirecto Niños).',
    cierreDetalle: 'Debate sobre la trampa de las compras a crédito impulsivas y tarjetas bancarias.',
    evaluacionCriterios: ['Estructuración técnica de presupuestos con balance equilibrado', 'Identificación de estrategias para eliminar gastos innecesarios', 'Toma de decisiones financieras informadas y responsables'],
    materiales: 'Calculadoras, hojas de cálculo, formatos de presupuesto mensual.',
    entregable: 'Presupuesto Mensual Personalizado y Plan de Ahorro con Metodología 50-30-20.'
  },
  {
    id: 'f6-hum-39',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 189,
    temaTitulo: 'Acondicionamiento físico funcional y calistenia con peso corporal',
    tituloProyecto: 'Fuerza Natural: Calistenia, Entrenamiento Funcional y Salud Articular',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Diseña y ejecuta un programa de calistenia y entrenamiento funcional utilizando el propio peso corporal (dominadas, flexiones, sentadillas profundas, fondos en paralelas) para fortalecer la postura y masa muscular.',
    detonadoras: ['¿Por qué la calistenia es una de las disciplinas más completas y accesibles al no requerir costosos gimnasios ni pesas?', '¿Cómo ejecutamos una flexión de pecho o sentadilla con alineación neutra de columna para proteger las articulaciones?'],
    inicioDetalle: 'Activación articular con movilidad de escápulas, cadera y tobillos.',
    desarrolloDetalle: 'Laboratorio de Calistenia y Fuerza Funcional: Practicar progresiones técnicas (ej. flexiones inclinadas en barras bajas para principiantes hasta flexiones estándar) organizadas en estaciones de entrenamiento por intervalos.',
    cierreDetalle: 'Rutina de estiramientos miofasciales y registro en la bitácora de fuerza.',
    evaluacionCriterios: ['Dominio técnico y biomecánico de los ejercicios de calistenia', 'Aplicación de principios de sobrecarga progresiva segura', 'Autonomía en el diseño de su rutina de entrenamiento físico'],
    materiales: 'Barras de calistenia del patio escolar o pasamanos, cronómetro, colchonetas.',
    entregable: 'Programa Personal de Calistenia y Entrenamiento Funcional con Progresiones Técnicas.'
  },
  {
    id: 'f6-hum-40',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología / Física / Artes',
    materiaFolder: 'Proyectos_Comunitarios',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 190,
    temaTitulo: 'Proyecto integrador comunitario: Ecotecnia de energía solar térmica para la escuela',
    tituloProyecto: 'Luz que Calienta: Diseño, Termofusión y Construcción de un Calentador Solar Escolar',
    ejes: ['Pensamiento Crítico', 'Vida Saludable', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Diseña, construye y evalúa un calentador solar de agua por efecto termosifón utilizando tubos de CPVC/PPR y botellas de PET recicladas, para abastecer de agua tibia a los lavabos escolares.',
    detonadoras: ['¿Cómo aprovecha el efecto termosifón la diferencia de densidad del agua caliente (que sube sola al termotanque) sin necesidad de bombas eléctricas?', '¿Cuánto gas y emisiones de $\\text{CO}_2$ ahorra un calentador solar casero al año?'],
    inicioDetalle: 'Demostración de convección térmica con agua caliente coloreada en un frasco sumergido.',
    desarrolloDetalle: 'Construcción del Colector Solar de PET: Cortar y ensamblar botellas de refresco pintadas de negro mate alrededor de tubos de CPVC conectados a un termotanque aislado, midiendo la temperatura del agua a las 12:00 hrs y a las 16:00 hrs.',
    cierreDetalle: 'Conexión a la red de agua escolar y presentación del balance de ahorro energético.',
    evaluacionCriterios: ['Integración interdisciplinaria de conceptos de termodinámica y procesos técnicos', 'Calidad en el ensamble hidráulico sin fugas de agua', 'Evaluación cuantitativa del rendimiento térmico y sustentabilidad'],
    materiales: 'Botellas de PET de 2L transparentes, tubos de CPVC de 1/2 pulgada, pintura negra mate, pegamento CPVC.',
    entregable: 'Calentador Solar Funcional Instalado en la Escuela y Memoria Técnica de Rendimiento Térmico.'
  },
  {
    id: 'f6-hum-41',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 191,
    temaTitulo: 'El ciclo de vida del producto y el ecodiseño',
    tituloProyecto: 'Diseñado para Durar: Ecodiseño, Desensamble Fácil y Reducción de Huella Ambiental',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Analiza el ciclo de vida de productos cotidianos (extracción, manufactura, transporte, uso y disposición) y aplica principios de ecodiseño para alargar su vida útil y facilitar el reciclaje.',
    detonadoras: ['¿Cómo podemos diseñar un producto pensando desde el primer día en cómo será desarmado y reciclado?', '¿Qué es el análisis "de la cuna a la tumba" (LCA)?'],
    inicioDetalle: 'Desensamble de un bolígrafo o juguete viejo clasificando sus partes.',
    desarrolloDetalle: 'Taller de Ecodiseño: Rediseñar el empaque de un producto comercial sustituyendo unicel y plásticos de un solo uso por cartón plegado biodegradable sin pegamentos tóxicos.',
    cierreDetalle: 'Exposición de prototipos de empaques sustentables.',
    evaluacionCriterios: ['Comprensión de las fases del ciclo de vida del producto', 'Aplicación de criterios de ecodiseño y reducción de materiales', 'Originalidad y funcionalidad del empaque biodegradable'],
    materiales: 'Cartón corrugado, tijeras, reglas, pegamentos vegetales.',
    entregable: 'Prototipo de Empaque Ecodiseñado y Matriz de Ciclo de Vida del Producto.'
  },
  {
    id: 'f6-hum-42',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 192,
    temaTitulo: 'Sistemas de captación pluvial y fontanería sustentable',
    tituloProyecto: 'Cosecha de Lluvia: Diseño de Filtro de Primeras Aguas y Almacenamiento Pluvial',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Diseña e instala un sistema de captación de agua de lluvia (SCALL) con separador de primeras lluvias (tlalocoque) para el riego de áreas verdes escolares.',
    detonadoras: ['¿Por qué es fundamental desviar los primeros 50 litros de lluvia que limpian el polvo de los techos antes de almacenar el agua limpia?', '¿Cómo calculamos cuántos litros podemos cosechar ($V = \\text{Área} \\times \\text{Precipitación} \\times 0.8$)?'],
    inicioDetalle: 'Cálculo del potencial de cosecha de lluvia en el techo de las aulas.',
    desarrolloDetalle: 'Taller de Fontanería Pluvial: Armar un separador de primeras lluvias con tubos de PVC de 4 pulgadas y válvula flotadora, conectándolo a canaletas y tanque de almacenamiento.',
    cierreDetalle: 'Prueba de flujo con manguera y activación del separador.',
    evaluacionCriterios: ['Cálculo volumétrico de captación pluvial', 'Correcta instalación de uniones de PVC y sellado hermético', 'Funcionalidad del separador de primeras lluvias'],
    materiales: 'Tubos de PVC de 4 y 2 pulgadas, codos, pegamento para PVC, pelota flotadora.',
    entregable: 'Separador de Primeras Lluvias Instalado y Manual de Mantenimiento Pluvial.'
  },
  {
    id: 'f6-hum-43',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tecnología',
    materiaFolder: 'Tecnologia',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 193,
    temaTitulo: 'Domótica básica y automatización del hogar con microcontroladores',
    tituloProyecto: 'Hogar Inteligente: Sensores de Gas, Alarma Antirrobo y Ahorro Energético con Domótica',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Construye y programa un prototipo domótico con microcontrolador (Arduino/ESP32) integrando sensores de gas MQ-2, sensor de movimiento PIR y relevador para corte automático.',
    detonadoras: ['¿Cómo puede la domótica prevenir explosiones por fugas de gas doméstico cortando el suministro automáticamente?', '¿Cómo programamos una alarma antirrobo con sensor infrarrojo y zumbador piezoeléctrico?'],
    inicioDetalle: 'Demostración de detección de gas de un encendedor cerca de un sensor MQ-2.',
    desarrolloDetalle: 'Laboratorio de Domótica Escolar: Conectar y calibrar en protoboard el sensor de gas MQ-2 y el sensor PIR, programando en C++/bloques la activación de una alarma acústica y el apagado de luces cuando no hay personas.',
    cierreDetalle: 'Montaje del circuito en una maqueta de vivienda inteligente.',
    evaluacionCriterios: ['Cableado correcto de entradas analógicas y salidas digitales', 'Programación lógica con umbrales de detección y temporizadores', 'Aplicación de la tecnología en la seguridad y el ahorro energético'],
    materiales: 'Arduino Uno, sensor de gas MQ-2, sensor PIR, buzzer, relé de 5V, LEDs.',
    entregable: 'Maqueta Domótica Funcional con Alarma de Gas y Sensor de Movimiento.'
  },
  {
    id: 'f6-hum-44',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 194,
    temaTitulo: 'Manejo del duelo, pérdidas afectivas y resiliencia emocional',
    tituloProyecto: 'Abrazar la Ausencia: Comprensión del Duelo, Expresión de Emociones y Redes de Cariño',
    ejes: ['Inclusión', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce las 5 etapas del duelo (Kübler-Ross: negación, ira, negociación, tristeza y aceptación) ante pérdidas familiares, de mascotas o cambios vitales, validando sus emociones y buscando apoyo.',
    detonadoras: ['¿Por qué llorar y expresar tristeza cuando perdemos a un ser querido es un proceso natural y saludable para sanar el corazón?', '¿Cómo acompañamos con respeto a un compañero que está viviendo un duelo sin decirle frases clichés que invaliden su dolor?'],
    inicioDetalle: 'Lectura del cuento "El Árbol de los Recuerdos" de Britta Teckentrup.',
    desarrolloDetalle: 'Taller del Cofre de la Memoria: Elaborar un objeto conmemorativo con cartas de agradecimiento y recuerdos positivos hacia seres queridos ausentes, identificando personas de confianza para desahogarse.',
    cierreDetalle: 'Círculo de escucha respetuosa y colocación de notas en el Árbol de la Gratitud.',
    evaluacionCriterios: ['Comprensión de las etapas y normalización del proceso de duelo', 'Expresión afectiva y artística de vivencias y recuerdos significativos', 'Demostración de empatía y solidaridad activa ante el dolor ajeno'],
    materiales: 'Cajas pequeñas para decorar, hojas de papel artesanal, notas adhesivas.',
    entregable: 'Cofre de los Recuerdos y Cartas de Gratitud y Sanación Emocional.'
  },
  {
    id: 'f6-hum-45',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 195,
    temaTitulo: 'Cuidado de la imagen corporal y prevención de trastornos alimentarios (TCA)',
    tituloProyecto: 'Espejo Real: Desmontando la Presión Estética, Redes Sociales y Prevención de Anorexia/Bulimia',
    ejes: ['Vida Saludable', 'Igualdad de Género', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Analiza críticamente los filtros digitales y la presión estética en redes sociales, reconociendo factores de riesgo de Trastornos de la Conducta Alimentaria (anorexia, bulimia, vigorexia) y cultivando la autoaceptación corporal.',
    detonadoras: ['¿Cómo los filtros de belleza y cuerpos retocados con Photoshop crean expectativas irreales que dañan la autoestima de los jóvenes?', '¿Cuáles son los síntomas de alerta de los TCA y por qué son enfermedades graves que requieren atención médica urgente?'],
    inicioDetalle: 'Comparación de fotos originales vs editadas con filtros de retoque facial y corporal.',
    desarrolloDetalle: 'Taller de Amor Propio y Diversidad Corporal: Redactar una carta de gratitud a nuestro cuerpo por todo lo que nos permite hacer (caminar, abrazar, reír, bailar) y diseñar carteles de desmitificación de la delgadez extrema.',
    cierreDetalle: 'Mural de Espejos Positivos con mensajes de autoaceptación incondicional.',
    evaluacionCriterios: ['Pensamiento crítico frente a cánones estéticos impuestos por la publicidad', 'Identificación de señales de riesgo de trastornos alimentarios', 'Promoción de la diversidad corporal y la salud integral'],
    materiales: 'Imágenes comparativas, espejos didácticos, cartulinas fluorescentes.',
    entregable: 'Campaña Escolar Ilustrada "Cuerpos Reales, Salud Integral: Sin Filtros".'
  },
  {
    id: 'f6-hum-46',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Tutoría / Educación Socioemocional',
    materiaFolder: 'Tutoria_Socioemocional',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 196,
    temaTitulo: 'Liderazgo positivo, trabajo en equipo y habilidades para el siglo XXI',
    tituloProyecto: 'Líderes que Inspiran: Liderazgo Servicial, Inteligencia Colectiva y Sinergia de Grupo',
    ejes: ['Inclusión', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Desarrolla habilidades de liderazgo servicial y trabajo en equipo (distribución equitativa de roles, delegación, retroalimentación constructiva y resolución ágil de desacuerdos) para coordinar proyectos comunitarios.',
    detonadoras: ['¿Qué diferencia a un jefe autoritario que da órdenes de un líder empático que escucha, sirve y potencia los talentos de su equipo?', '¿Qué es la SINERGIA (el todo es mayor que la suma de sus partes)?'],
    inicioDetalle: 'Reto de la Torre de Malvavisco y Espaguetis (Marshmallow Challenge) en equipos de 4.',
    desarrolloDetalle: 'Taller de Dinámicas de Alto Desempeño: Evaluar el rol asumido en el reto (coordinador, diseñador, ejecutor, mediador), analizar la matriz de roles de Belbin y planear una estrategia de mejora del clima grupal.',
    cierreDetalle: 'Compromiso de liderazgo positivo en las actividades de graduación escolar.',
    evaluacionCriterios: ['Demostración de actitudes de liderazgo empático y colaborativo', 'Capacidad de adaptación y resolución ágil de retos en equipo', 'Evaluación constructiva del desempeño propio y grupal'],
    materiales: 'Espaguetis crudos, malvaviscos, cinta adhesiva, cronómetros.',
    entregable: 'Diagnóstico de Roles de Equipo de Belbin y Decálogo del Liderazgo Servicial.'
  },
  {
    id: 'f6-hum-47',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 197,
    temaTitulo: 'Iniciación al Voleibol: saque, voleo, golpe bajo y rotaciones',
    tituloProyecto: 'Balón al Aire: Fundamentos Técnicos del Voleibol, Golpe Bajo, Voleo y Trabajo en Equipo',
    ejes: ['Vida Saludable', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Domina los fundamentos técnicos individuales (saque por abajo, voleo de dedos, golpe bajo o recepción) y colectivos (rotación en sentido horario y 3 toques reglamentarios) en el voleibol escolar.',
    detonadoras: ['¿Cómo colocamos los antebrazos juntos y flexionamos las rodillas para dirigir un pase suave y preciso en el golpe bajo?', '¿Por qué el voleibol es uno de los deportes más cooperativos donde nadie puede retener el balón ni tocarlo dos veces seguidas?'],
    inicioDetalle: 'Calentamiento de hombros y dedos con balón medicinal ligero y ejercicios de coordinación ojo-mano.',
    desarrolloDetalle: 'Circuito Técnico de Voleibol: Estación 1: Voleo de control contra pared a $2.5\\text{ m}$; Estación 2: Recepción de golpe bajo en parejas; Estación 3: Saque de seguridad por debajo de la red; Estación 4: Mini-partidos $3 \\times 3$ con 3 toques obligatorios.',
    cierreDetalle: 'Enfriamiento con estiramientos de tren superior y registro de pases logrados.',
    evaluacionCriterios: ['Ejecución técnica correcta del voleo, golpe bajo y saque', 'Aplicación de la regla de los tres toques y rotación de posiciones', 'Actitud de ánimo constante y apoyo a los compañeros de sexteto'],
    materiales: 'Balones de voleibol de tacto suave, red de voleibol o cuerda con listones, conos.',
    entregable: 'Registro de Desempeño Técnico en Voleibol y Ficha de Jugadas Colectivas.'
  },
  {
    id: 'f6-hum-48',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 198,
    temaTitulo: 'Iniciación al Baloncesto: drible, pase de pecho, tiro en suspensión y defensa',
    tituloProyecto: 'Encestando con Técnica: Drible, Pases, Tiro en Suspensión y Táctica Básica en Baloncesto',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Aplica fundamentos del baloncesto (drible con ambas manos con cambio de ritmo, pase de pecho/picado, tiro en suspensión con parábola y entrada a la canasta con doble paso) en situaciones de juego reducido $3 \\times 3$.',
    detonadoras: ['¿Cómo protegemos el balón botando con la mano más alejada del defensor (drible de protección)?', '¿Cuál es la mecánica correcta del tiro: Flexión de piernas, codo a $90^{\\circ}$, extensión y quiebre de muñeca ("mano de cisne")?'],
    inicioDetalle: 'Carrera continua botando balones alternando mano izquierda y derecha con conos de zigzag.',
    desarrolloDetalle: 'Estaciones de Habilidades de Baloncesto: Estación 1: Doble paso entrando por derecha e izquierda; Estación 2: Pase de pecho y picado en parejas a velocidad; Estación 3: Torneo de tiros libres; Estación 4: Torneo de tercias $3 \\times 3$ en media cancha.',
    cierreDetalle: 'Torneo relámpago de tiros de 3 puntos y vuelta a la calma.',
    evaluacionCriterios: ['Dominio del bote con ambas manos sin mirar fijamente el balón', 'Mecánica fluida en el tiro a canasta y entrada en doble paso', 'Juego colectivo con pases rápidos y desmarques activos'],
    materiales: 'Balones de baloncesto, canchas escolares con aros, conos, cronómetro.',
    entregable: 'Evaluación Técnica de Baloncesto y Bitácora del Torneo de Tercias $3 \\times 3$.'
  },
  {
    id: 'f6-hum-49',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'Educación Física',
    materiaFolder: 'Educacion_Fisica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 199,
    temaTitulo: 'Iniciación al Fútbol y Balonmano: control orientado, pase filtrado y repliegue defensivo',
    tituloProyecto: 'Estrategia de Gol: Control Orientado, Pase Filtrado, Paredes y Transiciones Rápidas',
    ejes: ['Vida Saludable', 'Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Perfecciona el control orientado, conducción con cambio de dirección, pases en profundidad y transiciones ataque-defensa en fútbol reducido y balonmano escolar mixto.',
    detonadoras: ['¿Cómo un buen control orientado con el empeine o la parte interna permite ganar un segundo crucial para rematar o pasar?', '¿Cómo cerramos los espacios en defensa mediante el repliegue y la basculación en bloque?'],
    inicioDetalle: 'Rondo o "Torito" de 4 atacantes contra 1 defensor a 2 toques máximos.',
    desarrolloDetalle: 'Circuito Táctico de Fútbol/Balonmano Mixto: Ejercicios de paredes $2 \\times 1$, triangulaciones rápidas y remates a portería con oposición de portero, culminando en un partido modificado $5 \\times 5$ mixto.',
    cierreDetalle: 'Análisis táctico en el círculo central y estiramientos musculares de piernas.',
    evaluacionCriterios: ['Precisión y velocidad en el control orientado y pase al espacio libre', 'Coordinación táctica en transiciones de ataque y repliegue defensivo', 'Juego limpio, respeto a los rivales y fomento del fútbol mixto'],
    materiales: 'Balones de fútbol y balonmano, porterías pequeñas, petos, silbatos.',
    entregable: 'Pizarra de Jugadas Tácticas de Fútbol/Balonmano y Evaluación Formativa de Desempeño.'
  },
  {
    id: 'f6-hum-50',
    campo: 'De lo Humano y lo Comunitario',
    campoTag: 'de_lo_humano_y_lo_comunitario',
    materia: 'De lo Humano / Interdisciplinaria',
    materiaFolder: 'Proyectos_Comunitarios',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 200,
    temaTitulo: 'Festival comunitario escolar de salud, tecnología y deporte',
    tituloProyecto: 'Comunidad en Movimiento: Gran Festival Escolar de Ecotecnias, Bienestar y Deporte Comunitario',
    ejes: ['Vida Saludable', 'Inclusión', 'Pensamiento Crítico', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (3º Secundaria) - Integra todos los aprendizajes del Campo De lo Humano y lo Comunitario para organizar y liderar un Festival Comunitario que combine exhibición de ecotecnias, talleres socioemocionales y circuito deportivo para toda la comunidad.',
    detonadoras: ['¿Cómo podemos involucrar a padres de familia, vecinos y estudiantes en una gran jornada de fiesta, salud y ciencia comunitaria?', '¿Qué impacto transformador deja en nuestra escuela un evento masivo organizado por los propios alumnos?'],
    inicioDetalle: 'Instalación del Comité Coordinador General de Alumnos de 3º Grado con asignación de comisiones.',
    desarrolloDetalle: 'Operación del Festival Comunitario en 3 Pabellones: Pabellón 1 (Tecnología y Ecotecnias: Muestra de deshidratadores, calentadores solares y robots); Pabellón 2 (Salud y Bienestar: Módulo de toma de presión, menú saludable y buzón emocional); Pabellón 3 (Deportes y Juegos Tradicionales: Torneos relámpago de Ultimate Frisbee y Pelota Purépecha).',
    cierreDetalle: 'Ceremonia de clausura comunitaria, entrega de reconocimientos y evaluación de impacto.',
    evaluacionCriterios: [
      'Integración armónica de Tecnología, Tutoría y Educación Física',
      'Liderazgo organizativo autónomo, logística impecable y trabajo colaborativo',
      'Impacto social positivo y participación activa de las familias en la escuela'
    ],
    materiales: 'Mesas, carpas, equipos deportivos, prototipos técnicos, lonas informativas.',
    entregable: 'Memoria Gráfica y Audiovisual del Festival Comunitario Escolar y Balance de Impacto.'
  }
];

