import { NodeMetadataF6 } from './fase6_data_lenguajes';

// 50 planeaciones únicas para SABERES Y PENSAMIENTO CIENTÍFICO en Secundaria (Fase 6)
export const saberesF6Data: NodeMetadataF6[] = [
  // --- MATEMÁTICAS 1º, 2º, 3º (15 planeaciones) ---
  {
    id: 'f6-sab-01',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 51,
    temaTitulo: 'Expresión de fracciones como decimales y de decimales como fracciones',
    tituloProyecto: 'El Muro Decimal: Fracciones Finitas, Periódicas Puras y Mixtas en el Comercio',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Usa diversas estrategias al convertir números fraccionarios a decimales y viceversa, distinguiendo decimales finitos, periódicos puros y periódicos mixtos mediante algoritmos algebraicos.',
    detonadoras: [
      '¿Por qué al dividir $1 \\div 3$ obtenemos $0.333...$ infinito mientras que $1 \\div 4$ da $0.25$ exacto?',
      '¿Cómo transformamos un número decimal periódico como $0.\\overline{7}$ o $1.2\\overline{45}$ en su fracción irreducible exacta usando ecuaciones?',
      '¿Cómo ayuda el redondeo y truncamiento en las transacciones comerciales diarias?'
    ],
    inicioDetalle: 'Desafío de la calculadora: Dividir fracciones unitarias y clasificar los patrones de sus cifras decimales.',
    desarrolloDetalle: 'Taller de Algoritmos de Conversión: Resolver conversiones algebraicas multiplicando por potencias de 10 para eliminar periodos decimales y simplificar fracciones por MCD.',
    cierreDetalle: 'Rally de velocidad mental y resolución de problemas financieros reales.',
    evaluacionCriterios: [
      'Conversión precisa de fracciones a decimales finitos y periódicos',
      'Aplicación del método algebraico para convertir decimales periódicos a fracciones',
      'Simplificación de fracciones a su forma irreducible'
    ],
    materiales: 'Calculadoras científicas, hojas cuadriculadas, fichas de dominó fraccionario.',
    entregable: 'Problemario Resuelto y Fichero Técnico "Del Decimal Periódico a la Fracción Exacta".'
  },
  {
    id: 'f6-sab-02',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 52,
    temaTitulo: 'Extensión de los números a positivos y negativos y su orden en la recta',
    tituloProyecto: 'Bajo Cero y en las Alturas: Números con Signo, Valor Absoluto y Densidad Numérica',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce la necesidad de los números negativos a partir de situaciones con el cero como referencia (temperaturas, finanzas, profundidades) y analiza la propiedad de densidad.',
    detonadoras: [
      '¿Por qué $-15^{\\circ}\\text{C}$ es más frío que $-3^{\\circ}\\text{C}$ a pesar de que $15 > 3$?',
      '¿Qué significa el valor absoluto $|x|$ como distancia al origen sin importar la dirección?',
      '¿Por qué entre dos números racionales cualesquiera siempre existe una infinidad de números (densidad)?'
    ],
    inicioDetalle: 'Simulación de ascensor en rascacielos con sótanos y altitudes marinas.',
    desarrolloDetalle: 'Laboratorio de la Recta Numérica: Ubicar números fraccionarios y decimales con signo, calcular valores absolutos y encontrar puntos medios fraccionarios.',
    cierreDetalle: 'Juego de mesa "Desafío Polar": Avanzar y retroceder con dados de enteros con signo.',
    evaluacionCriterios: [
      'Ubicación y ordenamiento riguroso de números con signo en la recta',
      'Comprensión del valor absoluto y opuesto de un número',
      'Demostración de la propiedad de densidad numérica entre dos racionales'
    ],
    materiales: 'Cintas métricas graduadas, dados bicolores, tarjetas numéricas.',
    entregable: 'Bitácora Gráfica de la Recta Numérica y Resolución de Casos Financieros y Térmicos.'
  },
  {
    id: 'f6-sab-03',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 53,
    temaTitulo: 'Jerarquía de operaciones y signos de agrupación',
    tituloProyecto: 'El Orden del Cálculo: Jerarquía PEMDAS, Paréntesis y Operaciones Combinadas',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Identifica y aplica la jerarquía de operaciones y símbolos de agrupación (paréntesis, corchetes, llaves) al realizar cálculos con enteros, fracciones y decimales.',
    detonadoras: [
      '¿Por qué $5 + 3 \\times 2$ no es igual a $16$ sino a $11$?',
      '¿Cuál es el orden estricto: Paréntesis, Exponentes, Multiplicación/División, Adición/Sustracción?',
      '¿Cómo evitan los paréntesis ambigüedades en programación y finanzas?'
    ],
    inicioDetalle: 'Reto viral de redes sociales de operaciones matemáticas ambiguas.',
    desarrolloDetalle: 'Taller de Jerarquía de Operaciones: Resolver expresiones anidadas con corchetes y llaves paso a paso, justificando cada simplificación.',
    cierreDetalle: 'Torneo de Criptogramas Numéricos en parejas.',
    evaluacionCriterios: [
      'Aplicación estricta de la jerarquía operacional',
      'Manejo correcto de signos de agrupación anidados',
      'Cálculo mental y exactitud en operaciones combinadas'
    ],
    materiales: 'Pizarrones individuales, tarjetas de desafíos algebraicos.',
    entregable: 'Cuadernillo de Retos Aritméticos "Cero Errores: Dominio de la Jerarquía de Operaciones".'
  },
  {
    id: 'f6-sab-04',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 54,
    temaTitulo: 'Leyes de los exponentes y notación científica',
    tituloProyecto: 'De los Átomos a las Galaxias: Potenciación, Raíz Cuadrada y Notación Científica',
    ejes: ['Pensamiento Crítico', 'Apropiación de las Culturas'],
    pda: 'Fase 6 (2º Secundaria) - Identifica y usa las propiedades de los exponentes ($a^m \\cdot a^n = a^{m+n}$, $(a^m)^n = a^{mn}$, $a^{-n} = 1/a^n$) y la notación científica con cantidades astronómicas y microscópicas.',
    detonadoras: [
      '¿Cómo escribimos la masa de la Tierra ($5.97 \\times 10^{24}\\text{ kg}$) o el tamaño de un virus ($1.2 \\times 10^{-7}\\text{ m}$) sin llenar páginas de ceros?',
      '¿Por qué cualquier número elevado a la potencia cero es igual a 1 ($a^0 = 1$)?',
      '¿Cómo se multiplican y dividen potencias con la misma base?'
    ],
    inicioDetalle: 'Visualización del video interactivo "Powers of Ten" (Escala del Universo).',
    desarrolloDetalle: 'Demostración de las 7 leyes de los exponentes con álgebra simbólica y resolución de operaciones combinadas en notación científica.',
    cierreDetalle: 'Rally astronómico y biológico calculando distancias interplanetarias y masas moleculares.',
    evaluacionCriterios: [
      'Aplicación correcta de leyes de los exponentes y exponentes negativos',
      'Conversión fluida entre notación estándar y notación científica',
      'Operaciones de producto y cociente en notación científica'
    ],
    materiales: 'Calculadoras científicas, tablas astronómicas, hojas de trabajo.',
    entregable: 'Problemario de Notación Científica y Leyes de los Exponentes "Escalas del Cosmos".'
  },
  {
    id: 'f6-sab-05',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 55,
    temaTitulo: 'Sistemas de dos ecuaciones lineales con dos incógnitas ($2 \\times 2$)',
    tituloProyecto: 'El Cruce de Caminos: Métodos Gráfico, Sustitución, Igualación y Reducción',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Modela y soluciona sistemas de dos ecuaciones lineales con dos incógnitas por métodos algebraicos (suma y resta, sustitución, igualación) y gráfico para dar respuesta a problemas reales.',
    detonadoras: [
      '¿Cómo modelamos algebraicamente un problema de compra donde conocemos el total de artículos y el costo total de dos productos distintos?',
      '¿Qué significa geométricamente la solución de un sistema como el punto de intersección $(x, y)$ de dos rectas?',
      '¿Cuándo un sistema no tiene solución (rectas paralelas) o tiene infinitas soluciones (rectas coincidentes)?'
    ],
    inicioDetalle: 'Planteamiento de un acertijo de compra de boletos de cine para adultos y niños.',
    desarrolloDetalle: 'Laboratorio de Métodos Algebraicos: Resolver el mismo sistema mediante el Método Gráfico (en GeoGebra/papel milimétrico), Método de Reducción (Suma y Resta) y Sustitución.',
    cierreDetalle: 'Comparación de eficiencia de métodos y resolución de problemas contextualizados.',
    evaluacionCriterios: [
      'Traducción de enunciados verbales a sistemas de ecuaciones lineales $2 \\times 2$',
      'Dominio procedimental de al menos 2 métodos algebraicos y el método gráfico',
      'Verificación de la solución en las ecuaciones originales'
    ],
    materiales: 'Papel milimétrico, reglas, calculadora, GeoGebra en tabletas.',
    entregable: 'Dossier Comparativo de Métodos de Solución de Sistemas $2 \\times 2$ con Gráficas.'
  },
  {
    id: 'f6-sab-06',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 56,
    temaTitulo: 'Ecuaciones cuadráticas completas e incompletas ($Ax^2 + Bx + C = 0$)',
    tituloProyecto: 'La Parábola Perfecta: Factorización, Fórmula General y el Discriminante',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Resuelve ecuaciones de la forma $Ax^2 + Bx + C = 0$ por factorización y fórmula general, interpretando el discriminante ($b^2 - 4ac$) y modelando trayectorias de tiro parabólico.',
    detonadoras: [
      '¿Por qué una ecuación cuadrática tiene hasta dos soluciones reales?',
      '¿Qué nos indica el signo del discriminante $\\Delta = b^2 - 4ac$ sobre la naturaleza de las raíces?',
      '¿Cómo describe una función cuadrática la trayectoria de un proyectil o el área máxima de un terreno?'
    ],
    inicioDetalle: 'Lanzamiento de una pelota y registro de la curva parabólica que describe.',
    desarrolloDetalle: 'Taller de Resolución Cuadrática: Factorización de trinomios cuadrados perfectos y de la forma $x^2+bx+c$, deducción de la Fórmula General y cálculo del vértice de la parábola.',
    cierreDetalle: 'Modelación de problemas de optimización de áreas y trayectorias físicas.',
    evaluacionCriterios: [
      'Dominio de la factorización y de la fórmula general cuadrática',
      'Interpretación correcta del discriminante en la existencia de soluciones',
      'Modelación matemática de problemas de áreas y trayectorias'
    ],
    materiales: 'Calculadoras, hojas milimétricas, simulador de tiro parabólico.',
    entregable: 'Guía Maestra de Ecuaciones Cuadráticas: Métodos, Factorización y Modelación Real.'
  },
  {
    id: 'f6-sab-07',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 57,
    temaTitulo: 'El Teorema de Pitágoras y sus aplicaciones trigonométricas',
    tituloProyecto: 'La Huella de Samos: Demostraciones Geométricas del Teorema de Pitágoras y Razones Trigonométricas',
    ejes: ['Pensamiento Crítico', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (3º Secundaria) - Formula, justifica y usa el teorema de Pitágoras ($a^2 + b^2 = c^2$) y las razones trigonométricas directas (seno, coseno, tangente) al resolver problemas de medición indirecta.',
    detonadoras: [
      '¿Cómo calculaban los agrimensores egipcios ángulos rectos perfectos con una cuerda de 12 nudos (terna 3-4-5)?',
      '¿Cómo medimos la altura de un árbol o poste sin subirnos a él usando la sombra y la tangente del ángulo?',
      '¿Por qué el Teorema de Pitágoras solo es válido en triángulos rectángulos?'
    ],
    inicioDetalle: 'Demostración visual con agua y cuadrados de acrílico del Teorema de Pitágoras.',
    desarrolloDetalle: 'Laboratorio de Medición Indirecta: Construir un goniómetro escolar (inclinómetro), medir ángulos de elevación hacia edificios escolares y calcular alturas usando $\\tan(\\theta)$ y el Teorema de Pitágoras.',
    cierreDetalle: 'Presentación de mediciones topográficas escolares y análisis de margen de error.',
    evaluacionCriterios: [
      'Demostración geométrica y algebraica del Teorema de Pitágoras',
      'Cálculo preciso de catetos e hipotenusa en contextos reales',
      'Aplicación de razones trigonométricas directas en medición indirecta'
    ],
    materiales: 'Transportadores, popotes, plomadas (hilo y tuerca), cinta métrica, tablas trigonométricas.',
    entregable: 'Reporte Topográfico Escolar con Goniómetro y Aplicación de Pitágoras y Trigonometría.'
  },
  {
    id: 'f6-sab-08',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 58,
    temaTitulo: 'Medidas de tendencia central y de dispersión (Rango y Desviación Media)',
    tituloProyecto: 'El Pulso Estadístico: Media, Mediana, Moda, Rango y Desviación Media en Decisiones Comunitarias',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Usa e interpreta las medidas de tendencia central (moda, media aritmética y mediana) y de dispersión (rango y desviación media) de un conjunto de datos, justificando decisiones con base en ellas.',
    detonadoras: [
      '¿Por qué la media aritmética puede ser engañosa si existen datos atípicos extremos?',
      '¿Qué nos indica la Desviación Media ($DM = \\frac{\\sum |x_i - \\bar{x}|}{n}$) sobre la consistencia y variabilidad de un grupo?',
      '¿Cómo usamos la estadística para analizar el promedio de bateo o la confiabilidad de un servicio público?'
    ],
    inicioDetalle: 'Comparación de sueldos de dos empresas con el mismo promedio pero diferente dispersión.',
    desarrolloDetalle: 'Taller de Análisis Estadístico: Recopilar datos de estatura y horas de sueño del grupo, calcular media, mediana, moda, rango y desviación media, y graficar histogramas.',
    cierreDetalle: 'Debate sobre la interpretación ética y crítica de estadísticas en noticias.',
    evaluacionCriterios: [
      'Cálculo riguroso de medidas de tendencia central y desviación media',
      'Interpretación del significado de la dispersión de datos',
      'Toma de decisiones fundamentada en evidencia estadística'
    ],
    materiales: 'Hojas de cálculo, calculadoras, hojas de registro de encuestas.',
    entregable: 'Informe Estadístico Completo con Tablas de Frecuencia, Gráficas y Desviación Media.'
  },
  {
    id: 'f6-sab-09',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 59,
    temaTitulo: 'Probabilidad de eventos complementarios, mutuamente excluyentes e independientes',
    tituloProyecto: 'El Casino Matemático: Reglas de la Suma y del Producto en Juegos de Azar Justos',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Resuelve problemas calculando la probabilidad de ocurrencia de dos eventos mutuamente excluyentes (regla de la suma) e independientes (regla del producto), analizando la noción de juegos justos.',
    detonadoras: [
      '¿Cuál es la probabilidad de obtener dos águilas consecutivas al lanzar dos monedas al aire ($P(A \\cap B) = P(A) \\cdot P(B)$)?',
      '¿Qué diferencia a los eventos mutuamente excluyentes ($P(A \\cup B) = P(A) + P(B)$) de los eventos no excluyentes?',
      '¿Por qué a largo plazo en los casinos "la casa siempre gana" matemáticamente?'
    ],
    inicioDetalle: 'Experimento con ruletas y dados: Registro de 100 lanzamientos para comparar probabilidad frecuencial vs teórica.',
    desarrolloDetalle: 'Laboratorio de Probabilidad: Diseñar árboles de probabilidad, calcular probabilidades de eventos compuestos y evaluar las reglas de un juego de feria escolar para que sea justo.',
    cierreDetalle: 'Feria de Juegos de Azar Justos en el aula con análisis probabilístico.',
    evaluacionCriterios: [
      'Aplicación precisa de la regla de la suma y regla del producto',
      'Construcción y análisis de diagramas de árbol y tablas de contingencia',
      'Evaluación crítica de la equiprobabilidad y condiciones de juegos justos'
    ],
    materiales: 'Dados, monedas, barajas, ruletas graduadas, fichas.',
    entregable: 'Guía de Probabilidad Compuesta y Diseño de Juego de Azar Matemáticamente Justo.'
  },

  // --- BIOLOGÍA 1º (12 planeaciones) ---
  {
    id: 'f6-sab-10',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 60,
    temaTitulo: 'Funcionamiento del cuerpo humano: sistemas nervioso y endocrino',
    tituloProyecto: 'La Red de Mando: Neuronas, Sinapsis, Hormonas y el Control Integral del Cuerpo',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Explica la participación de los sistemas nervioso y endocrino en la coordinación de las funciones del cuerpo humano, reconociendo el papel de neurotransmisores y hormonas en la maduración sexual y los efectos de sustancias adictivas.',
    detonadoras: [
      '¿Cómo viaja un impulso electroquímico por las neuronas a más de $300\\text{ km/h}$ para retirar la mano del fuego en un reflejo?',
      '¿Cómo regulan la hipófisis, tiroides y gónadas los cambios físicos y emocionales en la pubertad?',
      '¿Cómo alteran las drogas y el alcohol la liberación de dopamina y serotonina en la sinapsis cerebral?'
    ],
    inicioDetalle: 'Medición del tiempo de reacción motriz atrapando una regla en caída libre.',
    desarrolloDetalle: 'Modelado de la Sinapsis Neuronal: Construir con plastilina y cables un modelo de neurona con axón, dendritas y botones sinápticos, ilustrando el flujo de neurotransmisores y el eje hormonal hipotálamo-hipófisis.',
    cierreDetalle: 'Debate sobre los daños neurológicos del consumo de sustancias y elaboración de conclusiones.',
    evaluacionCriterios: [
      'Explicación científica de la transmisión sináptica y comunicación neuroendocrina',
      'Identificación de glándulas endocrinas y hormonas clave en la adolescencia',
      'Argumentación sólida sobre la prevención de adicciones y protección cerebral'
    ],
    materiales: 'Modelos anatómicos, plastilina, láminas de neuronas, cronómetro.',
    entregable: 'Modelo Tridimensional de Neurona y Sinapsis con Cuadro Comparativo Neuroendocrino.'
  },
  {
    id: 'f6-sab-11',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 61,
    temaTitulo: 'Salud sexual y reproductiva: prevención de ITS y métodos anticonceptivos',
    tituloProyecto: 'Decisiones Conscientes: Métodos Anticonceptivos, Doble Protección y Proyecto de Vida',
    ejes: ['Vida Saludable', 'Igualdad de Género', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Compara la efectividad de los métodos anticonceptivos (de barrera, hormonales, intrauterinos y definitivos), valorando la doble protección del condón contra ITS y embarazo adolescente.',
    detonadoras: [
      '¿Qué significa la DOBLE PROTECCIÓN (prevenir simultáneamente un embarazo no planeado y una Infección de Transmisión Sexual)?',
      '¿Cómo operan los métodos anticonceptivos hormonales en el ciclo menstrual ovulatorio?',
      '¿Por qué la responsabilidad en la salud sexual debe ser compartida al 100% entre hombres y mujeres sin estereotipos?'
    ],
    inicioDetalle: 'Dinámica de Mitos y Realidades sobre la sexualidad y métodos anticonceptivos.',
    desarrolloDetalle: 'Taller de Clasificación de Métodos Anticonceptivos: Analizar fichas técnicas de efectividad (Índice de Pearl) de métodos de barrera, hormonales, DIU y de emergencia, practicando la colocación correcta del condón masculino y femenino en simuladores.',
    cierreDetalle: 'Elaboración de una Guía de Servicios Amigables de Salud Sexual para adolescentes.',
    evaluacionCriterios: [
      'Comparación científica de mecanismos de acción y efectividad de anticonceptivos',
      'Reconocimiento del condón como único método de prevención de ITS (VIH, VPH)',
      'Enfoque de derechos sexuales, consentimiento informado y equidad de género'
    ],
    materiales: 'Muestrario didáctico de métodos anticonceptivos, simuladores anatómicos, rotafolios.',
    entregable: 'Guía Visual de Anticoncepción y Doble Protección "Mi Proyecto, Mi Decisión Informada".'
  },
  {
    id: 'f6-sab-12',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 62,
    temaTitulo: 'La biodiversidad como expresión del cambio de los seres vivos en el tiempo (Evolución)',
    tituloProyecto: 'El Viaje del Beagle: Selección Natural, Darwin, Wallace y Adaptaciones Evolutivas',
    ejes: ['Pensamiento Crítico', 'Interculturalidad Crítica'],
    pda: 'Fase 6 (1º Secundaria) - Indaga las principales aportaciones de Darwin y Wallace sobre la selección natural, analiza el registro fósil y explica adaptaciones morfológicas, fisiológicas y etológicas.',
    detonadoras: [
      '¿Cómo la variación genética y la presión ambiental hacen que los individuos mejor adaptados sobrevivan y dejen más descendencia?',
      '¿Qué nos enseñan los pinzones de las Islas Galápagos sobre la radiación adaptativa?',
      '¿Cómo demuestran los fósiles y la homología anatómica el ancestro común de los seres vivos?'
    ],
    inicioDetalle: 'Juego de simulación de picos de aves: Recolectar diferentes semillas usando pinzas, cucharas y palillos.',
    desarrolloDetalle: 'Taller de Evidencias Evolutivas: Comparar esqueletos homólogos de extremidades de mamíferos (humano, ballena, murciélago), analizar estratos fósiles y formular hipótesis sobre especiación.',
    cierreDetalle: 'Línea del tiempo del pensamiento evolutivo desde Lamarck hasta la Síntesis Moderna.',
    evaluacionCriterios: [
      'Comprensión del mecanismo de selección natural y adaptación al medio',
      'Identificación de evidencias evolutivas (fósiles, anatomía comparada, biogeografía)',
      'Reconocimiento de la ciencia como una construcción colectiva en constante cambio'
    ],
    materiales: 'Réplicas de fósiles o imágenes, pinzas de cocina, semillas variadas, esquemas anatómicos.',
    entregable: 'Infografía Científica "El Árbol de la Vida: Selección Natural y Evidencias de la Evolución".'
  },
  {
    id: 'f6-sab-13',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 63,
    temaTitulo: 'Importancia del microscopio para el conocimiento celular',
    tituloProyecto: 'El Mundo Invisible: De Leeuwenhoek al Microscopio Electrónico y la Teoría Celular',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Compara cómo han cambiado las observaciones microscópicas desde Hooke hasta la microscopía electrónica, describe organelos celulares y contrasta células procariotas y eucariotas.',
    detonadoras: [
      '¿Cómo el invento de Robert Hooke en 1665 al observar una laminilla de corcho revolucionó la medicina para siempre?',
      '¿Cuál es la función vital de la membrana plasmática, mitocondrias, cloroplastos y núcleo?',
      '¿Por qué las bacterias son procariotas y nuestras células son eucariotas?'
    ],
    inicioDetalle: 'Observación de una gota de agua estancada o de charco bajo el microscopio óptico.',
    desarrolloDetalle: 'Práctica de Laboratorio de Célula Vegetal y Animal: Preparar muestras de epidermis de cebolla con azul de metileno y mucosa bucal, enfocar a 10x, 40x y 100x y dibujar las estructuras observadas.',
    cierreDetalle: 'Construcción del cuadro comparativo entre célula animal y vegetal con funciones de organelos.',
    evaluacionCriterios: [
      'Manejo técnico correcto del microscopio óptico escolar (enfoque, luz, diafragma)',
      'Identificación y dibujo preciso de estructuras celulares observables',
      'Comprensión de los postulados de la Teoría Celular'
    ],
    materiales: 'Microscopios ópticos, portaobjetos, cubreobjetos, azul de metileno, cebolla, goteros.',
    entregable: 'Reporte de Práctica de Microscopía con Dibujos Científicos Rotulados a Escala.'
  },

  // --- FÍSICA 2º (12 planeaciones) ---
  {
    id: 'f6-sab-14',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 64,
    temaTitulo: 'Interacciones en fenómenos relacionados con la fuerza y el movimiento (Leyes de Newton)',
    tituloProyecto: 'Leyes del Cosmos: Inercia, Masa, Fuerza ($F=ma$) y Acción-Reacción en la Vida Cotidiana',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Experimenta e interpreta las interacciones de fuerza y movimiento mediante las Tres Leyes de Newton, identificando fuerzas en equilibrio, fricción y aceleración en actividades cotidianas.',
    detonadoras: [
      '¿Por qué los pasajeros de un autobús se van hacia adelante cuando el conductor frena bruscamente (Ley de Inercia)?',
      '¿Cómo se relacionan la fuerza neta, la masa y la aceleración ($F = m \\cdot a$) en el despegue de un cohete?',
      '¿Por qué al empujar una pared sentimos una fuerza exactamente igual pero en sentido opuesto (Acción y Reacción)?'
    ],
    inicioDetalle: 'Experimento del mantel y la vajilla: Tirar rápidamente de un mantel sin mover los vasos (inercia).',
    desarrolloDetalle: 'Laboratorio Dinámico de Fuerzas: Utilizar dinamómetros, carritos de fricción y masas calibradas para medir la aceleración con respecto a fuerzas variables y comprobar la 2ª Ley de Newton.',
    cierreDetalle: 'Construcción y lanzamiento de un cohete impulsado por agua y aire (3ª Ley de Newton).',
    evaluacionCriterios: [
      'Explicación y demostración experimental de las tres Leyes de Newton',
      'Cálculo algebraico correcto usando la fórmula $F=ma$ con unidades del SI (Newtons)',
      'Elaboración de diagramas de cuerpo libre con vectores de fuerza'
    ],
    materiales: 'Dinamómetros, carritos de baja fricción, cronómetros, botellas de PET para cohetes.',
    entregable: 'Reporte Experimental de Dinámica Newtoniana con Diagramas de Vectores de Fuerza.'
  },
  {
    id: 'f6-sab-15',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 65,
    temaTitulo: 'Principios de Pascal y de Arquímedes en fluidos',
    tituloProyecto: 'El Poder de los Fluidos: Prensa Hidráulica de Pascal y Flotabilidad de Arquímedes',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Experimenta e interpreta las interacciones de fuerza y presión en fluidos (Principio de Pascal: $\\frac{F_1}{A_1} = \\frac{F_2}{A_2}$ y Principio de Arquímedes: Empuje hidrostático $E = \\rho g V$).',
    detonadoras: [
      '¿Cómo puede un niño levantar un automóvil pesado utilizando una prensa hidráulica con jeringas de distinto diámetro?',
      '¿Por qué un barco de acero de miles de toneladas flota en el mar mientras que una pequeña canica de vidrio se hunde?',
      '¿Qué relación existe entre la densidad del fluido y la fuerza de empuje?'
    ],
    inicioDetalle: 'Demostración del "Ludión" o Buzo de Descartes dentro de una botella de plástico con agua.',
    desarrolloDetalle: 'Construcción de Brazo Robótico Hidráulico con Jeringas: En equipos, armar un mecanismo articulado accionado por presión de agua demostrando el Principio de Pascal y calcular la ventaja mecánica.',
    cierreDetalle: 'Cálculo del empuje hidrostático sumergiendo cuerpos en probetas y midiendo volumen desalojado.',
    evaluacionCriterios: [
      'Comprensión física del Principio de Pascal y transmisión uniforme de la presión',
      'Demostración del Principio de Arquímedes y equilibrio de flotabilidad',
      'Construcción y funcionamiento del prototipo hidráulico'
    ],
    materiales: 'Jeringas de 5ml, 10ml y 20ml, mangueras de acuario, cartón, dinamómetros, probetas.',
    entregable: 'Brazo Robótico Hidráulico Funcional y Memoria de Cálculo de Presión y Empuje.'
  },
  {
    id: 'f6-sab-16',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 66,
    temaTitulo: 'Conservación de la energía mecánica y fuentes renovables',
    tituloProyecto: 'La Montaña Rusa de la Energía: Energía Cinética ($E_c$), Potencial ($E_p$) y Termodinámica',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Analiza las características de la energía cinética ($E_c = \\frac{1}{2}mv^2$) y potencial ($E_p = mgh$), describe casos de conservación y diseña prototipos de energía solar y eólica.',
    detonadoras: [
      '¿Por qué en lo más alto de una montaña rusa la velocidad es mínima pero la energía potencial es máxima?',
      '¿Por qué la energía no se crea ni se destruye, solo se transforma (Ley de Conservación)?',
      '¿Cómo transformamos la radiación solar y la energía cinética del viento en electricidad limpia?'
    ],
    inicioDetalle: 'Simulación digital de pista de patinaje (PhET Interactive Simulations - Skate Park).',
    desarrolloDetalle: 'Diseño de Maqueta de Montaña Rusa y Horno Solar: Construir una pista de canicas calculando la velocidad teórica en cada valle y diseñar una caja térmica solar con papel aluminio y vidrio.',
    cierreDetalle: 'Medición de temperatura alcanzada en el horno solar y cálculo de eficiencia térmica.',
    evaluacionCriterios: [
      'Cálculo algebraico de energía potencial, cinética y mecánica total',
      'Demostración de la conservación y degradación de la energía mecánica',
      'Diseño sustentable del prototipo de aprovechamiento de energía solar'
    ],
    materiales: 'Mangueras transparentes, canicas, cajas de pizza, papel aluminio, termómetros.',
    entregable: 'Horno Solar Construido y Análisis Gráfico de Conservación de Energía Mecánica.'
  },

  // --- QUÍMICA 3º (11 planeaciones) ---
  {
    id: 'f6-sab-17',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 67,
    temaTitulo: 'Propiedades extensivas e intensivas de la materia',
    tituloProyecto: 'La Huella de la Materia: Masa, Volumen, Densidad y Puntos de Fusión/Ebullición',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Formula hipótesis para diferenciar propiedades extensivas (dependen de la cantidad de materia: masa, volumen) e intensivas (características de la sustancia: densidad, solubilidad, punto de ebullición).',
    detonadoras: [
      '¿Por qué $1\\text{ litro}$ de agua y $100\\text{ litros}$ de agua hierven exactamente a la misma temperatura ($100^{\\circ}\\text{C}$)?',
      '¿Por qué el aceite flota sobre el agua aunque tengamos un galón de aceite y un vaso de agua (densidad $\\rho = m/V$)?',
      '¿Cómo nos permiten las propiedades intensivas identificar una sustancia desconocida en criminalística o minería?'
    ],
    inicioDetalle: 'Desafío de las dos botellas idénticas: Una con agua destilada y otra con alcohol.',
    desarrolloDetalle: 'Laboratorio de Determinación de Densidad: Medir con balanza y probeta la masa y volumen de diferentes metales sólidos y líquidos, graficar $m$ vs $V$ y calcular la pendiente (densidad).',
    cierreDetalle: 'Construcción de una columna de 5 densidades con líquidos de colores (miel, jabón, agua, aceite, alcohol).',
    evaluacionCriterios: [
      'Diferenciación conceptual y experimental entre propiedades extensivas e intensivas',
      'Uso adecuado de instrumentos de medición (balanza granataria, probeta, termómetro)',
      'Cálculo de densidad con unidades del SI ($\\text{g/cm}^3$, $\\text{kg/m}^3$)'
    ],
    materiales: 'Balanza granataria, probetas, termómetros, muestras metálicas, líquidos de uso común.',
    entregable: 'Reporte de Laboratorio "Determinación Experimental de Densidad y Columna de Líquidos".'
  },
  {
    id: 'f6-sab-18',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 68,
    temaTitulo: 'La Tabla Periódica: modelos atómicos de Bohr y estructuras de Lewis',
    tituloProyecto: 'El Código de los Elementos: Configuración Electrónica, Grupos, Periodos y Enlaces Químicos',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Construye modelos atómicos de Bohr y diagramas de Lewis para representar electrones de valencia y justificar la ubicación de los elementos en grupos y periodos de la Tabla Periódica.',
    detonadoras: [
      '¿Cómo descubrió Dmitri Mendeléyev el orden periódico de los elementos prediciendo propiedades de elementos aún no descubiertos?',
      '¿Por qué los gases nobles no reaccionan mientras que los metales alcalinos reaccionan violentamente con el agua?',
      '¿Cómo se cumple la Regla del Octeto al formarse enlaces químicos entre átomos?'
    ],
    inicioDetalle: 'Demostración de espectros de emisión a la flama con sales de sodio (amarillo), cobre (verde) y estroncio (rojo).',
    desarrolloDetalle: 'Taller de Estructuras Atómicas: Dibujar modelos de Bohr y diagramas de Lewis para los primeros 20 elementos químicos, identificando electrones de valencia y prediciendo fórmulas de compuestos iónicos y covalentes.',
    cierreDetalle: 'Juego de mesa "Batalla Periódica": Formar compuestos estables completando octetos.',
    evaluacionCriterios: [
      'Construcción correcta de modelos de Bohr con órbitas electrónicas ($2, 8, 8, 18$)',
      'Representación precisa de estructuras de Lewis y electrones de valencia',
      'Interpretación de tendencias periódicas (radio atómico y electronegatividad)'
    ],
    materiales: 'Sales químicas para flama, cartulinas de Tabla Periódica, fichas de electrones.',
    entregable: 'Álbum Atómico Ilustrado "Los Primeros 20 Elementos: Modelos de Bohr y Lewis".'
  },
  {
    id: 'f6-sab-19',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 69,
    temaTitulo: 'Reacciones químicas: Ley de conservación de la materia y balanceo de ecuaciones',
    tituloProyecto: 'Alquimia Moderna: Manifestaciones Químicas, Ecuaciones y Balanceo por Tanteo',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Reconoce distintas reacciones químicas por sus manifestaciones (cambio de color, precipitado, efervescencia, emisión de luz o calor) y balancea ecuaciones químicas aplicando la Ley de Lavoisier.',
    detonadoras: [
      '¿Por qué en una reacción química en sistema cerrado la masa total de los reactivos es exactamente igual a la masa de los productos?',
      '¿Cómo interpretamos los coeficientes estequiométricos y subíndices en una fórmula como $2\\text{H}_2 + \\text{O}_2 \\rightarrow 2\\text{H}_2\\text{O}$?',
      '¿Cuál es la diferencia entre un cambio físico (derretir hielo) y un cambio químico (quemar madera)?'
    ],
    inicioDetalle: 'Reacción de vinagre con bicarbonato de sodio en botella cerrada sobre una balanza (demostración de Lavoisier).',
    desarrolloDetalle: 'Laboratorio de Reacciones Químicas: Experimentar con 4 tipos de reacciones (síntesis, descomposición, desplazamiento simple y doble), escribir las ecuaciones químicas y balancearlas por el método de tanteo.',
    cierreDetalle: 'Resolución de problemas de balanceo estequiométrico en equipos.',
    evaluacionCriterios: [
      'Identificación experimental de evidencias de transformación química',
      'Aplicación rigurosa de la Ley de Conservación de la Materia',
      'Dominio del balanceo de ecuaciones químicas por el método de tanteo'
    ],
    materiales: 'Bicarbonato de sodio, vinagre, sulfato de cobre, clavos de hierro, tubos de ensayo.',
    entregable: 'Reporte Experimental de Reacciones Químicas y Problemario de Balanceo por Tanteo.'
  },
  {
    id: 'f6-sab-20',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 70,
    temaTitulo: 'Propiedades de ácidos y bases, escala de pH y reacciones de neutralización',
    tituloProyecto: 'La Escala de la Acidez: Indicadores Naturales, pH y Neutralización Química',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Distingue propiedades de ácidos y bases en el entorno a partir de indicadores de pH caseros (col morada) y deducir productos de reacciones de neutralización (ácido + base $\\rightarrow$ sal + agua).',
    detonadoras: [
      '¿Por qué el jugo de limón sabe agrio y el jabón se siente resbaloso y amargo?',
      '¿Cómo indica la antocianina de la col morada el nivel de pH de una sustancia virando de rojo (ácido) a verde/amarillo (base)?',
      '¿Cómo neutraliza un antiácido estomacal el exceso de ácido clorhídrico en el estómago?'
    ],
    inicioDetalle: 'Preparación de extracto de col morada con alcohol y adición a vinagre y bicarbonato.',
    desarrolloDetalle: 'Laboratorio de Titulación Cualitativa de pH: Medir el pH de 10 sustancias cotidianas (leche, refresco, cloro, café, saliva, limpiador de cañerías) y realizar una reacción de neutralización midiendo el cambio de temperatura.',
    cierreDetalle: 'Construcción de la Escala de pH Ilustrada del salón y análisis del impacto de la lluvia ácida.',
    evaluacionCriterios: [
      'Caracterización de propiedades organolépticas y químicas de ácidos y bases',
      'Interpretación correcta de la escala de pH (0 a 14: ácido, neutro, básico)',
      'Escritura y comprensión de reacciones químicas de neutralización'
    ],
    materiales: 'Col morada, tubos de ensayo, vinagre, antiácidos, jugo de naranja, tiras de pH.',
    entregable: 'Muestrario Gráfico de la Escala de pH y Reporte de Neutralización Química.'
  },
  // Planeaciones 71 a 100 de Saberes y Pensamiento Científico
  {
    id: 'f6-sab-21',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 71,
    temaTitulo: 'Regularidades y sucesiones con progresión aritmética',
    tituloProyecto: 'El Patrón Secreto: Sucesiones Aritméticas, Regla General $an + b$ y Modelado',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Representa algebraicamente una sucesión con progresión aritmética de figuras y números, deduciendo la regla general de la forma $an+b$ y prediciendo términos lejanos.',
    detonadoras: ['¿Cómo encontramos el término número 100 de una serie sin tener que escribir todos los números intermedios?', '¿Qué representa la diferencia común $a$ en la fórmula general?'],
    inicioDetalle: 'Secuencia de figuras con fósforos o bloques de madera.',
    desarrolloDetalle: 'Taller de Álgebra de Sucesiones: Tabular términos, calcular primeras diferencias constantes y deducir fórmulas algebraicas.',
    cierreDetalle: 'Resolución de problemas de series aplicadas al ahorro y crecimiento poblacional.',
    evaluacionCriterios: ['Deducción rigurosa de la regla general $an+b$', 'Cálculo exacto de términos en posiciones enésimas', 'Modelación de patrones geométricos y numéricos'],
    materiales: 'Palillos de madera, hojas cuadriculadas, calculadoras.',
    entregable: 'Problemario de Sucesiones Aritméticas y Modelos Geométricos.'
  },
  {
    id: 'f6-sab-22',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 72,
    temaTitulo: 'Progresiones cuadráticas y sucesiones con segundas diferencias',
    tituloProyecto: 'El Vuelo Cuadrático: Sucesiones de Segundo Orden ($an^2 + bn + c$)',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Representa algebraicamente una sucesión con progresión cuadrática de figuras y números, empleando el método de segundas diferencias ($2a, 3a+b, a+b+c$).',
    detonadoras: ['¿Por qué en algunas sucesiones la diferencia entre términos no es constante pero la segunda diferencia sí lo es?', '¿Cómo deducimos los coeficientes $a, b, c$ del polinomio cuadrático?'],
    inicioDetalle: 'Construcción de figuras triangulares y cuadradas con fichas.',
    desarrolloDetalle: 'Laboratorio de Segundas Diferencias: Resolver sistemas de ecuaciones para hallar $a, b, c$ y comprobar la fórmula para $n=50$.',
    cierreDetalle: 'Evaluación formativa y aplicaciones en física y economía.',
    evaluacionCriterios: ['Aplicación del método de diferencias finitas', 'Obtención de la fórmula cuadrática general', 'Comprobación algebraica de resultados'],
    materiales: 'Fichas plásticas, hojas de trabajo, calculadoras.',
    entregable: 'Guía de Sucesiones Cuadráticas y Modelación Geométrica.'
  },
  {
    id: 'f6-sab-23',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 73,
    temaTitulo: 'Construcción de triángulos y cuadriláteros con regla y compás',
    tituloProyecto: 'Geometría Euclidiana: Mediatriz, Bisectriz, Rectas Notables y Puntos de Cruce',
    ejes: ['Pensamiento Crítico', 'Artes y Experiencias Estéticas'],
    pda: 'Fase 6 (1º Secundaria) - Utiliza regla y compás para trazar: mediatriz de un segmento, bisectriz de un ángulo, rectas perpendiculares/paralelas y rectas notables del triángulo (circuncentro, incentro, baricentro, ortocentro).',
    detonadoras: ['¿Por qué la regla sin graduar y el compás fueron las únicas herramientas sagradas de los geómetras griegos?', '¿Dónde se ubica el centro de gravedad (baricentro) de cualquier triángulo?'],
    inicioDetalle: 'Equilibrar un triángulo de cartón sobre la punta de un lápiz apoyado en su baricentro.',
    desarrolloDetalle: 'Taller de Trazo Geométrico de Precisión: Trazar con compás las 3 mediatrices (circuncentro) y circunscribir la circunferencia perfecta.',
    cierreDetalle: 'Galería de láminas geométricas y teselaciones.',
    evaluacionCriterios: ['Precisión milimétrica en trazos con compás y regla', 'Identificación y propiedades de las 4 rectas notables', 'Limpieza y rigor geométrico en las láminas'],
    materiales: 'Juegos de geometría de precisión, compás metálico, hojas blancas.',
    entregable: 'Carpeta de Láminas Geométricas: Puntos y Rectas Notables del Triángulo.'
  },
  {
    id: 'f6-sab-24',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 74,
    temaTitulo: 'Polígonos regulares y teselados del plano',
    tituloProyecto: 'El Mosaico de Escher: Ángulos Interiores, Polígonos Regulares y Teselaciones',
    ejes: ['Artes y Experiencias Estéticas', 'Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Calcula la suma de ángulos interiores de polígonos ($(n-2) \\times 180^{\\circ}$) y determina cuáles polígonos regulares pueden teselar el plano sin dejar huecos ni encimarse.',
    detonadoras: ['¿Por qué solo los triángulos equiláteros, cuadrados y hexágonos regulares pueden cubrir un piso perfectamente sin dejar espacios?', '¿Cómo calculamos el ángulo interior de un icoságono (20 lados)?'],
    inicioDetalle: 'Análisis de mosaicos de la Alhambra de Granada y obras de M.C. Escher.',
    desarrolloDetalle: 'Taller de Mosaicos Geométricos: Deducir la fórmula de ángulos interiores y diseñar un teselado artístico semirregular con hexágonos y triángulos.',
    cierreDetalle: 'Exposición de teselados y comprobación de suma de ángulos en los vértices ($360^{\\circ}$).',
    evaluacionCriterios: ['Deducción y uso de fórmulas de ángulos interiores y centrales', 'Justificación matemática de la teselación del plano', 'Creatividad estética en el diseño del mosaico'],
    materiales: 'Reglas, transportadores, compás, cartulinas, colores.',
    entregable: 'Lámina Artística de Teselado y Memoria de Cálculo de Ángulos Poligonales.'
  },
  {
    id: 'f6-sab-25',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 75,
    temaTitulo: 'Criterios de congruencia y semejanza de triángulos',
    tituloProyecto: 'Triángulos a Escala: Criterios LAL, LLL, ALA y el Teorema de Tales',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Aplica las propiedades de congruencia (LLL, LAL, ALA) y semejanza (AA, LLL, LAL) de triángulos para resolver problemas de cálculo de sombras y distancias inaccesibles mediante el Teorema de Tales.',
    detonadoras: ['¿Cómo calculó Tales de Mileto la altura de la Gran Pirámide de Guiza usando solo un bastón y la sombra proyectada?', '¿Qué condiciones exactas garantizan que dos figuras sean geométricamente semejantes?'],
    inicioDetalle: 'Proyección de sombras en el patio escolar a diferentes horas del día.',
    desarrolloDetalle: 'Laboratorio de Semejanza: Resolver problemas de proporcionalidad directa en triángulos semejantes y calcular alturas de postes escolares con el Teorema de Tales.',
    cierreDetalle: 'Coevaluación de ejercicios geométricos de aplicación.',
    evaluacionCriterios: ['Identificación y aplicación de criterios de semejanza', 'Uso riguroso del Teorema de Tales en problemas contextualizados', 'Cálculo de razones de semejanza y escala'],
    materiales: 'Cintas métricas, bastones de madera, hojas cuadriculadas.',
    entregable: 'Problemario Aplicado de Semejanza de Triángulos y Teorema de Tales.'
  },
  {
    id: 'f6-sab-26',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 76,
    temaTitulo: 'Cálculo de volumen y desarrollos planos de cilindros, conos y esferas',
    tituloProyecto: 'Geometría del Espacio: Desarrollos Planos, Sólidos de Revolución y Volúmenes',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Explora y construye desarrollos planos de conos, cilindros y pirámides, calcula sus volúmenes y analiza la relación $V_{\\text{cono}} = \\frac{1}{3} V_{\\text{cilindro}}$ y $V_{\\text{esfera}} = \\frac{4}{3}\\pi r^3$.',
    detonadoras: ['¿Por qué se necesitan exactamente 3 conos llenos de agua para llenar un cilindro de la misma base y altura?', '¿Cómo se genera un sólido de revolución al girar un triángulo o rectángulo en un eje?'],
    inicioDetalle: 'Rotación rápida de figuras planas en un taladro para visualizar sólidos 3D.',
    desarrolloDetalle: 'Taller de Construcción de Cuerpos Geométricos: Trazar en cartulina el desarrollo plano de conos y cilindros con lengüetas de pegado y calcular su capacidad en mililitros.',
    cierreDetalle: 'Comprobación experimental de capacidades con arena o agua coloreada.',
    evaluacionCriterios: ['Construcción exacta de desarrollos planos con compás y fórmulas de arco', 'Cálculo algebraico preciso de áreas totales y volúmenes', 'Comprobación de relaciones de volumen entre sólidos'],
    materiales: 'Cartulina bristol, compás, pegamento, tijeras, probetas graduadas.',
    entregable: 'Set de Cuerpos Geométricos 3D y Memoria de Cálculo de Capacidad y Volumen.'
  },
  {
    id: 'f6-sab-27',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 77,
    temaTitulo: 'Redes tróficas, pirámides de biomasa y fotosíntesis',
    tituloProyecto: 'La Red de la Vida: Productores, Consumidores, Descomponedores y la Regla del 10%',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Representa la transferencia de materia y energía en redes tróficas y pirámides ecológicas, explicando la fotosíntesis ($6\\text{CO}_2 + 6\\text{H}_2\\text{O} \\rightarrow \\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2$) y la pérdida de energía en cada eslabón.',
    detonadoras: ['¿Por qué la energía disponible disminuye un 90% en cada nivel trófico (Regla del 10%)?', '¿Qué ocurriría en un ecosistema si desaparecen los descomponedores (hongos y bacterias)?'],
    inicioDetalle: 'Dinámica de la Red Alimentaria con estambres entre estudiantes representando especies.',
    desarrolloDetalle: 'Laboratorio de Fotosíntesis: Comprobar la producción de oxígeno en la planta acuática Elodea expuesta a la luz solar y diseñar una pirámide trófica cuantitativa.',
    cierreDetalle: 'Modelación de escenarios de extinción de un depredador tope.',
    evaluacionCriterios: ['Explicación bioquímica básica de la fotosíntesis', 'Construcción y análisis de redes tróficas y pirámides de energía', 'Comprensión de la interdependencia ecológica'],
    materiales: 'Plantas Elodea, bicarbonato, lámparas, tubos de ensayo, estambres.',
    entregable: 'Modelo Tridimensional de Pirámide Trófica y Reporte de Fotosíntesis.'
  },
  {
    id: 'f6-sab-28',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 78,
    temaTitulo: 'Ciclos biogeoquímicos del carbono y nitrógeno y calentamiento global',
    tituloProyecto: 'El Viaje de los Elementos: Ciclos del Carbono, Nitrógeno y Efecto Invernadero',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Analiza las prácticas de consumo humano que alteran los ciclos biogeoquímicos del carbono y nitrógeno, explicando sus efectos en el calentamiento global y la acidificación de océanos.',
    detonadoras: ['¿Cómo circula un átomo de carbono desde la atmósfera hacia una planta, luego a un animal y finalmente a un combustible fósil?', '¿Por qué la quema desmedida de hidrocarburos rompe el equilibrio térmico planetario?'],
    inicioDetalle: 'Simulación del efecto invernadero en frascos de vidrio con termómetro.',
    desarrolloDetalle: 'Taller de Ciclos Biogeoquímicos: Elaborar un diorama interactivo del ciclo del carbono y nitrógeno, cuantificando la huella de carbono personal y proponiendo acciones de mitigación.',
    cierreDetalle: 'Compromiso escolar de reducción de emisiones y reforestación.',
    evaluacionCriterios: ['Representación de etapas clave de los ciclos del carbono y nitrógeno', 'Explicación del mecanismo físico-químico del efecto invernadero', 'Propuestas sustentables de reducción de huella ecológica'],
    materiales: 'Frascos de vidrio, termómetros, plastilina, cajas de cartón.',
    entregable: 'Diorama Interactivo de los Ciclos Biogeoquímicos y Plan de Reducción de Emisiones.'
  },
  {
    id: 'f6-sab-29',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 79,
    temaTitulo: 'Genética mendeliana, ADN y biotecnología moderna',
    tituloProyecto: 'El Código Hereditario: Leyes de Mendel, Cuadros de Punnett y la Molécula de ADN',
    ejes: ['Pensamiento Crítico', 'Inclusión'],
    pda: 'Fase 6 (1º Secundaria) - Modela la estructura del ADN en doble hélice, resuelve problemas de herencia genética con cuadros de Punnett aplicando las Leyes de Mendel y debate dilemas éticos de la ingeniería genética.',
    detonadoras: ['¿Por qué los hijos heredan rasgos de ambos padres pero pueden expresar características de los abuelos?', '¿Cómo se aparean las bases nitrogenadas Adenina-Timina y Guanina-Citosina en el ADN?'],
    inicioDetalle: 'Extracción casera de ADN de fresa con detergente y alcohol frío.',
    desarrolloDetalle: 'Taller de Genética: Construir un modelo tridimensional de la doble hélice con gomitas y palillos, resolver cruzas monohíbridas con cuadros de Punnett y calcular porcentajes fenotípicos y genotípicos.',
    cierreDetalle: 'Mesa redonda sobre transgénicos y terapia génica.',
    evaluacionCriterios: ['Extracción y modelado correcto de la molécula de ADN', 'Resolución precisa de cuadros de Punnett y leyes mendelianas', 'Postura bioética fundamentada sobre edición genética'],
    materiales: 'Fresas, alcohol isopropílico, gomitas de colores, palillos, cuadros de Punnett.',
    entregable: 'Modelo 3D de Doble Hélice de ADN y Problemario de Cruzas Genéticas.'
  },
  {
    id: 'f6-sab-30',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 80,
    temaTitulo: 'Vacunas, sistema inmunológico y prevención de epidemias',
    tituloProyecto: 'El Escuadrón Inmune: Linfocitos, Anticuerpos, Vacunas y Salud Pública',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Valora la importancia del sistema inmunológico y el uso de vacunas para la prevención y erradicación de enfermedades infecciosas, contrastando evidencias científicas con mitos antivacunas.',
    detonadoras: ['¿Cómo "entrenan" las vacunas a los linfocitos T y B para producir anticuerpos de memoria sin enfermarnos gravemente?', '¿Qué es la inmunidad de rebaño y por qué vacunarse es un acto de solidaridad social?'],
    inicioDetalle: 'Línea del tiempo histórica: De la viruela y Edward Jenner a las vacunas de ARNm.',
    desarrolloDetalle: 'Simulación Epidemiológica: Modelar con fichas la propagación de un virus en una población con 0%, 50% y 90% de vacunados, analizando la curva de contagios y redactar una infografía médica.',
    cierreDetalle: 'Revisión de la Cartilla Nacional de Vacunación.',
    evaluacionCriterios: ['Explicación de la respuesta inmunológica primaria y secundaria', 'Comprobación matemática del impacto de la inmunidad colectiva', 'Argumentación científica frente a noticias falsas sobre vacunas'],
    materiales: 'Fichas de colores para simulación de contagios, cartillas de vacunación modelo.',
    entregable: 'Infografía Médica Ilustrada "Cómo Funcionan las Vacunas en Nuestro Sistema Inmune".'
  },
  {
    id: 'f6-sab-31',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 81,
    temaTitulo: 'Movimiento rectilíneo uniforme (MRU) y acelerado (MRUA)',
    tituloProyecto: 'Velocidad y Aceleración: Cinemática, Gráficas Posición-Tiempo y Seguridad Vial',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (2º Secundaria) - Identifica y calcula velocidad ($v = d/t$), aceleración ($a = \\frac{v_f - v_0}{t}$) y distancia en movimientos rectilíneos, interpretando gráficas de posición-tiempo y velocidad-tiempo aplicadas a la seguridad vial.',
    detonadoras: ['¿Por qué la distancia de frenado de un auto se cuadruplica al duplicar la velocidad?', '¿Cómo se interpreta la pendiente de una gráfica posición-tiempo como la velocidad?'],
    inicioDetalle: 'Experimento con carrito en plano inclinado midiendo tiempos con fotoceldas o cronómetros.',
    desarrolloDetalle: 'Laboratorio de Cinemática: Tabular datos de distancia y tiempo, graficar curvas en papel milimétrico, calcular aceleración y modelar zonas de frenado seguro en cruces peatonales.',
    cierreDetalle: 'Campaña de seguridad vial escolar con datos de física.',
    evaluacionCriterios: ['Cálculo correcto de velocidad y aceleración en el SI ($\\text{m/s}$, $\\text{m/s}^2$)', 'Interpretación rigurosa de pendientes en gráficas cinemáticas', 'Aplicación de la física en la prevención de accidentes viales'],
    materiales: 'Planos inclinados, carritos, cronómetros, cinta métrica, papel milimétrico.',
    entregable: 'Reporte Experimental de Cinemática con Gráficas $x-t$, $v-t$ y Decálogo Vial.'
  },
  {
    id: 'f6-sab-32',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 82,
    temaTitulo: 'Calor, temperatura y equilibrio térmico',
    tituloProyecto: 'El Fuego Invisible: Modelo Cinético de Partículas, Escalas Termométricas y Calorimetría',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Diferencia entre calor (energía en tránsito) y temperatura (energía cinética promedio), interpreta el equilibrio térmico mediante el modelo de partículas y convierte escalas (°C, °F, K).',
    detonadoras: ['¿Por qué un iceberg gigante tiene más calor total que una taza de café hirviendo aunque su temperatura sea menor?', '¿Cómo ocurre la transferencia de calor por conducción, convección y radiación?'],
    inicioDetalle: 'Demostración de difusión de tinta en agua fría vs agua caliente.',
    desarrolloDetalle: 'Laboratorio de Calorimetría: Medir temperaturas de mezclas de agua a distintas temperaturas para comprobar el Principio de Equilibrio Térmico ($Q_{\\text{ganado}} = -Q_{\\text{perdido}}$) y calibrar un termómetro casero.',
    cierreDetalle: 'Conversión de temperaturas entre Celsius, Kelvin y Fahrenheit.',
    evaluacionCriterios: ['Diferenciación conceptual entre calor y temperatura', 'Explicación del equilibrio térmico con el modelo corpuscular', 'Conversión matemática precisa de escalas de temperatura'],
    materiales: 'Termómetros de laboratorio, vasos de unicel (calorímetros), agua fría y caliente.',
    entregable: 'Reporte de Práctica de Calorimetría y Modelo Corpuscular de la Temperatura.'
  },
  {
    id: 'f6-sab-33',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 83,
    temaTitulo: 'Electricidad, circuitos eléctricos y Ley de Ohm',
    tituloProyecto: 'El Flujo de Electrones: Circuitos en Serie, Paralelo y la Ley de Ohm ($V = I \\cdot R$)',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Experimenta con circuitos eléctricos en serie y en paralelo, calcula voltaje, corriente y resistencia mediante la Ley de Ohm ($V=IR$) y analiza medidas de seguridad eléctrica en el hogar.',
    detonadoras: ['¿Por qué si se funde un foco en una serie navideña antigua se apagan todos (serie), pero en una casa los focos funcionan de forma independiente (paralelo)?', '¿Qué relación existe entre la resistencia de un cable y la corriente eléctrica que fluye por él?'],
    inicioDetalle: 'Construcción de una pila casera con limones, monedas de cobre y clavos de zinc.',
    desarrolloDetalle: 'Laboratorio de Circuitos: Conectar circuitos con protoboard o cables, focos LED, resistencias y pilas, medir voltaje y corriente con multímetro y calcular potencias eléctricas ($P = V \\cdot I$).',
    cierreDetalle: 'Diseño del plano eléctrico de una maqueta de casa con interruptores.',
    evaluacionCriterios: ['Armado y diferenciación entre circuitos serie y paralelo', 'Aplicación matemática de la Ley de Ohm con unidades (Volts, Amperes, Ohms)', 'Comprensión y aplicación de protocolos de seguridad eléctrica'],
    materiales: 'Pilas de 9V, cables caimán, focos LED, multímetros escolares, interruptores.',
    entregable: 'Maqueta con Circuito Eléctrico Funcional y Memoria de Cálculo de la Ley de Ohm.'
  },
  {
    id: 'f6-sab-34',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 84,
    temaTitulo: 'Magnetismo, electromagnetismo y motores eléctricos',
    tituloProyecto: 'Fuerzas Invisibles: Campos Magnéticos, Inducción de Faraday y el Motor Eléctrico',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Relaciona la electricidad y el magnetismo (electromagnetismo), experimenta con electroimanes y explica el funcionamiento de motores y generadores basados en la Ley de Inducción de Faraday.',
    detonadoras: ['¿Cómo descubrió Oersted en 1820 que una corriente eléctrica desvía la aguja de una brújula magnética?', '¿Cómo convierte un motor eléctrico la energía eléctrica en energía mecánica de rotación?'],
    inicioDetalle: 'Visualización de líneas de campo magnético con limadura de hierro sobre un imán.',
    desarrolloDetalle: 'Construcción de un Electroimán y Motor Eléctrico Homopolar: Enrollar alambre esmaltado sobre un clavo para crear un electroimán potente y construir un motor miniatura con una pila, imán de neodimio y alambre de cobre.',
    cierreDetalle: 'Explicación del principio de generación eléctrica en presas hidroeléctricas y aerogeneradores.',
    evaluacionCriterios: ['Construcción funcional del electroimán y motor eléctrico casero', 'Explicación teórica de la relación entre corriente eléctrica y campo magnético', 'Identificación de aplicaciones industriales del electromagnetismo'],
    materiales: 'Alambre de cobre esmaltado, clavos grandes, pilas D, imanes de neodimio, clips.',
    entregable: 'Prototipo de Motor Eléctrico Funcional y Reporte de Inducción Electromagnética.'
  },
  {
    id: 'f6-sab-35',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 85,
    temaTitulo: 'Ondas electromagnéticas, luz y telecomunicaciones',
    tituloProyecto: 'El Espectro de la Luz: Ondas Electromagnéticas, Óptica y Telecomunicaciones',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Explica el comportamiento de la luz y las ondas electromagnéticas (frecuencia, longitud de onda, velocidad $c = \\lambda \\cdot f$), analizando su aplicación en fibra óptica, radio, microondas y telefonía.',
    detonadoras: ['¿Por qué la luz viaja a $300,000\\text{ km/s}$ en el vacío pero se frena y desvía al pasar por agua o vidrio (refracción)?', '¿Qué diferencia a los rayos X y gamma de las ondas de radio en el espectro electromagnético?'],
    inicioDetalle: 'Descomposición de la luz blanca en los colores del arcoíris con un prisma de cristal.',
    desarrolloDetalle: 'Taller de Óptica y Ondas: Construir un espectroscopio casero con un disco CD para analizar la luz de focos LED y tubos fluorescentes, y modelar la transmisión de datos por fibra óptica.',
    cierreDetalle: 'Presentación de infografías sobre el uso de microondas y satélites.',
    evaluacionCriterios: ['Identificación de las regiones del espectro electromagnético', 'Explicación de fenómenos de reflexión, refracción y difracción de la luz', 'Construcción y calibración del espectroscopio casero'],
    materiales: 'Prismas ópticos, discos CD usados, cajas de cartón, punteros láser escolares.',
    entregable: 'Espectroscopio Óptico Calibrado e Infografía del Espectro Electromagnético.'
  },
  {
    id: 'f6-sab-36',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 86,
    temaTitulo: 'Gravitación universal y estructura del Sistema Solar',
    tituloProyecto: 'La Danza de los Planetas: Ley de Gravitación Universal de Newton y Leyes de Kepler',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Relaciona la gravitación universal ($F = G\\frac{m_1 m_2}{r^2}$) con el movimiento orbital de los planetas, las mareas terrestres y la exploración espacial.',
    detonadoras: ['¿Por qué la Luna no cae sobre la Tierra a pesar de la gravedad (velocidad orbital centrípeta)?', '¿Cómo describe la 1ª Ley de Kepler las órbitas elípticas con el Sol en uno de sus focos?'],
    inicioDetalle: 'Demostración de tela elástica espacial con canicas pesadas deformando el espacio-tiempo.',
    desarrolloDetalle: 'Modelado Orbital a Escala: Trazar elipses orbitales con chinchetas y cordel demostrando las Leyes de Kepler y calcular el peso de un astronauta en Marte, Júpiter y la Luna.',
    cierreDetalle: 'Simulación de trayectorias de satélites artificiales con software astronómico.',
    evaluacionCriterios: ['Comprensión de la fuerza gravitacional y su relación con la masa y distancia', 'Trazo y fundamentación geométrica de las Leyes de Kepler', 'Cálculo comparativo de peso y gravedad en distintos cuerpos celestes'],
    materiales: 'Tablas de corcho, chinchetas, cordel, cartulina, simulador digital del sistema solar.',
    entregable: 'Maqueta Orbital de Leyes de Kepler y Reporte de Gravitación Universal.'
  },
  {
    id: 'f6-sab-37',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 87,
    temaTitulo: 'Mezclas homogéneas, heterogéneas y métodos de separación',
    tituloProyecto: 'El Laboratorio de Separaciones: Decantación, Filtración, Destilación y Cromatografía',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Clasifica mezclas en homogéneas (disoluciones) y heterogéneas (coloides, suspensiones) y deduce métodos físicos de separación (filtración, decantación, evaporación, cromatografía, cristalización y destilación).',
    detonadoras: ['¿Cómo podemos purificar agua de mar para hacerla potable mediante destilación térmica?', '¿Cómo separa la cromatografía en papel los diferentes pigmentos de la tinta de un plumón?'],
    inicioDetalle: 'Demostración del Efecto Tyndall con puntero láser en disolución de sal vs leche (coloide).',
    desarrolloDetalle: 'Circuito Experimental de Separación: Separar una mezcla compleja de 4 componentes (arena, sal, limadura de hierro y agua) usando imán, filtración y evaporación secuencial.',
    cierreDetalle: 'Cromatografía de tintas en tiras de papel filtro con alcohol.',
    evaluacionCriterios: ['Diferenciación conceptual entre disolución, coloide y suspensión', 'Selección lógica y ejecución de métodos de separación según propiedades físicas', 'Manejo seguro de material de vidrio y mecheros de laboratorio'],
    materiales: 'Arena, sal, limadura de hierro, papel filtro, embudos, imanes, alcohol, plumones.',
    entregable: 'Reporte de Práctica Experimental de Métodos de Separación de Mezclas y Cromatograma.'
  },
  {
    id: 'f6-sab-38',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 88,
    temaTitulo: 'Concentración de disoluciones: porcentaje en masa, volumen y partes por millón (ppm)',
    tituloProyecto: 'La Dosis Exacta: Porcentaje en Masa (%m/m), Volumen (%v/v) y Concentración de Contaminantes en ppm',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Analiza y calcula la concentración de sustancias en mezclas de uso cotidiano (% en masa, % en volumen y ppm en agua/aire), evaluando riesgos para la salud.',
    detonadoras: ['¿Qué significa que el alcohol desinfectante tenga una concentración del $70\\%\\text{ v/v}$?', '¿Por qué una concentración de plomo de apenas $0.01\\text{ ppm}$ en agua potable ya es tóxica para el cerebro?'],
    inicioDetalle: 'Análisis de etiquetas comerciales de sueros orales, blanqueadores y bebidas azucaradas.',
    desarrolloDetalle: 'Taller de Preparación de Disoluciones: Preparar con precisión disoluciones al $5\\%$, $10\\%$ y $15\\%$ de soluto usando balanza y matraces aforados, resolviendo problemas de concentración estequiométrica.',
    cierreDetalle: 'Cálculo de la concentración de contaminantes en aire durante contingencias ambientales.',
    evaluacionCriterios: ['Cálculo algebraico preciso de fórmulas de porcentaje y ppm', 'Preparación experimental de disoluciones con material volumétrico', 'Conciencia crítica sobre contaminantes en agua y alimentos'],
    materiales: 'Balanza, matraces aforados o probetas, sal, azúcar, colorante vegetal.',
    entregable: 'Problemario de Concentración Química y Ficha Técnica de Control de Calidad.'
  },
  {
    id: 'f6-sab-39',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 89,
    temaTitulo: 'Enlaces químicos: iónico, covalente y metálico',
    tituloProyecto: 'La Unión Hace la Molécula: Enlaces Iónicos, Covalentes y Conductividad Eléctrica',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Experimenta y diferencia compuestos iónicos, covalentes y metálicos con base en sus propiedades físicas (solubilidad, punto de fusión y conductividad eléctrica en estado sólido y disuelto).',
    detonadoras: ['¿Por qué la sal disuelta en agua enciende un foco (electrolito) pero el azúcar disuelto no conduce electricidad?', '¿Cómo determina la diferencia de electronegatividad de Pauling el tipo de enlace químico?'],
    inicioDetalle: 'Circuito probador de conductividad con foco LED y vasos con diferentes sustancias.',
    desarrolloDetalle: 'Laboratorio de Conductividad y Enlaces: Probar conductividad en sal común ($\text{NaCl}$), azúcar ($\text{C}_{12}\text{H}_{22}\text{O}_{11}$), sulfato de cobre y aceite, clasificando los enlaces con base en la electronegatividad.',
    cierreDetalle: 'Modelado molecular 3D de cristales iónicos vs moléculas covalentes.',
    evaluacionCriterios: ['Diferenciación experimental de electrolitos y no electrolitos', 'Comprensión de la transferencia vs compartición de electrones', 'Predicción del tipo de enlace según la escala de Pauling'],
    materiales: 'Circuito detector con pila y LED, sal, azúcar, agua destilada, electrodos de grafito.',
    entregable: 'Reporte de Laboratorio de Enlaces Químicos y Maqueta de Redes Cristalinas.'
  },
  {
    id: 'f6-sab-40',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 90,
    temaTitulo: 'Reacciones de óxido-reducción (Redox) y corrosión',
    tituloProyecto: 'La Danza de los Electrones: Reacciones Redox, Número de Oxidación y Protección Galvánica',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Identifica reacciones redox en el entorno (combustión, respiración celular, corrosión de metales), asigna números de oxidación y determina el agente oxidante y reductor.',
    detonadoras: ['¿Por qué un clavo de hierro se oxida al aire libre perdiendo electrones mientras el oxígeno se reduce?', '¿Cómo protegen los ánodos de sacrificio de zinc el casco de los barcos y las tuberías de gas?'],
    inicioDetalle: 'Reacción de una manzana cortada oscureciéndose por oxidación enzimática vs tratada con jugo de limón.',
    desarrolloDetalle: 'Laboratorio de Redox y Electroquímica: Sumergir clavos de hierro en solución de sulfato de cobre observando el depósito de cobre metálico ($Fe + Cu^{2+} \\rightarrow Fe^{2+} + Cu$), asignando números de oxidación.',
    cierreDetalle: 'Balanceo de una reacción redox sencilla por método de cambio de número de oxidación.',
    evaluacionCriterios: ['Asignación correcta de números de oxidación a elementos y compuestos', 'Identificación precisa de la especie oxidada, reducida y agentes redox', 'Comprensión de aplicaciones industriales y prevención de la corrosión'],
    materiales: 'Sulfato de cobre, clavos de hierro limpios, ácido clorhídrico diluido, manzana.',
    entregable: 'Reporte Experimental de Reacciones Redox y Guía de Prevención de la Corrosión.'
  },
  {
    id: 'f6-sab-41',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 91,
    temaTitulo: 'Los alimentos como fuente de energía química: macromoléculas',
    tituloProyecto: 'Energía Celular: Carbohidratos, Lípidos, Proteínas y Calorimetría Nutricional',
    ejes: ['Vida Saludable', 'Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Identifica carbohidratos, lípidos y proteínas mediante pruebas químicas cualitativas (Lugol, Biuret, Sudán III), calculando el aporte energético (kcal) para una dieta equilibrada.',
    detonadoras: ['¿Cómo almacena nuestro cuerpo la energía química en enlaces moleculares de glucosa y triglicéridos?', '¿Qué prueba bioquímica identifica el almidón en una papa o el gluten en el pan?'],
    inicioDetalle: 'Prueba rápida con tintura de yodo (Lugol) sobre pan, manzana y papa.',
    desarrolloDetalle: 'Laboratorio de Macromoléculas: Aplicar reactivo de Biuret para detectar proteínas en clara de huevo y leche, y reactivo de Sudán o prueba de traslúcido para grasas, diseñando un menú balanceado.',
    cierreDetalle: 'Cálculo del gasto calórico basal y balance energético diario en adolescentes.',
    evaluacionCriterios: ['Identificación experimental de macronutrientes con reactivos químicos', 'Explicación del valor energético de carbohidratos ($4\\text{ kcal/g}$), proteínas ($4\\text{ kcal/g}$) y grasas ($9\\text{ kcal/g}$)', 'Diseño de un menú saludable adaptado a requerimientos reales'],
    materiales: 'Lugol, reactivo de Biuret, clara de huevo, aceite, pan, tubos de ensayo.',
    entregable: 'Reporte de Laboratorio Bioquímico de Alimentos y Plan Nutricional Balanceado.'
  },
  {
    id: 'f6-sab-42',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 92,
    temaTitulo: 'Química verde y desarrollo sustentable en la industria',
    tituloProyecto: 'Química para el Planeta: Los 12 Principios de la Química Verde y Bioplásticos',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Evalúa los 12 principios de la Química Verde (economía atómica, degradabilidad, prevención de residuos) y sintetiza un bioplástico biodegradable a base de almidón de maíz.',
    detonadoras: ['¿Cómo puede la síntesis química producir materiales útiles sin generar residuos tóxicos ni dañar la capa de ozono?', '¿Cómo fabricamos un plástico 100% compostable en el laboratorio escolar?'],
    inicioDetalle: 'Análisis de la persistencia de los polímeros sintéticos (más de 400 años en degradarse).',
    desarrolloDetalle: 'Síntesis de Bioplástico de Almidón: Mezclar maicena, agua, glicerina y vinagre, calentar a fuego medio hasta formar una pasta viscosa, moldear láminas y probar su resistencia mecánica y biodegradabilidad.',
    cierreDetalle: 'Debate sobre la transición hacia una economía circular y sustentabilidad industrial.',
    evaluacionCriterios: ['Sustentación teórica de los principios de la Química Verde', 'Ejecución rigurosa del protocolo de síntesis del biopolímero', 'Evaluación de impacto ambiental y viabilidad del producto'],
    materiales: 'Fécula de maíz, glicerina pura, vinagre blanco, recipientes térmicos, moldes de silicón.',
    entregable: 'Muestrario de Bioplástico Biodegradable Fabricado y Ensayo de Química Verde.'
  },
  {
    id: 'f6-sab-43',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 93,
    temaTitulo: 'Ecuaciones lineales de la forma $Ax+B=C$ y $Ax+B=Cx+D$',
    tituloProyecto: 'La Balanza Algebraica: Propiedades de la Igualdad y Despeje de Incógnitas',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Resuelve ecuaciones lineales de la forma $Ax+B=C$ y $Ax+B=Cx+D$ utilizando las propiedades uniformes de la igualdad y modela problemas de perímetros y costos.',
    detonadoras: ['¿Por qué una ecuación es como una balanza de dos platillos en perfecto equilibrio?', '¿Qué operaciones inversas debemos aplicar en ambos miembros para despejar la incógnita $x$?'],
    inicioDetalle: 'Simulador de balanza interactiva agregando y quitando pesas desconocidas.',
    desarrolloDetalle: 'Taller de Despeje y Modelación: Resolver ecuaciones algebraicas con paréntesis y términos en ambos miembros, verificando siempre la igualdad numérica final.',
    cierreDetalle: 'Resolución de problemas de edades y perímetros geométricos modelados con ecuaciones.',
    evaluacionCriterios: ['Uso correcto de propiedades de la igualdad (uniformidad)', 'Despeje algebraico sistemático sin errores de signos', 'Comprobación de la solución en el planteamiento original'],
    materiales: 'Balanza de platillos didáctica, fichas algebraicas, hojas de trabajo.',
    entregable: 'Problemario de Ecuaciones Lineales con Comprobación y Modelación Geométrica.'
  },
  {
    id: 'f6-sab-44',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 94,
    temaTitulo: 'Funciones y variación lineal e inversa',
    tituloProyecto: 'Constantes de Cambio: Variación Directa ($y=kx$) vs Inversa ($y=k/x$) en la Ciencia',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Relaciona e interpreta la proporcionalidad directa ($y=kx$) e inversa ($y=k/x$), representándolas en tablas, gráficas hiperbólicas/rectas y expresiones algebraicas.',
    detonadoras: ['¿Por qué si aumentamos la velocidad el tiempo de viaje disminuye a la mitad (variación inversa)?', '¿Cómo se distingue una recta que pasa por el origen de una curva hiperbólica?'],
    inicioDetalle: 'Análisis de la Ley de Boyle en física: Presión vs Volumen de un gas a temperatura constante.',
    desarrolloDetalle: 'Taller de Gráficas Funcionales: Construir tablas de valores, graficar en plano cartesiano y determinar la constante de proporcionalidad $k$ en problemas de velocidad y rendimiento de combustible.',
    cierreDetalle: 'Rally de identificación de tipos de variación funcional.',
    evaluacionCriterios: ['Diferenciación conceptual y gráfica entre variación directa e inversa', 'Cálculo de la constante de proporcionalidad $k$', 'Modelación de fenómenos físicos mediante funciones'],
    materiales: 'Papel milimétrico, reglas, calculadoras, hojas de problemas.',
    entregable: 'Dossier Gráfico de Variación Funcional: Rectas y Curvas Hiperbólicas.'
  },
  {
    id: 'f6-sab-45',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 95,
    temaTitulo: 'Razones trigonométricas (seno, coseno y tangente) en triángulos rectángulos',
    tituloProyecto: 'El Triángulo Maestro: Seno, Coseno, Tangente y Topografía Escolar',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (3º Secundaria) - Resuelve problemas utilizando las razones trigonométricas seno ($\\text{cateto opuesto}/\\text{hipotenusa}$), coseno y tangente, calculando ángulos y distancias en situaciones reales.',
    detonadoras: ['¿Por qué el cociente entre el cateto opuesto y la hipotenusa de un ángulo de $30^{\\circ}$ es siempre $0.5$ sin importar el tamaño del triángulo?', '¿Cómo usan los radares de navegación y satélites la trigonometría?'],
    inicioDetalle: 'Construcción del círculo unitario trigonométrico con compás.',
    desarrolloDetalle: 'Laboratorio de Trigonometría: Calcular catetos desconocidos con $\\sin, \\cos, \\tan$ usando calculadora científica, verificando con el Teorema de Pitágoras.',
    cierreDetalle: 'Resolución de problemas de navegación aérea y pendientes de carreteras.',
    evaluacionCriterios: ['Identificación precisa de cateto opuesto, adyacente e hipotenusa', 'Uso correcto de funciones trigonométricas directas e inversas en la calculadora', 'Resolución de problemas reales de topografía y navegación'],
    materiales: 'Calculadoras científicas, tablas trigonométricas, transportadores.',
    entregable: 'Problemario de Razones Trigonométricas y Reporte de Triangulación Topográfica.'
  },
  {
    id: 'f6-sab-46',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Biología',
    materiaFolder: 'Biologia',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 96,
    temaTitulo: 'Herbolaria tradicional mexicana y validación científica de principios activos',
    tituloProyecto: 'Farmacia Ancestral: Etnobotánica, Principios Activos y Fitoterapia Científica',
    ejes: ['Interculturalidad Crítica', 'Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (1º Secundaria) - Reconoce la importancia de los saberes etnobotánicos de los pueblos originarios sobre plantas medicinales (manzanilla, árnica, epazote, gordolobo), contrastándolos con la farmacología moderna.',
    detonadoras: ['¿Cómo los conocimientos indígenas sobre plantas medicinales dieron origen a medicamentos como la aspirina (sauce blanco)?', '¿Qué precauciones químicas se deben tomar con la dosificación de infusiones y extractos?'],
    inicioDetalle: 'Identificación sensorial (olfato y vista) de 5 plantas medicinales secas.',
    desarrolloDetalle: 'Taller de Etnofarmacología: Elaborar un herbario escolar científico clasificando plantas por nombre científico, familia botánica, uso tradicional, principio activo validado e indicaciones de uso seguro.',
    cierreDetalle: 'Elaboración comunitaria de una pomada artesanal de árnica y caléndula.',
    evaluacionCriterios: ['Investigación rigurosa de principios activos botánicos', 'Valoración ética y respetuosa de la medicina tradicional originaria', 'Elaboración del herbario con fichas taxonómicas completas'],
    materiales: 'Muestras botánicas, prensas de plantas, cartulinas, frascos para pomadas.',
    entregable: 'Herbario Científico Ilustrado "Plantas Medicinales de México: Saberes y Ciencia".'
  },
  {
    id: 'f6-sab-47',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Física',
    materiaFolder: 'Fisica',
    grado: '2do_Grado',
    gradoDisplay: '2º de Secundaria',
    temaNum: 97,
    temaTitulo: 'Energía nuclear, fisión, fusión y física cuántica introductoria',
    tituloProyecto: 'El Corazón del Átomo: Fisión, Fusión Nuclear y la Ecuación de Einstein ($E=mc^2$)',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (2º Secundaria) - Indaga sobre los procesos de fisión y fusión nuclear, analiza la equivalencia masa-energía de Einstein ($E=mc^2$) y debate sobre los riesgos y beneficios de la energía nuclear (Laguna Verde).',
    detonadoras: ['¿Cómo produce el Sol su inmensa energía fusionando núcleos de hidrógeno en helio a millones de grados?', '¿Cuál es la diferencia entre la fisión del uranio en una central nuclear y la fusión solar?'],
    inicioDetalle: 'Video documental sobre la central nuclear de Laguna Verde en Veracruz.',
    desarrolloDetalle: 'Modelado Atómico Nuclear: Representar la reacción en cadena de la fisión con fichas de dominó y analizar las aplicaciones pacíficas de la medicina nuclear (radioterapia, radiografías).',
    cierreDetalle: 'Debate ético: ¿Es la energía nuclear una alternativa viable contra el cambio climático?',
    evaluacionCriterios: ['Diferenciación conceptual entre fisión y fusión nuclear', 'Comprensión del principio de equivalencia masa-energía', 'Postura crítica y argumentada sobre la seguridad y residuos nucleares'],
    materiales: 'Fichas de dominó, modelos atómicos, rotafolios para debate.',
    entregable: 'Ensayo Crítico y Modelo Infográfico "Energía Nuclear: Ciencia, Retos y Futuro".'
  },
  {
    id: 'f6-sab-48',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Química',
    materiaFolder: 'Quimica',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 98,
    temaTitulo: 'Química de los polímeros y reciclaje molecular',
    tituloProyecto: 'Mundo Plástico: Monómeros, Polímeros, Código SPI y Economía Circular',
    ejes: ['Pensamiento Crítico', 'Vida Saludable'],
    pda: 'Fase 6 (3º Secundaria) - Describe la estructura molecular de monómeros y polímeros, clasifica plásticos según el código de identificación SPI (PET, PEAD, PVC, PEBD, PP, PS) y evalúa métodos de reciclaje mecánico y químico.',
    detonadoras: ['¿Cómo se unen miles de moléculas simples (etileno) para formar una larga cadena polimérica (polietileno)?', '¿Qué significa el triángulo de flechas con número del 1 al 7 grabado en el fondo de las botellas?'],
    inicioDetalle: 'Inspección de envases plásticos recolectados en la escuela para clasificar por código SPI.',
    desarrolloDetalle: 'Laboratorio de Polímeros: Síntesis de "slime" polimérico uniendo alcohol polivinílico con borato de sodio (entrecruzamiento molecular) y prueba de pirólisis/flotabilidad para identificar plásticos desconocidos.',
    cierreDetalle: 'Plan escolar de separación y compactación de PET y Polipropileno.',
    evaluacionCriterios: ['Identificación de la estructura macromolecular de polímeros', 'Manejo del sistema de clasificación SPI y reciclabilidad', 'Diseño de un circuito sustentable de reciclaje escolar'],
    materiales: 'Pegamento blanco, bórax, muestras de envases plásticos 1-7, agua.',
    entregable: 'Muestrario Técnico de Polímeros SPI y Guía de Reciclaje Molecular Escolar.'
  },
  {
    id: 'f6-sab-49',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Matemáticas',
    materiaFolder: 'Matematicas',
    grado: '1er_Grado',
    gradoDisplay: '1º de Secundaria',
    temaNum: 99,
    temaTitulo: 'Mínimo común múltiplo (MCM) y Máximo común divisor (MCD)',
    tituloProyecto: 'Sincronía Numérica: Descomposición en Factores Primos, MCM y MCD en Problemas de Encuentro',
    ejes: ['Pensamiento Crítico'],
    pda: 'Fase 6 (1º Secundaria) - Usa criterios de divisibilidad y descomposición simultánea en factores primos para calcular el MCD y MCM, resolviendo problemas de sincronización de semáforos, rutas y repartos equitativos.',
    detonadoras: ['¿Si tres líneas de autobús salen cada 12, 15 y 20 minutos, a qué hora volverán a coincidir en la estación (MCM)?', '¿Cómo cortamos listones de diferentes longitudes en los tramos más grandes posibles sin desperdiciar nada (MCD)?'],
    inicioDetalle: 'Criba de Eratóstenes para identificar los números primos menores a 100.',
    desarrolloDetalle: 'Taller de Algoritmos Primos: Descomposición canónica en árbol de factores y método de factorización simultánea en tabla, resolviendo 5 problemas contextualizados.',
    cierreDetalle: 'Rally de problemas de sincronización y empaquetado en equipos.',
    evaluacionCriterios: ['Identificación de números primos y criterios de divisibilidad', 'Cálculo algorítmico correcto de MCD y MCM', 'Elección justificada del método adecuado según el problema'],
    materiales: 'Tablas de números primos, hojas cuadriculadas, cronómetros.',
    entregable: 'Problemario Resuelto de MCD y MCM "Sincronía y Optimización Numérica".'
  },
  {
    id: 'f6-sab-50',
    campo: 'Saberes y Pensamiento Científico',
    campoTag: 'saberes_y_pensamiento_cientifico',
    materia: 'Saberes / Ciencias',
    materiaFolder: 'Ciencias_Interdisciplinarias',
    grado: '3er_Grado',
    gradoDisplay: '3º de Secundaria',
    temaNum: 100,
    temaTitulo: 'Proyecto integrador STEM: Solución tecnológica a un problema ambiental escolar',
    tituloProyecto: 'Innovadores STEM: Diseño, Construcción y Evaluación de un Filtro Purificador de Agua Comunitario',
    ejes: ['Pensamiento Crítico', 'Vida Saludable', 'Inclusión'],
    pda: 'Fase 6 (3º Secundaria) - Integra saberes de Matemáticas, Biología, Física y Química en un proyecto STEM para diseñar, construir y evaluar un sistema de captación y purificación de agua de lluvia en la escuela.',
    detonadoras: ['¿Cómo integramos la química de coagulantes, la física de filtración, la biología de desinfección y el cálculo de volumen en un purificador?', '¿Cómo validamos la potabilidad del agua filtrada?'],
    inicioDetalle: 'Medición de la turbidez y pH del agua de lluvia recolectada en la azotea escolar.',
    desarrolloDetalle: 'Construcción del Filtro de Múltiples Lechos: En una columna transparente, colocar capas calibradas de grava, arena sílice, carbón activado y algodón, realizando pruebas de caudal ($Q = V/t$), turbidez y eliminación de patógenos con luz UV solar (método SODIS).',
    cierreDetalle: 'Inauguración del Sistema Demostrativo de Captación Pluvial Escolar.',
    evaluacionCriterios: ['Integración interdisciplinaria rigurosa de las 4 ciencias', 'Eficiencia funcional y calidad del agua filtrada', 'Documentación técnica completa del proyecto STEM'],
    materiales: 'Botellones de 20L, arena sílice, carbón activado, grava, algodón, tiras de prueba.',
    entregable: 'Prototipo Funcional de Purificador de Agua y Memoria Técnica del Proyecto STEM.'
  }
];

